"""Assembla output finale, include MKD bonus, opzionalmente zip o .skill.

Used by: Stage 8 packaging (chiamato direttamente dal Conductor).
Part of: content-forge

Usage:
    python scripts/package_target.py <artifact_dir> [--out packaged/] [--zip] [--skill] [--mkd-dir <stage-04/>]

`<artifact_dir>` è la directory dell'output del builder (es. stage-06/output/my-agent/).
`--mkd-dir` è opzionale: se fornito, include master.md & co come "bonus" nel pacchetto.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import zipfile
from datetime import datetime
from pathlib import Path


def copy_artifact(artifact_dir: Path, out_dir: Path) -> Path:
    """Copia artifact_dir in out_dir/<artifact_name>/."""
    dest = out_dir / artifact_dir.name
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(artifact_dir, dest)
    return dest


def copy_mkd_bonus(mkd_dir: Path, dest: Path) -> Path | None:
    """Copia MKD come bonus dentro dest/master-knowledge-document/."""
    if not mkd_dir.exists():
        return None
    mkd_dest = dest / "master-knowledge-document"
    mkd_dest.mkdir(parents=True, exist_ok=True)
    for f in mkd_dir.iterdir():
        if f.is_file():
            shutil.copy2(f, mkd_dest / f.name)
    return mkd_dest


def write_handoff_readme(dest: Path, artifact_name: str,
                         has_mkd_bonus: bool, qa_summary: dict | None) -> Path:
    """Scrive README.md di handoff per l'utente."""
    readme_path = dest / "HANDOFF.md"
    lines = [
        f"# Handoff — {artifact_name}",
        "",
        f"Generated by `content-forge` on {datetime.now().isoformat(timespec='seconds')}.",
        "",
        "## Cosa c'è dentro",
        "",
        f"- `{artifact_name}/`: l'artefatto richiesto",
    ]
    if has_mkd_bonus:
        lines += [
            "- `master-knowledge-document/`: 🎁 il documento perfetto ampliato (MKD)",
            "  — questo è il contenuto del sorgente espanso, strutturato, con esempi e schemi.",
            "  Anche se non l'hai richiesto esplicitamente, lo ottieni perché è la base intermedia",
            "  che ha generato il tuo artefatto. È pronto da archiviare/leggere/consultare.",
        ]
    lines += ["", "## Come usarlo", "", f"Vedi `{artifact_name}/README.md` per le istruzioni specifiche del target."]

    if qa_summary:
        lines += [
            "",
            "## QA Summary",
            "",
            f"- Coverage rate: {qa_summary.get('coverage_rate', 'n/a')}",
            f"- Schema validation: {qa_summary.get('schema_verdict', 'n/a')}",
            f"- Iterations: {qa_summary.get('iterations', 'n/a')}",
        ]

    readme_path.write_text("\n".join(lines), encoding="utf-8")
    return readme_path


def make_zip(source_dir: Path, zip_path: Path) -> Path:
    """Comprime source_dir in zip_path."""
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in source_dir.rglob("*"):
            if f.is_file():
                zf.write(f, f.relative_to(source_dir.parent))
    return zip_path


def make_skill_file(source_dir: Path, skill_path: Path) -> Path:
    """Crea un file .skill (zip con extension .skill)."""
    # Tenta di usare il package_skill.py ufficiale di Anthropic se disponibile (PATH)
    import subprocess
    try:
        result = subprocess.run(
            ["package_skill.py", str(source_dir), "--out", str(skill_path)],
            capture_output=True, text=True, timeout=60
        )
        if result.returncode == 0:
            return skill_path
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    # Fallback: zip con extension .skill
    with zipfile.ZipFile(skill_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in source_dir.rglob("*"):
            if f.is_file():
                zf.write(f, f.relative_to(source_dir.parent))
    return skill_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("artifact_dir", type=Path,
                        help="Directory dell'output del builder (es. stage-06/output/my-agent/)")
    parser.add_argument("--out", type=Path, default=Path("packaged/"),
                        help="Directory di output del pacchetto")
    parser.add_argument("--mkd-dir", type=Path,
                        help="Path a stage-04/ per includere MKD come bonus")
    parser.add_argument("--qa-summary", type=Path,
                        help="Path opzionale a qa-report.json per includere stats")
    parser.add_argument("--zip", action="store_true", help="Produci anche .zip")
    parser.add_argument("--skill", action="store_true", help="Produci anche .skill (se target=skill)")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    if not args.artifact_dir.exists():
        print(f"ERROR: artifact_dir non esiste: {args.artifact_dir}", file=sys.stderr)
        return 2

    args.out.mkdir(parents=True, exist_ok=True)
    dest = copy_artifact(args.artifact_dir, args.out)

    has_mkd_bonus = False
    if args.mkd_dir and args.mkd_dir.exists():
        mkd_dest = copy_mkd_bonus(args.mkd_dir, dest)
        has_mkd_bonus = mkd_dest is not None

    qa_summary = None
    if args.qa_summary and args.qa_summary.exists():
        try:
            raw = json.loads(args.qa_summary.read_text(encoding="utf-8"))
            # Normalizza formato: accetta sia qa-summary unificato che coverage-report direct
            if "lexical" in raw:
                # È un coverage-report.json
                qa_summary = {
                    "coverage_rate": f"{raw['lexical']['rate']:.1%}",
                    "schema_verdict": "(separate report)",
                    "iterations": "1 (initial)",
                }
            else:
                qa_summary = raw
        except Exception:
            pass

    handoff = write_handoff_readme(dest, args.artifact_dir.name, has_mkd_bonus, qa_summary)

    result = {
        "packaged_dir": str(dest),
        "handoff": str(handoff),
        "has_mkd_bonus": has_mkd_bonus,
    }

    if args.zip:
        zip_path = args.out / f"{args.artifact_dir.name}.zip"
        make_zip(dest, zip_path)
        result["zip"] = str(zip_path)

    if args.skill:
        skill_path = args.out / f"{args.artifact_dir.name}.skill"
        make_skill_file(dest, skill_path)
        result["skill"] = str(skill_path)

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print(f"✅ Packaged in {dest}")
        if has_mkd_bonus:
            print(f"   🎁 MKD bonus incluso")
        if "zip" in result:
            print(f"   .zip: {result['zip']}")
        if "skill" in result:
            print(f"   .skill: {result['skill']}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
