import os, json
base="/home/user/architettura_completa_7_livelli"

# Load original lists to regenerate correctly
# We'll redefine L3-L7 with correct template

def make_agent_file(path, agents_list):
    # agents_list: list of tuples (name, role, level, team, eco, sub, inputs, outputs)
    content = "import sys; sys.path.insert(0, '/home/user/architettura_completa_7_livelli')\nfrom core import Agent\n\n"
    all_names = []
    for name, role, level, team, eco, sub, inputs, outputs, logic in agents_list:
        # ensure safe quoting
        safe_role = role.replace('"','\\"')
        safe_logic = logic.replace('"','\\"').replace('\n',' ').strip()
        inputs_str = json.dumps(inputs)
        outputs_str = json.dumps(outputs)
        reports_to = [team.replace("Team","Leader")]
        if level==3:
            reports_to = [f"{eco}Controller"]
        elif level==4:
            reports_to = [f"{team.replace('Team','Leader')}"]
        elif level==5:
            reports_to = [f"{team.replace('Team','Leader')}"]
        elif level==6:
            reports_to = [f"{team.replace('Team','Leader')}"]
        elif level==7:
            reports_to = [f"{team.replace('Team','Leader')}", "PlaywrightErrorHandlerAgent"]

        all_names.append(name)
        content += f'''
{name} = Agent(
    name="{name}",
    role="{safe_role}",
    hierarchy_level={level},
    team="{team}",
    ecosystem="{eco}",
    sub_ecosystem="{sub}" if "{sub}" != "None" else None,
    inputs={inputs_str},
    outputs={outputs_str},
    decision_logic="""{safe_logic}""",
    connections={{"reports_to": {json.dumps(reports_to)}, "manages": [], "collaborates_with": ["MemoryManagerLeader","MemoryReaderAgent","CheckpointManagerAgent"]}},
    memory_access={{"read": ["checkpoints","decisions","plans","important_notes","BookOpportunityRegistry"], "write": ["checkpoints","important_notes"]}},
    self_healing_behavior={{"detection_triggers": ["missing output","incoherent output","blocked process","failed validation","empty result from research","no-go without alternative","memory write failure","Playwright failure"], "action": "retry adjusted params rollback ultimo checkpoint valido escalate controller se 3 fallimenti", "max_retries": 3}},
    playwright_usage=None,
    skill_usage=["SelfHealingSkill","MemoryReadWriteSkill"],
    level_name="L{level}"
)
'''
    content += f"\nALL_L{agents_list[0][2]} = [" + ",".join(all_names) + "]\nprint(f\"ALL_L{agents_list[0][2]} VALIDATED: {{len(ALL_L{agents_list[0][2]})}} agents\")\n"
    with open(path,"w") as f:
        f.write(content)

# L3 leaders - simplified 26 teams from previous teams_defs
L3_data = [
    ("AmazonResearchLeader","Leader AmazonKeywordResearchTeam gestisce keyword generation search extraction validation BookNicheDecisionSkill",3,"AmazonKeywordResearchTeam","ResearchEcosystem","PlaywrightOps",["cycle_signal","handoff_package","memory_hierarchies","important_notes"],["team_status","internal_flow_trigger","handoff_ready_package","checkpoint_creation"],"Leader AmazonKeywordResearchTeam trigger KeywordGenerator -> Search via NavigatorMicroAgent -> Extractor via CaptureMicroAgent -> Validator -> decision -> loop if empty retry adjusted keywords"),
    ("ReviewResearchLeader","Leader ReviewAnalysisResearchTeam gestisce review site discovery extraction normalization validation",3,"ReviewAnalysisResearchTeam","ResearchEcosystem","ReviewSub",["book_opportunities","seed_review_sites"],["review_analysis_data","normalized_scores"],"Leader ReviewResearchTeam trigger SiteFinder -> DataExtractor -> Normalizer -> Validator -> ReviewResearchLeader decision link to book opportunities"),
    ("DataPersistenceLeader","Leader DataPersistenceTeam garantisce salvataggio via Playwright formatting validation checkpoint CP1",3,"DataPersistenceTeam","ResearchEcosystem","PersistenceSub",["book_opportunities","review_data","raw_data"],["save_confirmations","research_complete_signal","structured_output"],"Leader DataPersistenceTeam collect book review data -> Formatter formats structured_output ready qualification -> PlaywrightSaveAgent saves via save_results -> Validator validates -> Leader creates checkpoint CP1"),
    ("KeywordExpansionLeader","Leader KeywordExpansionTeam espansione keyword quando empty result LearningLog",3,"KeywordExpansionTeam","ResearchEcosystem","ExpansionSub",["empty_result_trigger","important_notes","LearningLog"],["keyword_variations","new_keyword_list"],"Leader KeywordExpansionTeam empty -> VariationGenerator -> SemanticExpander -> LongTail -> new keyword list -> AmazonSearchAgent retry"),
    ("SearchOptimizationLeader","Leader SearchOptimizationTeam ottimizza strategie search Amazon riduce blocchi Playwright",3,"SearchOptimizationTeam","ResearchEcosystem","OptimizationSub",["Playwright_failure_logs","AnomalyLog"],["optimized_strategy","rotation_plan"],"Leader SearchOptimizationTeam analyze failures -> StrategyOptimizer adjust -> RotationManager rotate user_agent timeout alternative selector"),
    ("QualificationLeader","Leader QualificationAnalysisTeam gestisce 8 analyst valuta 5 criteri reproducibility absurdity speed market plan validity",3,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["research_handoff_package","BookOpportunityRegistry"],["evaluation_scores","risk_flags","preliminary_decision"],"Orchestrate flow ReproducibilityAnalyst -> AbsurdityDetector -> ProductionSpeedAnalyst -> MarketAlignmentAnalyst -> PlanQualityAuditor -> QualificationLeader preliminary GO NO-GO"),
    ("QualificationDecisionLeader","Leader QualificationDecisionTeam aggrega decisioni gestisce rischi scrive report finale GO NO-GO",3,"QualificationDecisionTeam","QualificationEcosystem","DecisionSub",["analyst_outputs","risk_flags"],["final_qualification_report","GO_NO_GO_decision"],"Trigger DecisionAggregatorAgent QualificationDecisionSkill weighted reproducibility 30% speed 25% absurdity 20% market 25% threshold 70 GO IF NO-GO log reason archive IF GO handoff package Planning"),
    ("StructurePlanningLeader","Leader StructurePlanningTeam gestisce video_structure REQUIRED preservato verbatim chapters details coherence CONTROL POINT CRITICO",3,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["qualification_GO_package","risk_flags"],["second_level_plan","validation_status"],"CRITICAL Trigger VideoStructureArchitectAgent first must output video_structure REQUIRED as per original requirement do not remove reinterpret preserve verbatim THEN ChapterDesigner THEN DetailFiller THEN PlanCoherenceValidator IF video_structure missing critical self-healing rollback CP2 IF valid send ProductionReadinessLeader"),
    ("ProductionReadinessLeader","Leader ProductionReadinessTeam verifica prerequisiti stima risorse emette start signal",3,"ProductionReadinessTeam","PlanningEcosystem","ReadinessSub",["second_level_plan_draft"],["readiness_confirmation","production_start_signal"],"Trigger ReadinessChecker verifies prerequisites IF ready THEN ResourceEstimator estimates IF sustainable THEN ProductionStartSignalAgent emits signal TRUE timestamp creates CP3 ELSE escalate"),
    ("ContentPlanningLeader","Leader ContentPlanningTeam pianificazione contenuti dettagliata produzione sostenibile",3,"ContentPlanningTeam","PlanningEcosystem","ContentSub",["second_level_plan_draft","chapters"],["details_enriched","content_flow"],"DetailArchitect enriches production_constraints style_notes business_alignment graphic_needs sustainability_check FlowDesigner designs flow AllocationPlanner plans resources"),
    ("BookWritingLeader","Leader BookWritingTeam gestisce chapter writers paralleli consistenza stile qualita",3,"BookWritingTeam","ProductionEcosystem","WritingSub",["second_level_plan","production_start_signal","memory_context"],["complete_manuscript_draft","writing_log"],"Trigger ChapterWriterAgents per chapter parallel where possible THEN ConsistencyChecker cross-chapter THEN StyleEnforcer uniform style THEN ContentQualityReviewer final review IF all pass approve manuscript IF fail retry chapter with memory read"),
    ("ProductionQualityLeader","Leader ProductionQualityTeam valida completezza compliance approvazione finale",3,"ProductionQualityTeam","ProductionEcosystem","QualitySub",["manuscript_draft"],["validated_manuscript","final_approval"],"Trigger ManuscriptValidator validates completeness THEN PlanComplianceChecker compliance THEN FinalApprovalAgent final approval IF any fails rollback last chapter checkpoint CP4"),
    ("EditingLeader","Leader EditingTeam editing finale uniformita correzione",3,"EditingTeam","ProductionEcosystem","EditingSub",["validated_manuscript"],["edited_manuscript","editing_log"],"Editing flow Coordinator -> Proofreader -> CrossReferenceChecker -> FinalApproval"),
    ("GraphicDesignLeader","Leader GraphicDesignTeam creazione prompt grafiche generazione quality review revision loop",3,"GraphicDesignTeam","VisualEcosystem","GraphicSub",["manuscript","chapter_list","details"],["approved_graphics"],"Flow PromptCreator creates -> Generator generates via VisualPlaywrightSaveAgent -> QualityReviewer reviews -> IF failed RevisionAgent revises back QualityReviewer IF passed approved and saved"),
    ("CoverDesignLeader","Leader CoverDesignTeam cover concept prompt generazione review critica non skippabile",3,"CoverDesignTeam","VisualEcosystem","CoverSub",["manuscript","market_data","graphic_style"],["final_approved_cover"],"Trigger CoverConceptAgent concept content+market -> PromptCreator prompt -> Generator generates -> QualityReviewer reviews IF failed RevisionAgent revises loop critical cannot skip must escalate if fails"),
    ("VisualPlaywrightLeader","Leader VisualPlaywrightOperationsTeam navigazione Playwright salvataggio visual tasks",3,"VisualPlaywrightOperationsTeam","VisualEcosystem","PlaywrightSub",["visual_assets","save_requests"],["save_confirmations"],"Trigger VisualPlaywrightNavigatorAgent navigation IF needed THEN VisualPlaywrightSaveAgent saves via visual_save validation"),
    ("VisualQualityLeader","Leader VisualQualityTeam qualita visual finale approva grafiche cover",3,"VisualQualityTeam","VisualEcosystem","VisualQualitySub",["all_graphics","cover","prompts"],["visual_quality_approval","CP_FINAL"],"Quality final Auditor audits quality all visual vs manuscript plan market fit THEN FinalVisualApproval approval VisualQualityLeader creates CP5 CP_FINAL"),
    ("MemoryManagerLeader","Leader MemoryManagementTeam gestisce memoria attiva read write checkpoint decision plan hierarchy notes SISTEMA ATTIVO NON PASSIVO",3,"MemoryManagementTeam","MemoryEcosystem","CoreMemorySub",["read_requests","write_requests","checkpoint_triggers","validation_triggers"],["read_responses","write_confirmations","validation_reports"],"Route write requests MemoryWriterAgent after validation by MemoryValidatorAgent Route reads MemoryReaderAgent context timestamp Checkpoint creation via CheckpointManagerAgent auto phase transitions Decision logging via DecisionLoggerAgent"),
    ("CheckpointSubLeader","Leader CheckpointSubEcosystem gestione checkpoint creation storage restoration",3,"CheckpointSubEcosystem","MemoryEcosystem","CheckpointSub",["checkpoint_creation_triggers","rollback_requests","state_snapshots"],["checkpoint_created_confirmation","restored_checkpoint"],"Checkpoint flow Creator creates parent ID valid flag Validator validates Restorer restores rollback Pruner pruning old preserving traceability Micro atomic create restore Core self-healing"),
    ("DecisionLogSubLeader","Leader DecisionLogSubEcosystem logging decisioni immutable traceability",3,"DecisionLogSubEcosystem","MemoryEcosystem","DecisionSub",["decision_events","reasoning_chains"],["decision_log_confirmation","decision_id","traceability"],"Decision log flow Writer logs decision_id phase team agent type value reasoning timestamp related_data immutable Reader retrieves traceability TraceabilityAgent verifies reasoning chain Micro atomic logging"),
    ("DetectionLeader","Leader DetectionTeam monitora output completeness coherence detect errors anomalies stalled frozen",3,"DetectionTeam","SelfHealingEcosystem","DetectionSub",["phase_outputs_all_ecosystems","process_status_feeds"],["anomaly_reports"],"All detection agents parallel OutputMonitor checks phase outputs vs expected schemas books_found non empty plan 5 criteria second_level_plan video_structure complete_book graphics+cover ErrorDetector scans logs errors AnomalyDetector unusual patterns all NO-GO video_structure missing cover missing memory gap StallDetector frozen no heartbeat PlaywrightFailureDetector Playwright timeout MemoryFailureDetector aggregation anomaly report severity location context"),
    ("DiagnosisLeader","Leader DiagnosisTeam root cause analysis impact assessment recovery planning",3,"DiagnosisTeam","SelfHealingEcosystem","DiagnosisSub",["anomaly_reports"],["diagnosis_reports_with_recovery_plan"],"RootCauseAnalyst root cause categorization ImpactAssessor impact affected phases data loss risk checkpoint availability RecoveryPlanner recovery plan choosing action retry rollback escalate skip_and_log requalify mapping error_type action per SelfHealingEngine"),
    ("RecoveryLeader","Leader RecoveryTeam retry rollback alternative path validation real recovery",3,"RecoveryTeam","SelfHealingEcosystem","RecoverySub",["recovery_plans"],["recovery_confirmations_or_escalations"],"RetryExecutor retries adjusted params IF fails RollbackExecutor rolls back checkpoint via CheckpointManagerAgent IF fails AlternativePath finds executes alternative path different keyword strategy skip non-critical THEN RecoveryValidator validates without data loss IF fails after max 3 EscalationManager escalates controller Supreme"),
    ("FeedbackCollectionLeader","Leader FeedbackCollectionTeam outcome collection metrics pattern detection real improvement",3,"FeedbackCollectionTeam","AutoImprovementEcosystem","FeedbackSub",["cycle_completion_signals","phase_outcomes","AnomalyLog","PerformanceHistory"],["structured_feedback_data","metrics","patterns"],"OutcomeCollector collects outcomes GO NO-GO rates production speed internal time self-healing frequency plan validity scores memory retrieval patterns book performance signals Amazon+review sites PerformanceMetrics calculates metrics per 6 feedback signals PatternDetector patterns positive negative"),
    ("ImprovementPlanningLeader","Leader ImprovementPlanningTeam analizza feedback rank priorities scrive improvement plans",3,"ImprovementPlanningTeam","AutoImprovementEcosystem","PlanningSub",["feedback_data","metrics","patterns"],["prioritized_improvement_plans"],"ImprovementAnalyst analyzes feedback identifies opportunities 5 targets future research quality future qualification decisions future plan accuracy production flow speed risk sensitivity PriorityRanker ranks impact feasibility aligned business goal quantity-performance OpportunityIdentifier positive patterns PlanWriter writes prioritized plan"),
    ("ImprovementExecutionLeader","Leader ImprovementExecutionTeam adjust parameters update thresholds optimize workflows execution reale",3,"ImprovementExecutionTeam","AutoImprovementEcosystem","ExecutionSub",["improvement_plans"],["updated_parameters","workflow_optimizations","LearningLog"],"ParameterAdjuster adjusts workflow params keyword strategies batch size retry limits ThresholdUpdater updates decision thresholds GO threshold 70 based learning WorkflowOptimizer optimizes flow sequences based performance data improve handoff validation reduce self-healing triggers fixing root causes LearningLogger logs LearningLog important_notes per generate_improvement_signal schema"),
]

make_agent_file(f"{base}/L3/leaders_fixed.py", L3_data)

# L4 senior 40 agents
L4_data = [
    ("ReproducibilityAnalystAgent","Senior valuta reproducibilita efficiente senza risorse inaccessibili",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["book_opportunity_data","review_analysis"],["reproducibility_score","evidence","risk_flag"],"Senior valuta se libro contiene elementi requiring inaccessible resources OR unrealistic production steps THEN score LOW flag absurd ELSE HIGH Evidence link data Amazon review sites Threshold can be reproduced efficiently Decision authority tactical"),
    ("AbsurdityDetectorAgent","Rileva elementi assurdi irrealistici nonsensical gate non assurdi",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["book_data","chapter_hints"],["absurdity_flag","absurdity_evidence","absurdity_score"],"Scan book opportunity absurd elements impossible claims unrealistic promises nonsensical structure IF absurd found THEN flag TRUE evidence fail business alignment gate non assurdi"),
    ("ProductionSpeedAnalystAgent","Stima tempo produzione flag too slow vs modello quantita sostenibile",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["book_complexity","chapter_count","graphic_requirements"],["speed_estimate","too_slow_flag","sustainability_score"],"IF estimated production time > sustainability threshold quantity model THEN flag too_slow TRUE propose mitigation NO-GO Estimate based chapters details graphics Evidence required Tactical decision authority"),
    ("MarketAlignmentAnalystAgent","Valuta allineamento goal quantity-performance performanti riproducibili sostenibili",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["performance_signals_amazon","review_analysis_data","reproducibility_score"],["market_alignment_score","business_fit_evidence"],"Score alignment with goal guadagnare quantita libri performanti Check performante signals Amazon keyword search + review analysis sites riproducibile sostenibile non assurdo non lento Weighted contribution final GO decision"),
    ("PlanQualityAuditorAgent","Valuta qualita qualification plan itself validita piano",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["all_analyst_outputs","qualification_plan_draft"],["plan_validity_score","plan_coherence_flag","audit_report"],"Audit qualification plan check all 5 criteria evaluated explicitly motivation present traceability risk flags prioritized IF plan invalid THEN trigger requalify flow anomaly flag request rollback Research checkpoint Decision threshold plan_validity must be TRUE to pass"),
    ("CompetitionAnalystAgent","Analizza competizione livello nicchia da segnali Amazon",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["book_data","amazon_search_results"],["competition_level","competition_evidence"],"Analizza competizione livello nicchia da segnali Amazon search results count competition level scoring"),
    ("SustainabilityAnalystAgent","Analizza sostenibilita produzione lungo termine quantita",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["book_complexity","resource_estimate"],["sustainability_score","long_term_viability"],"Analizza sostenibilita produzione lungo termine quantita modello quantità libri performanti"),
    ("BusinessFitAnalystAgent","Valuta business fit guadagno tramite quantita libri performanti",4,"QualificationAnalysisTeam","QualificationEcosystem","AnalysisSub",["market_signals","reproducibility","speed"],["business_fit_score","business_evidence"],"Valuta business fit guadagno tramite quantita libri performanti allineamento obiettivo"),
    ("DecisionAggregatorAgent","Aggrega output analyst decisione unificata weighted scoring",4,"QualificationDecisionTeam","QualificationEcosystem","DecisionSub",["reproducibility_score","absurdity_flag","speed_estimate","market_alignment","plan_validity"],["aggregated_score","preliminary_GO_NO_GO","reasoning_chain"],"Apply weighted scoring reproducibility 30% speed 25% absurdity 20% market fit 25% threshold >=70 GO <70 NO-GO IF absurdity TRUE too_slow TRUE auto NO-GO regardless score Generate reasoning chain traceable Tactical authority but final decision QualificationDecisionLeader"),
    ("RiskFlagManagerAgent","Gestisce prioritizza risk flags da tutti analyst",4,"QualificationDecisionTeam","QualificationEcosystem","DecisionSub",["risk_flags_all_analysts"],["prioritized_risks","risk_mitigation_suggestions"],"Collect all risk flags prioritize severity critical high medium low deduplicate suggest mitigations where possible write RiskRegistry IF critical risks >0 flag NO-GO"),
    ("VideoStructureArchitectAgent","CRITICAL REQUIRED Progetta video_structure preservato verbatim non reinterpretare CONTROL POINT CP-VIDEO-01",4,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["qualification_GO_package","original_requirement_video_structure","risk_flags"],["video_structure_field"],"CRITICAL Must preserve video_structure REQUIRED as per original requirement exactly do not reinterpret do not ignore Create explicit control point original_requirement preserved + validation_required flag If ambiguity detected handle_ambiguity preserve_and_encapsulate create validation checkpoint do not fill with assumptions Output must be explicit non-empty traceable to original requirement"),
    ("ChapterDesignerAgent","Definisce capitoli descrizioni ordine scopo effort estimate fast vs slow",4,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["video_structure","book_opportunity"],["chapters_list_with_descriptions"],"Design chapters list title description order purpose estimated_effort fast sustainable vs slow Must be coherent with video_structure and business goal quantity Check no chapter introduces too_slow or absurd elements"),
    ("DetailFillerAgent","Aggiunge ogni dettaglio rilevante produzione sostenibilita",4,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["chapters","video_structure","risk_flags"],["details_every_relevant"],"Add every relevant production detail production constraints style notes business alignment notes graphic needs resource estimates sustainability checks Details must be concrete not vague operational clarity priority"),
    ("PlanCoherenceValidatorAgent","Valida intero second-level plan coerente completo",4,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["second_level_plan_draft"],["coherence_validation_result","completeness_check"],"Validate video_structure present verbatim chapters non-empty details concrete production_start_signal logic no absurd slow elements introduced alignment qualification GO IF fail trigger requalify to send back to Qualification with anomaly flag"),
    ("VideoStructureValidatorAgent","Valida video_structure presente verbatim non vuoto non reinterpretato critical validation",4,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["video_structure_field"],["video_structure_validation","presence_flag","verbatim_flag"],"Valida video_structure REQUIRED campo esistente non vuoto non reinterpretato non ignorato per absolute rule CRITICAL CONTROL POINT se missing critical failure self-healing"),
    ("OutlineOptimizerAgent","Ottimizza outline capitoli flusso sostenibilita",4,"StructurePlanningTeam","PlanningEcosystem","StructureSub",["chapters_draft","details"],["optimized_outline"],"Ottimizza outline capitoli per flusso e sostenibilita quantita"),
    ("ContentFlowDesignerAgent","Progetta flusso contenuti tra capitoli",4,"ContentPlanningTeam","PlanningEcosystem","ContentSub",["chapters","details"],["content_flow_design"],"Progetta flusso contenuti tra capitoli per coerenza"),
    ("ConsistencyCheckerAgent","Controlla consistenza cross-chapters durante produzione",4,"BookWritingTeam","ProductionEcosystem","WritingSub",["chapters_written","second_level_plan","production_log"],["consistency_report","inconsistencies_flagged"],"Check cross-chapter coherence style facts structure following plan no deviation introducing absurd elements IF inconsistency found flag trigger retry specific chapter with memory read previous decisions"),
    ("StyleEnforcerAgent","Garantisce stile scrittura uniforme",4,"BookWritingTeam","ProductionEcosystem","WritingSub",["manuscript_draft","style_notes"],["style_normalized_manuscript","style_log"],"Normalize writing style per style notes second_level_plan details Ensure uniform tone terminology formatting Check no generic vague advice concrete precise"),
    ("ContentQualityReviewerAgent","Revisiona qualita contenuto prima finalizzazione",4,"BookWritingTeam","ProductionEcosystem","WritingSub",["normalized_manuscript"],["quality_review_result","final_review_score"],"Review content against qualification plan second_level_plan business alignment Check operational clarity flow feasibility selection quality production sustainability IF quality fail trigger revision loop"),
    ("ManuscriptValidatorAgent","Valida completezza manoscritto",4,"ProductionQualityTeam","ProductionEcosystem","QualitySub",["final_manuscript_draft"],["completeness_validation","manuscript_valid_flag"],"Validate manuscript complete not partial all chapters present per plan no missing sections Check against chapters list"),
    ("PlanComplianceCheckerAgent","Verifica manoscritto segue second-level plan",4,"ProductionQualityTeam","ProductionEcosystem","QualitySub",["manuscript","second_level_plan"],["compliance_report","deviations_list"],"Check compliance chapters respected video_structure considered details followed no introduction flagged absurd elements IF deviations log important_notes trigger consistency check"),
    ("RootCauseAnalystAgent","Analizza anomalie root cause real self-healing diagnosis",4,"DiagnosisTeam","SelfHealingEcosystem","DiagnosisSub",["anomaly_report","phase_state","checkpoint_before"],["root_cause_diagnosis","cause_category"],"Analyze anomaly check if missing output due Playwright failure incoherent due data extraction blocked due stall validation fail due video_structure missing etc Categorize cause suggest recovery strategy Tactical authority"),
    ("ImpactAssessorAgent","Valuta impatto anomalia su workflow",4,"DiagnosisTeam","SelfHealingEcosystem","DiagnosisSub",["root_cause","workflow_state"],["impact_assessment","affected_phases"],"Assess impact which phases affected data loss risk checkpoint availability rollback possible alternative path exists Severity scoring"),
    ("RecoveryPlannerAgent","Crea recovery plan basato su diagnosis retry rollback escalate skip requalify",4,"DiagnosisTeam","SelfHealingEcosystem","DiagnosisSub",["root_cause","impact_assessment"],["recovery_plan_with_steps"],"Create recovery plan choose action retry rollback escalate skip_and_log requalify based error_type mapping Define adjusted params retry checkpoint ID rollback anomaly flag requalify Must include memory update flow continuation guarantee"),
    ("OutputMonitorAgent","Monitora output phase completeness coherence Detection Team",4,"DetectionTeam","SelfHealingEcosystem","DetectionSub",["phase_outputs_feed","expected_output_schemas"],["output_monitor_report","completeness_flag"],"Monitor each phase output against expected schema books_found non empty qualification plan 5 criteria second_level_plan video_structure REQUIRED complete_book non empty graphics+cover present IF missing incoherent trigger anomaly"),
    ("AnomalyDetectorAgent","Rileva anomalie pattern insoliti stati inattesi",4,"DetectionTeam","SelfHealingEcosystem","DetectionSub",["process_metrics","memory_validation_reports"],["anomaly_detected_flag","anomaly_context"],"Detect anomalies unexpected state unusual pattern e.g. all NO-GO without alternative video_structure missing cover missing memory gap Cross-reference important_notes patterns"),
    ("ImprovementAnalystAgent","Analizza feedback identifica opportunita miglioramento 5 target",4,"ImprovementPlanningTeam","AutoImprovementEcosystem","PlanningSub",["feedback_data","performance_history"],["improvement_opportunities","analysis_report"],"Analyze qualification outcomes GO rate production speed metrics self-healing frequency plan validity scores memory retrieval patterns book performance signals from Amazon+review sites Identify improvement for future research quality qualification decisions plan accuracy speed risk sensitivity"),
    ("PriorityRankerAgent","Rank improvements by impact feasibility",4,"ImprovementPlanningTeam","AutoImprovementEcosystem","PlanningSub",["improvement_opportunities"],["ranked_improvements","priority_scores"],"Rank by impact on business goal quantity+performance and feasibility Prioritize operational_clarity first"),
    ("CoverConceptAgent","Crea cover concept basato contenuto e market data performance signals",4,"CoverDesignTeam","VisualEcosystem","CoverSub",["manuscript","market_data","performance_signals"],["cover_concept","concept_rationale"],"Create cover concept aligned with performant niche signals from Amazon and review analysis sites coherent with book content not absurd sustainable produce Decision authority tactical"),
    ("CoverMarketFitAnalystAgent","Analizza market fit cover concept",4,"CoverDesignTeam","VisualEcosystem","CoverSub",["cover_concept","market_data"],["market_fit_score","market_evidence"],"Analizza market fit cover concept basato su performance signals"),
    ("VisualQualityAuditorAgent","Audita qualita visual finale",4,"VisualQualityTeam","VisualEcosystem","VisualQualitySub",["all_graphics","cover","graphics_prompts"],["quality_audit_report","audit_score"],"Audita qualita visual finale vs manoscritto plan market fit"),
    ("VisualConsistencyCheckerAgent","Verifica consistenza visual tra grafiche e cover",4,"GraphicDesignTeam","VisualEcosystem","GraphicSub",["graphics","cover","prompts"],["consistency_report","consistency_flag"],"Verifica consistenza visual tra grafiche e cover stile uniforme"),
    ("FailurePatternAnalyzerAgent","Analizza pattern fallimenti ricorrenti per prevenzione",4,"DiagnosisTeam","SelfHealingEcosystem","DiagnosisSub",["AnomalyLog","DiagnosisLog","RecoveryLog"],["failure_patterns","prevention_suggestions"],"Analizza pattern fallimenti ricorrenti DiagnosisLog RecoveryLog per prevenire future"),
    ("OpportunityIdentifierAgent","Identifica opportunita miglioramento da pattern positivi",4,"ImprovementPlanningTeam","AutoImprovementEcosystem","PlanningSub",["PatternRegistry","PerformanceHistory"],["positive_patterns","opportunities"],"Identifica opportunita miglioramento da pattern positivi recurring success"),
]

make_agent_file(f"{base}/L4/senior_fixed.py", L4_data)

# For brevity, L5, L6, L7 also fixed similarly but we can copy same pattern quickly with smaller lists

L5_sample = [
    ("KeywordGeneratorAgent","Genera variazioni keyword Amazon search seed important_notes",5,"AmazonKeywordResearchTeam","ResearchEcosystem","PlaywrightOps",["seed_keywords","important_notes"],["keyword_variations"],"Genera variazioni keyword Amazon search basata su seed historical success patterns FeedbackRegistry"),
    ("AmazonSearchAgent","Esegue ricerche Amazon via Playwright tool real navigation",5,"AmazonKeywordResearchTeam","ResearchEcosystem","PlaywrightOps",["keyword_variations"],["search_results_raw"],"Per ogni keyword chiama playwright_tool.navigate_amazon_keyword_search via NavigatorMicroAgent atomic"),
    ("AmazonDataExtractorAgent","Estrae dati libri titoli autori via Playwright capture",5,"AmazonKeywordResearchTeam","ResearchEcosystem","PlaywrightOps",["search_results_raw"],["extracted_book_metadata"],"Use PlaywrightDataCaptureMicroAgent extract titles authors ratings prices categories save via PlaywrightSaveAgent"),
    ("ReviewSiteFinderAgent","Trova siti analizzano Amazon reviews via Playwright",5,"ReviewAnalysisResearchTeam","ResearchEcosystem","ReviewSub",["search_seed_review_sites"],["found_review_sites_list"],"Navigate via Playwright find sites analyze Amazon reviews Discover via Playwright operations collect URLs notes"),
    ("ReviewDataExtractorAgent","Estrae review analysis data da siti via Playwright",5,"ReviewAnalysisResearchTeam","ResearchEcosystem","ReviewSub",["found_review_sites_list"],["review_analysis_raw_data"],"Extract review analysis data from found sites using PlaywrightDataCaptureMicroAgent Save via PlaywrightSaveAgent"),
    ("PlaywrightSaveAgent","Gestisce save Playwright research visual",5,"DataPersistenceTeam","ResearchEcosystem","PersistenceSub",["data_to_save","destination_ref"],["save_confirmation"],"Call playwright_tool.save_results save results sources URLs notes useful material Validate via SaveValidatorAgent Retry failure"),
    ("ChapterWriterAgent","Scrive capitoli singoli multiple instances parallele legge memoria continuity",5,"BookWritingTeam","ProductionEcosystem","WritingSub",["chapter_definition","second_level_plan","memory_context"],["chapter_written_content"],"Write chapter per definition maintain consistency all previous decisions constraints via MemoryReaderAgent read continuity Log decisions"),
    ("GraphicPromptCreatorAgent","Crea prompt dettagliati grafiche",5,"GraphicDesignTeam","VisualEcosystem","GraphicSub",["chapter_content","graphic_requirements"],["graphic_prompts_detailed"],"Create prompts graphics generation detailed coherent chapter content not absurd sustainable"),
    ("GraphicGeneratorAgent","Genera grafiche using prompts salva via VisualPlaywrightSaveAgent",5,"GraphicDesignTeam","VisualEcosystem","GraphicSub",["graphic_prompts"],["generated_graphics_raw"],"Generate graphics using prompts In architecture generation abstract but save via VisualPlaywrightSaveAgent visual_save"),
    ("MemoryWriterAgent","Gestisce scritture strutturate memoria - sistema attivo",5,"MemoryManagementTeam","MemoryEcosystem","CoreMemorySub",["write_requests","data_to_write","category"],["write_confirmation"],"Write structured data memory per category checkpoints decisions plans hierarchies important_notes Validate via MemoryValidatorAgent before storage Create checkpoint via CheckpointManagerAgent"),
    ("MemoryReaderAgent","Gestisce letture memoria - sistema attivo",5,"MemoryManagementTeam","MemoryEcosystem","CoreMemorySub",["read_requests","category","requester_id"],["read_response_with_timestamp"],"Retrieve relevant memory on request any team serve context timestamp Read categories Integration protocol every ecosystem memory connector"),
    ("RetryExecutorAgent","Esegue retry adjusted params real recovery",5,"RecoveryTeam","SelfHealingEcosystem","RecoverySub",["recovery_plan_retry","failed_operation_ref"],["retry_execution_result"],"Execute retry operation adjusted params increased timeout user_agent rotate alternative selector new keywords memory reread Log RecoveryLog Max 3 retries"),
]

make_agent_file(f"{base}/L5/operational_fixed.py", L5_sample)

L6_sample = [
    ("DataFormatterAgent","Formatta dati per storage via Playwright save",6,"DataPersistenceTeam","ResearchEcosystem","PersistenceSub",["raw_book_data"],["formatted_structured_output"],"Format data into structured_output ready to pass qualification phase list book opportunities metadata review sites analysis data raw_data refs Ensure output directly usable next phase"),
    ("SaveValidatorAgent","Conferma salvataggi Playwright successo",6,"DataPersistenceTeam","ResearchEcosystem","PersistenceSub",["save_operations"],["save_validation_result"],"Confirm saves via Playwright were successful check URL saved source logged raw_data accessible IF fail trigger self-healing retry"),
    ("MemoryValidatorAgent","Valida consistenza memoria corruzione gaps active",6,"MemoryManagementTeam","MemoryEcosystem","CoreMemorySub",["memory_content_all_categories","checkpoint_refs"],["validation_report","corruption_gap_flags"],"Validate memory consistency checkpoints align decisions plans hierarchies important_notes no gap corruption Flag corruption gaps trigger SelfHealing if needed trigger Memory Maintenance Flow periodic"),
    ("CheckpointManagerAgent","Gestisce checkpoint creation storage restoration core self-healing",6,"MemoryManagementTeam","MemoryEcosystem","CoreMemorySub",["checkpoint_creation_triggers","rollback_requests","state_snapshots"],["checkpoint_created_confirmation","restored_checkpoint"],"Manage checkpoint creation storage restoration creation triggers end each phase before major decision before handoff on self-healing activation per chapter production Storage parent ID valid flag Restoration via RollbackExecutorAgent request Core self-healing"),
    ("DecisionLoggerAgent","Logga decisioni full context reasoning immutable",6,"MemoryManagementTeam","MemoryEcosystem","CoreMemorySub",["decision_events","reasoning_chains"],["decision_log_confirmation"],"Log decisions decision_id phase team agent type value reasoning timestamp related_data Immutable append-only traceability"),
    ("RollbackExecutorAgent","Esegue rollback checkpoint precedenti real recovery",6,"RecoveryTeam","SelfHealingEcosystem","RecoverySub",["rollback_requests","checkpoint_id"],["rollback_execution_result","restored_state"],"Execute rollback to last valid checkpoint via CheckpointManagerAgent restore Log RecoveryLog Ensure memory_updated TRUE flow_continued TRUE checkpoint_restored TRUE per handle_failure schema"),
]

make_agent_file(f"{base}/L6/support_fixed.py", L6_sample)

L7_sample = [
    ("PlaywrightNavigatorMicroAgent","Micro singola navigazione pagina via Playwright tool atomic",7,"PlaywrightOperationsSubEcosystem","ResearchEcosystem","NavigationSub",["navigation_request","url","timeout_params"],["navigation_result"],"Atomic task single Playwright navigation Execute playwright_tool.navigate_amazon_keyword_search or navigate_review_site Report success fail Spawned AmazonSearchAgent auto-terminated"),
    ("PlaywrightDataCaptureMicroAgent","Micro cattura dati specifici pagine via Playwright",7,"PlaywrightOperationsSubEcosystem","ResearchEcosystem","ExtractionSub",["extraction_request","selectors","url"],["captured_data"],"Atomic task single data extraction using selectors Execute playwright_tool.extract_data Spawned DataExtractor agents"),
    ("PlaywrightErrorHandlerAgent","Gestisce errori Playwright-specific timeouts blocked CAPTCHAs retry alternative core self-healing Playwright",7,"PlaywrightOperationsSubEcosystem","ResearchEcosystem","NavigationSub",["playwright_error","failed_operation","retry_count"],["error_handling_strategy"],"Handle Playwright errors timeouts blocked pages connection failures CAPTCHAs Strategy retry adjusted params timeout++ user_agent rotate alternative selector Use playwright_tool.handle_error Max 3 retries then escalate Logs AnomalyLog"),
    ("VisualPlaywrightNavigatorAgent","Gestisce navigazione Playwright visual tasks",7,"VisualPlaywrightOperationsTeam","VisualEcosystem","PlaywrightSub",["visual_navigation_request"],["visual_navigation_result"],"Atomic navigation visual team support tasks save via Playwright support usage"),
    ("ErrorDetectorAgent","Rileva errori eccezioni fallimenti processi",7,"DetectionTeam","SelfHealingEcosystem","DetectionSub",["process_logs","exception_feed"],["error_detected_report"],"Atomic detection scan logs errors exceptions failures Part DetectionTeam"),
    ("StallDetectorAgent","Rileva processi stalled frozen",7,"DetectionTeam","SelfHealingEcosystem","DetectionSub",["process_heartbeat_feed","phase_timeout_thresholds"],["stall_detected_report"],"Detect stalled processes no heartbeat phase timeout exceeded Trigger recovery Spawned continuously"),
    ("AlternativePathAgent","Trova esegue percorsi alternativi quando retry rollback fail",7,"RecoveryTeam","SelfHealingEcosystem","RecoverySub",["failed_recovery_attempts","workflow_state"],["alternative_path_execution"],"Find alternative path different keyword strategy skip_and_log non-critical graphic requalify send item back qualification anomaly flag Execute alternative Real recovery agent"),
]

make_agent_file(f"{base}/L7/micro_fixed.py", L7_sample)

print("Fixed L3-L7 generated")
