import sys; sys.path.insert(0, '/home/user/architettura_completa_7_livelli')
from core import MemoryComponent

MEMORY_COMPONENTS = []

def mem(name, cat, reads, writes, schema, checkpoint, validation, eco, sub=None):
    return MemoryComponent(name=name, category=cat, read_agents=reads, write_agents=writes, data_schema=schema, checkpoint_logic=checkpoint, validation_rules=validation, ecosystem=eco, sub_ecosystem=sub)

# Core 5 categories + expanded 35
# Research
MEMORY_COMPONENTS.append(mem("ResearchCheckpoints","checkpoints",["ResearchEcosystemController","SelfHealingEcosystemController","CheckpointManagerAgent","RollbackExecutorAgent"],["AmazonResearchLeader","DataPersistenceLeader","CheckpointManagerAgent","MemoryWriterAgent"],{"phase":"Research","state_snapshot":"keywords books review raw refs","trigger":"end batch before decision before handoff on healing"},{"creation_triggers":["end each batch","before decision","before handoff","on healing"],"storage":"CheckpointManager parent ID","restoration":"RollbackExecutor"},{"must have timestamp","books_found_count","trigger_event","readable by SelfHealing"},"ResearchEcosystem","ResearchSub"))
MEMORY_COMPONENTS.append(mem("ResearchDecisions","decisions",["ResearchEcosystemController","QualificationEcosystemController"],["AmazonResearchLeader","MemoryWriterAgent"],{"decision_id":"uuid","type":"keyword_selection","value":"string","reasoning":"why"},{"creation":"every decision point","storage":"DecisionLogger append-only"},{"reasoning required","timestamp"},"ResearchEcosystem"))
MEMORY_COMPONENTS.append(mem("BookOpportunityRegistry","important_notes",["QualificationLeader","CoverConceptAgent","MemoryReaderAgent"],["AmazonDataExtractorAgent","DataFormatterAgent","PlaywrightSaveAgent"],{"book_id":"uuid","title":"string","amazon_url":"url","keyword_match":"string","metadata":"dict","observed_signals":"performance Amazon+review","raw_data_ref":"Playwright ref"},{"creation":"after extraction","validation":"AmazonResultsValidator"},{"amazon_url valid","title not empty","raw_data_ref Playwright required"},"ResearchEcosystem"))
MEMORY_COMPONENTS.append(mem("ReviewDataRegistry","important_notes",["QualificationLeader"],["ReviewDataExtractorAgent"],{"review_data_id":"uuid","site_url":"url review analysis","linked_book_id":"uuid"},{"creation":"after ReviewDataValidator"},{"site_url must be review analysis site"},"ResearchEcosystem"))
MEMORY_COMPONENTS.append(mem("KeywordExpansionLog","important_notes",["AmazonResearchLeader","KeywordExpansionLeader"],["KeywordVariationGeneratorAgent"],{"keyword_original":"string","variations":"list","strategy":"string"},{"creation":"when empty result retry"},{"strategy required"},"ResearchEcosystem","ExpansionSub"))
MEMORY_COMPONENTS.append(mem("SearchOptimizationLog","important_notes",["SearchOptimizationLeader"],["SearchStrategyOptimizerAgent"],{"failure_type":"Playwright failure","adjusted_params":"dict timeout user_agent selector"},{"creation":"on Playwright failure"},{"adjusted_params required"},"ResearchEcosystem","OptimizationSub"))

# Qualification
MEMORY_COMPONENTS.append(mem("QualificationCheckpoints","checkpoints",["QualificationEcosystemController","PlanningEcosystemController"],["QualificationLeader","CheckpointManagerAgent"],{"phase":"Qualification","state_snapshot":"evaluated GO NO-GO counts plan_validity"},{"creation_triggers":["after evaluation","before GO NO-GO","before handoff Planning","on healing"]},["GO NO-GO counts","plan_validity flag"],"QualificationEcosystem"))
MEMORY_COMPONENTS.append(mem("QualificationDecisions","decisions",["PlanningEcosystemController","StructurePlanningLeader"],["DecisionAggregatorAgent","DecisionLoggerAgent"],{"decision_id":"uuid","type":"GO NO-GO","value":"GO NO-GO","reasoning":"full reasoning weighted","scores":"repro speed absurdity market"},{"creation":"every go no-go","storage":"DecisionLogger immutable"},{"reasoning with evidence","decision_value GO or NO-GO","all 5 criteria evaluated","plan_validity required"},"QualificationEcosystem"))
MEMORY_COMPONENTS.append(mem("QualificationPlans","plans",["PlanningEcosystemController"],["QualificationReportWriterAgent","PlanStorageAgent"],{"plan_id":"uuid","criteria_evaluation":"reproducibility absurdity production_speed plan_validity business_alignment"},{"creation":"when plan approved validated","validation":"PlanQualityAuditor"},{"all 5 criteria present","evidence each"},"QualificationEcosystem"))
MEMORY_COMPONENTS.append(mem("RiskRegistry","important_notes",["QualificationDecisionLeader","StructurePlanningLeader"],["AbsurdityDetectorAgent","RiskFlagManagerAgent"],{"risk_id":"uuid","category":"absurdity reproducibility speed market plan_validity","content":"risk description","severity":"critical high medium low"},{"creation":"when risk detected"},{"severity required","category required"},"QualificationEcosystem"))
MEMORY_COMPONENTS.append(mem("BusinessFitScores","important_notes",["PlanningEcosystemController"],["MarketAlignmentAnalystAgent","BusinessFitAnalystAgent"],{"book_id":"uuid","business_fit":"score quantity-performance","evidence":"string"},{"creation":"after market alignment evaluation"},{"evidence required"},"QualificationEcosystem"))

# Planning
MEMORY_COMPONENTS.append(mem("PlanningCheckpoints","checkpoints",["PlanningEcosystemController","ProductionEcosystemController"],["StructurePlanningLeader","ProductionReadinessLeader"],{"phase":"Planning","state_snapshot":"video_structure_present chapters_count details_complete readiness_confirmed"},{"creation_triggers":["after video_structure","after chapters","after details","validation","production_start_signal"]},["video_structure_present flag required"],"PlanningEcosystem"))
MEMORY_COMPONENTS.append(mem("SecondLevelPlans","plans",["ProductionEcosystemController","BookWritingLeader","VisualEcosystemController"],["VideoStructureArchitectAgent","ChapterDesignerAgent","DetailFillerAgent","PlanStorageAgent"],{"plan_id":"uuid","content":"video_structure REQUIRED preserved verbatim + chapters list + details concrete + production_start_signal TRUE"},{"creation":"when plan approved validated StructurePlanningLeader","validation":"PlanCoherenceValidator checks video_structure present verbatim"},{"video_structure REQUIRED must exist non-empty non-reinterpreted","chapters non-empty","details concrete not vague","production_start_signal TRUE required"},"PlanningEcosystem"))
MEMORY_COMPONENTS.append(mem("ProductionStartSignals","decisions",["ProductionEcosystemController","BookWritingLeader"],["ProductionStartSignalAgent","DecisionLoggerAgent"],{"signal_id":"uuid","value":"TRUE","validated_by":"ProductionReadinessLeader","checkpoint_ref":"CP3"},{"creation":"when production authorized marks actual start","checkpoint":"CP3 Planning End Production Start gate"},{"value TRUE explicit","validated_by required","checkpoint_ref CP3 required"},"PlanningEcosystem"))
MEMORY_COMPONENTS.append(mem("VideoStructureControlPoints","important_notes",["StructurePlanningLeader","PlanCoherenceValidatorAgent","SelfHealingEcosystemController"],["VideoStructureArchitectAgent","VideoStructureValidatorAgent"],{"original_requirement":"video structure","preserved_as_is":"bool True","validation_required":"human_or_orchestrator must confirm","ambiguity_handling":"preserve_and_encapsulate create validation checkpoint forbidden fill_with_assumptions"},{"creation":"when video_structure designed - CRITICAL CP-VIDEO-01"},{"original_requirement preserved verbatim required","validation_required flag"},"PlanningEcosystem","StructureSub"))

# Production
MEMORY_COMPONENTS.append(mem("ProductionCheckpoints","checkpoints",["ProductionEcosystemController","VisualEcosystemController"],["ChapterWriterAgent","BookWritingLeader","CheckpointManagerAgent"],{"phase":"Production","state_snapshot":"chapter_completed manuscript_length consistency style"},{"creation_triggers":["after each chapter critical","after consistency","after style","final","on healing"],"restoration":"rollback to last chapter checkpoint"},["chapter_completed required"],"ProductionEcosystem"))
MEMORY_COMPONENTS.append(mem("ProductionLog","important_notes",["VisualEcosystemController","GraphicDesignLeader"],["ChapterWriterAgent","ConsistencyCheckerAgent","ProductionLogWriterAgent"],{"log_id":"uuid","book_id":"uuid","decisions_made":"list chapter decision reasoning","consistency_checks":"list","deviations":"list"},{"creation":"during writing log decisions","checkpoint":"ProductionCheckpoint per chapter"},["decisions_made required","book_id required"],"ProductionEcosystem"))
MEMORY_COMPONENTS.append(mem("CompletedManuscripts","plans",["VisualEcosystemController","GraphicDesignLeader"],["BookWritingLeader","FinalApprovalAgent","PlanStorageAgent"],{"manuscript_id":"uuid","book_id":"uuid","plan_id":"ref SecondLevelPlans","content":"full_book_ref chapters production_log_ref","status":"validated approved final","validation":"completeness plan_compliance style uniform consistency"},{"creation":"when final approval given FinalApprovalAgent","validation":"ManuscriptValidator + PlanComplianceChecker"},["content full_book_ref required","status approved required","plan_id ref required"],"ProductionEcosystem"))
MEMORY_COMPONENTS.append(mem("EditingLog","important_notes",["ProductionQualityLeader"],["EditingCoordinatorAgent","FinalProofreaderAgent"],{"editing_id":"uuid","changes":"list","proofread_status":"bool"},{"creation":"during editing"},["proofread_status required"],"ProductionEcosystem","EditingSub"))

# Visual
MEMORY_COMPONENTS.append(mem("GraphicPrompts","important_notes",["GraphicGeneratorAgent","MemoryReaderAgent"],["GraphicPromptCreatorAgent","CoverPromptCreatorAgent"],{"prompt_id":"uuid","book_id":"uuid","chapter_ref":"string cover","prompt":"detailed prompt graphic generation","purpose":"purpose"},{"creation":"when prompt created per graphic requirement"},{"prompt detailed required","purpose required"},"VisualEcosystem"))
MEMORY_COMPONENTS.append(mem("GeneratedGraphics","important_notes",["GraphicQualityReviewerAgent","VisualPlaywrightLeader"],["GraphicGeneratorAgent","VisualPlaywrightSaveAgent"],{"graphic_id":"uuid","book_id":"uuid","prompt_id":"ref GraphicPrompts","asset_ref":"Playwright visual_save ref","quality_score":"pass fail","review_status":"approved failed revised"},{"creation":"after generation save via Playwright support","validation":"GraphicQualityReviewer","revision_loop":"failed -> RevisionAgent -> QualityReviewer"},["asset_ref via Playwright save required","quality_score required"],"VisualEcosystem"))
MEMORY_COMPONENTS.append(mem("CoverVersions","plans",["VisualEcosystemController"],["CoverConceptAgent","CoverGeneratorAgent","CoverQualityReviewerAgent","VisualPlaywrightSaveAgent"],{"cover_id":"uuid","book_id":"uuid","concept":"concept rationale market signals","prompt":"cover prompt detailed","versions":"list version_id asset_ref quality_score review_status","final_approved":"asset_ref final cover","status":"draft reviewing approved critical_fail_escalated"},{"creation":"from concept to final versions stored","validation":"CoverQualityReviewer critical cannot skip_and_log must escalate if fails final","checkpoint":"CP5 CP_FINAL"},["concept required","final_approved required","status required"],"VisualEcosystem"))
MEMORY_COMPONENTS.append(mem("VisualProductionLog","important_notes",["VisualEcosystemController"],["GraphicDesignLeader","CoverDesignLeader","VisualPlaywrightLeader"],{"log_id":"uuid","book_id":"uuid","graphic_decisions":"list","cover_decisions":"list","playwright_saves":"list save confirmations"},{"creation":"during visual production log decisions"},["book_id required"],"VisualEcosystem"))
MEMORY_COMPONENTS.append(mem("VisualQualityLog","important_notes",["VisualQualityLeader"],["VisualQualityAuditorAgent","FinalVisualApprovalAgent"],{"audit_id":"uuid","quality_score":"overall visual quality","issues":"list"},{"creation":"after visual quality audit"},["quality_score required"],"VisualEcosystem","VisualQualitySub"))

# Memory core active system
MEMORY_COMPONENTS.append(mem("checkpoints","checkpoints",["SelfHealingEcosystemController","All teams on recovery","SupremeOrchestratorAgent","CheckpointManagerAgent","RollbackExecutorAgent"],["All teams via MemoryWriterAgent","CheckpointManagerAgent","MemoryManagerLeader"],{"checkpoint_id":"uuid","phase":"Research Qualification Planning Production Visual SelfHealing AutoImprovement","team":"string","timestamp":"ISO","state_snapshot":"arbitrary state","trigger_event":"end phase before decision before handoff on healing periodic","parent_checkpoint_id":"uuid or None","valid":"bool","created_by":"CheckpointManagerAgent"},{"creation_triggers":["end each phase","before major decision GO NO-GO","before handoff","on healing","per chapter"],"storage":"CheckpointManager versioned parent ref","restoration":"RollbackExecutor + CheckpointManager restore","validation":"MemoryValidator checks alignment decisions plans"},["must have phase team timestamp state_snapshot trigger_event valid","parent_checkpoint_id required chain","readable by SelfHealing"],"MemoryEcosystem","CoreMemorySub"))
MEMORY_COMPONENTS.append(mem("decisions","decisions",["ProductionTeam","VisualTeam","AutoImprovementEcosystemController","All teams"],["QualificationTeam","PlanningTeam","DecisionLoggerAgent","MemoryWriterAgent"],{"decision_id":"uuid","phase":"string","team":"string","agent":"string decision maker","decision_type":"GO NO-GO production_start keyword_selection niche_ranking","decision_value":"string value","reasoning":"full reasoning chain","timestamp":"ISO","related_data":"dict book_id scores risk_flags plan_id"},{"creation":"at every decision point all ecosystems","storage":"append-only DecisionLogger immutable full context","checkpoint":"checkpoint created before major decision"},["decision_type required","decision_value required","reasoning required traceable","timestamp required","agent required"],"MemoryEcosystem"))
MEMORY_COMPONENTS.append(mem("plans","plans",["ProductionTeam","VisualTeam"],["QualificationTeam","PlanningTeam","PlanStorageAgent","MemoryWriterAgent"],{"plan_id":"uuid","plan_type":"qualification second_level_operational manuscript cover improvement","plan_level":"first_level second_level final","content":"dict varying per type","status":"draft approved validated archived","created_by":"agent name","approved_by":"agent name leader","timestamp":"ISO","validity_score":"descriptive score"},{"creation":"when plan approved validated","validation":"PlanQualityAuditor for qualification PlanCoherenceValidator for second-level","storage":"PlanStorage versioned not overwritten","checkpoint":"before after approval"},["plan_type required","content required","status required","created_by approved_by required"],"MemoryEcosystem"))
MEMORY_COMPONENTS.append(mem("hierarchies","hierarchies",["All teams","All agents for routing escalation"],["Orchestrator SupremeOrchestratorAgent via HierarchyManagerAgent","MemoryWriterAgent"],{"agent_id":"uuid","agent_name":"string","hierarchy_level":"int 1-7","team":"string","ecosystem":"string","reports_to":"list","manages":"list","role":"string","timestamp":"ISO"},{"creation":"at workflow initialization and on update orchestrator","validation":"MemoryValidator verifies not corrupted","storage":"HierarchyManagerAgent","update":"only via SupremeOrchestratorAgent"},["agent_name unique required","hierarchy_level 1-7 required","reports_to required array","manages required","exactly 7 levels must exist"],"MemoryEcosystem","CoreMemorySub"))
MEMORY_COMPONENTS.append(mem("important_notes","important_notes",["All teams","AutoImprovementEcosystemController","SelfHealingEcosystemController"],["All teams","SelfHealingEngine","AutoImprovementEngine","ImportantNotesAgent","MemoryWriterAgent"],{"note_id":"uuid","category":"critical_notions risk_flags anomaly_logs keyword_patterns improvement_suggestions validation_uncertainties Playwright_failures","content":"string critical notion","severity":"critical high medium low info","source_agent":"string","source_phase":"string Research etc","timestamp":"ISO","expiry":"ISO or None persistent"},{"creation":"whenever relevant signal detected any agent self-healing auto-improvement","storage":"ImportantNotesAgent deduplication but without loss trace"},["content not empty","category required","source_agent required","timestamp required"],"MemoryEcosystem"))

# Self-Healing
MEMORY_COMPONENTS.append(mem("AnomalyLog","important_notes",["DiagnosisLeader","RecoveryLeader","SelfHealingEcosystemController"],["OutputMonitorAgent","ErrorDetectorAgent","AnomalyDetectorAgent","StallDetectorAgent","DetectionLeader","PlaywrightFailureDetectorAgent","MemoryFailureDetectorAgent"],{"anomaly_id":"uuid","phase":"string where detected","team":"string","agent":"string detecting","error_type":"missing output incoherent output blocked process failed validation empty result from research no-go without alternative memory write failure Playwright failure","severity":"critical high medium low","context":"state snapshot before anomaly","checkpoint_before":"checkpoint ID ref","timestamp":"ISO","status":"detected diagnosed recovering recovered escalated"},{"creation":"on any detection trigger 8 triggers","storage":"MemoryWriter append","checkpoint":"SelfHealingCheckpoint before after"},["error_type must be one of 8 triggers","severity required","phase required","checkpoint_before required"],"SelfHealingEcosystem","DetectionSub"))
MEMORY_COMPONENTS.append(mem("DiagnosisLog","important_notes",["RecoveryLeader","SelfHealingEcosystemController"],["RootCauseAnalystAgent","ImpactAssessorAgent","RecoveryPlannerAgent","FailurePatternAnalyzerAgent"],{"diagnosis_id":"uuid","anomaly_id":"ref AnomalyLog","root_cause":"string categorization","cause_category":"Playwright failure data extraction validation empty result memory stall","impact":"affected phases data loss risk checkpoint availability","recovery_plan":"action retry rollback escalate skip_and_log requalify adjusted_params checkpoint_id anomaly_flag"},{"creation":"after diagnosis","storage":"append link to AnomalyLog"},["anomaly_id ref required","root_cause required","recovery_plan action required"],"SelfHealingEcosystem","DiagnosisSub"))
MEMORY_COMPONENTS.append(mem("RecoveryLog","important_notes",["SelfHealingEcosystemController","SupremeOrchestratorAgent"],["RetryExecutorAgent","RollbackExecutorAgent","AlternativePathAgent","RecoveryValidatorAgent","EscalationManagerAgent"],{"recovery_id":"uuid","anomaly_id":"ref","diagnosis_id":"ref","action_taken":"retry rollback escalate skip_and_log requalify","execution_result":"success fail","checkpoint_restored":"bool","memory_updated":"bool","flow_continued":"bool","retry_count":"int","timestamp":"ISO","validation_result":"recovered without data loss or escalated"},{"creation":"after each recovery execution","storage":"append handle_failure schema must include phase error_type checkpoint_restored action_taken memory_updated flow_continued"},["action_taken required one of 5","checkpoint_restored bool required","memory_updated bool required","flow_continued bool required per handle_failure"],"SelfHealingEcosystem","RecoverySub"))
MEMORY_COMPONENTS.append(mem("SelfHealingCheckpoints","checkpoints",["SelfHealingEcosystemController","RollbackExecutorAgent","RecoveryValidatorAgent"],["CheckpointManagerAgent","MemoryWriterAgent","RecoveryLeader","DetectionLeader"],{"checkpoint_id":"uuid","type":"self_healing","phase":"string","timestamp":"ISO","state_before":"snapshot before anomaly","state_after":"snapshot after recovery","trigger_event":"on_self_healing_activation before_recovery after_recovery","parent_checkpoint_id":"uuid","valid":"bool","related_anomaly_id":"ref AnomalyLog"},{"creation":"before and after each recovery and on self-healing activation","restoration":"target for RollbackExecutor","validation":"MemoryValidator"},["type self_healing","trigger_event required","parent_checkpoint_id required","related_anomaly_id required"],"SelfHealingEcosystem"))

# Auto-Improvement
MEMORY_COMPONENTS.append(mem("FeedbackRegistry","important_notes",["ImprovementPlanningLeader","ResearchEcosystemController"],["OutcomeCollectorAgent","MemoryWriterAgent"],{"feedback_id":"uuid","source_phase":"string","outcome_summary":"GO_rate NO_GO reasons production_time self_healing_frequency plan_validity","timestamp":"ISO","cycle_id":"uuid production cycle"},{"creation":"upon outcome collection after cycle or periodic","storage":"append read by ImprovementPlanning for analysis"},["source_phase required","outcome_summary required","cycle_id required"],"AutoImprovementEcosystem","FeedbackSub"))
MEMORY_COMPONENTS.append(mem("ImprovementPlans","plans",["ImprovementExecutionLeader","ParameterAdjusterAgent"],["ImprovementPlanWriterAgent","ImprovementPlanningLeader","PlanStorageAgent"],{"plan_id":"uuid","plan_type":"improvement","target":"future research quality future qualification decisions future plan accuracy production flow speed risk detection sensitivity","source_feedback_id":"ref FeedbackRegistry","improvement_suggestion":"derived from outcome","priority":"high medium low","impact_estimate":"string","feasibility":"string","steps":"list steps","status":"planned executing applied validated"},{"creation":"after ImprovementPlanning","storage":"PlanStorage","execution":"ImprovementExecutionTeam"},["target must be one of 5 improvement_targets","improvement_suggestion required","priority required"],"AutoImprovementEcosystem","PlanningSub"))
MEMORY_COMPONENTS.append(mem("PerformanceHistory","important_notes",["ImprovementAnalystAgent","PriorityRankerAgent"],["PerformanceMetricsAgent","MemoryWriterAgent"],{"history_id":"uuid","phase":"string Research Qualification Planning Production Visual","metrics":"qualification_outcomes production_speed_metrics self_healing_activation_frequency plan_validity_scores memory_retrieval_patterns book_performance_signals","timestamp":"ISO","cycle_id":"uuid"},{"creation":"after metrics calculation each cycle","storage":"append historical used for pattern detection","retention":"persistent for learning"},["phase required","metrics dict with 6 feedback signals required","cycle_id required"],"AutoImprovementEcosystem","FeedbackSub"))
MEMORY_COMPONENTS.append(mem("LearningLog","important_notes",["SupremeOrchestratorAgent","All EcosystemControllers","ResearchEcosystemController"],["ParameterAdjusterAgent","ThresholdUpdaterAgent","WorkflowOptimizerAgent","LearningLoggerAgent"],{"log_id":"uuid","improvement_plan_id":"ref ImprovementPlans","what_learned":"string what system learned","what_changed":"parameter adjusted threshold updated flow optimized","target":"next cycle or next similar phase","before":"state before","after":"state after","validation":"measurable improvement boolean","timestamp":"ISO","memory_write":"True per generate_improvement_signal schema"},{"creation":"after improvement execution per generate_improvement_signal schema source_phase outcome_summary improvement_suggestion target memory_write True","use":"read by Research Qualification before new cycle to adapt"},["what_learned required","what_changed required","target required","improvement_plan_id ref required"],"AutoImprovementEcosystem","ExecutionSub"))
MEMORY_COMPONENTS.append(mem("PatternRegistry","important_notes",["ImprovementPlanningLeader"],["PatternDetectorAgent"],{"pattern_id":"uuid","pattern_type":"positive negative recurring","description":"string","frequency":"int","impact":"high medium low"},{"creation":"when pattern detected by PatternDetectorAgent"},["pattern_type required","description required"],"AutoImprovementEcosystem","FeedbackSub"))

print(f"MEMORY COMPONENTS EXPANDED: {len(MEMORY_COMPONENTS)} components total")
for cat in ["checkpoints","decisions","plans","hierarchies","important_notes"]:
    print(f"  {cat}: {len([m for m in MEMORY_COMPONENTS if m.category==cat])}")
