#!/usr/bin/env python3
"""
Master-Architect Memory Ecosystem Manager
Implements the screenshot structure + Ruflo + Content-Forge + Context-Eng + P10/P12 principles.
Updates INDEX after every step. Two-layer memory. Traceability mandatory.

Usage:
  python memory_manager.py --init --target=/path/to/project --vision="..."
  python memory_manager.py --checkpoint "Phase 3 MKD done" --phase=3 --target=...
  python memory_manager.py --decision "Use hierarchical topology" --rationale="Ruflo queen + PT01" --target=...
  python memory_manager.py --search "memory principles" --target=...

Integrates with Ruflo: if RUFLO_MEMORY=1, uses memory_store/search via subprocess or env.
"""

import os
import sys
import json
import datetime
from pathlib import Path
import argparse

def get_timestamp():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def ensure_memory_structure(target: str):
    mem_dir = Path(target) / "memory"
    subdirs = ["checkpoints", "decisions", "sessions", "plans", "architectures"]
    for sd in subdirs:
        (mem_dir / sd).mkdir(parents=True, exist_ok=True)
    index_path = mem_dir / "MEMORY-INDEX.md"
    if not index_path.exists():
        with open(index_path, "w") as f:
            f.write(f"""# MEMORY-INDEX.md — Master Architecture Memory Ecosystem

**Project:** {Path(target).name}  
**Vision:** [To be filled]  
**Started:** {get_timestamp()}  
**Objective:** Full traceability, self-improvement, memory-first architecture per Master-Architect skill.

**Rules (non-negotiable):**
- Update after EVERY step (tool call, decision, handoff, artifact).
- Two-layer: Short-term (sessions/ + current context) + Long-term (this INDEX + vector/Ruflo AgentDB).
- Research→Plan→Reset→Implement cycle documented.
- Trace every entry to sources (Pxx etc, clones, advisor, skill-creator, user input, knowledge-pack/).
- Failure modes logged.
- Python auto-update (this script).

**Current Status:** Initialized.

## Index of Checkpoints
- [CP-000] {get_timestamp()}: Memory ecosystem bootstrapped by memory_manager.py

## Index of Decisions
- [DEC-000] {get_timestamp()}: Memory structure created per user screenshot + P10 + Context-Eng + Ruflo.

## Index of Sessions
- [SES-000] {get_timestamp()}: Bootstrap session.

## Index of Plans
- [PLAN-000] {get_timestamp()}: Initial memory plan.

## Index of Architectures
- [ARCH-000] {get_timestamp()}: Memory architecture (two-layer FS + optional vector).

**Update Protocol:** After action, run this script or append manually + re-index.

**Principles Enforced:** P10 Self-Improvement, P12 Traceability, PT07 Silent-Observer, PT09 Multi-Source, Ruflo memory, Content-Forge failure-logs, Context-Eng two-layer.

---
*Living document. Auto-updated by memory_manager.py + Conductor.*
""")
    return mem_dir, index_path

def append_to_index(index_path: Path, section: str, entry: str):
    with open(index_path, "a") as f:
        f.write(f"\n- {entry}")
    print(f"Appended to {section} in INDEX.")

def create_checkpoint(target: str, desc: str, phase: int = 0, linked_principles: str = "P10, P12, PT07"):
    mem_dir, index_path = ensure_memory_structure(target)
    ts = get_timestamp()
    safe_desc = ''.join(c if c.isalnum() or c in '-_' else '-' for c in desc.replace(" ", "-").lower())[:60].strip('-')
    cp_file = mem_dir / "checkpoints" / f"CP-{phase:03d}-{safe_desc}-{ts.replace(' ', 'T').replace(':', '')}.md"
    content = f"""# Checkpoint CP-{phase:03d}: {desc}

**Timestamp:** {ts}  
**Phase:** {phase}  
**Linked Principles:** {linked_principles}  
**Traceability:** Generated by memory_manager.py for Master-Architect. Sources: user screenshot + P10-self-improvement-loops.md + Ruflo memory plugins + Content-Forge failure-modes-log + Context-Engineering-Advisor two-layer + this skill SKILL.md.

**Actions Completed:**
- {desc}

**Rationale:** Memory update after step (P10, user req "fin da subito").

**Evidence:** This file + INDEX append.

**Next:** [To be filled by Conductor]

**Status:** ✅ Complete.
"""
    with open(cp_file, "w") as f:
        f.write(content)
    append_to_index(index_path, "Checkpoints", f"[CP-{phase:03d}] {ts}: {desc}")
    print(f"Created {cp_file}")
    return str(cp_file)

def record_decision(target: str, title: str, context: str, decision: str, alternatives: str, rationale: str, consequences: str, traceability: str):
    mem_dir, index_path = ensure_memory_structure(target)
    ts = get_timestamp()
    safe_title = title.replace(" ", "-").lower()[:50]
    dec_file = mem_dir / "decisions" / f"DEC-{safe_title}-{ts.replace(' ', 'T').replace(':', '')}.md"
    content = f"""# Decision Record: {title}

**Date:** {ts}

**Context:** {context}

**Decision:** {decision}

**Alternatives Considered:**
{alternatives}

**Rationale:** {rationale}

**Consequences:**
{consequences}

**Traceability:** {traceability}
Sources: P10 + P12 + PT01 + Ruflo swarm/memory + Content-Forge PT02 + Context-Eng + knowledge-pack/ + user vision.

**Status:** ✅ Implemented.
"""
    with open(dec_file, "w") as f:
        f.write(content)
    append_to_index(index_path, "Decisions", f"[DEC] {ts}: {title} — {decision[:80]}...")
    print(f"Created {dec_file}")
    return str(dec_file)

def main():
    parser = argparse.ArgumentParser(description="Master-Architect Memory Manager")
    parser.add_argument("--init", action="store_true", help="Initialize memory structure")
    parser.add_argument("--target", required=True, help="Target project root for memory/")
    parser.add_argument("--vision", help="Project vision (for init)")
    parser.add_argument("--checkpoint", help="Create checkpoint with this desc")
    parser.add_argument("--phase", type=int, default=0)
    parser.add_argument("--decision", help="Record decision with this title")
    parser.add_argument("--rationale", help="Rationale for decision")
    # Add more args as needed for full
    args = parser.parse_args()

    if args.init:
        mem_dir, index = ensure_memory_structure(args.target)
        if args.vision:
            # Update INDEX with vision
            with open(index, "r") as f:
                content = f.read()
            content = content.replace("[To be filled]", args.vision)
            with open(index, "w") as f:
                f.write(content)
        print(f"Memory ecosystem initialized at {mem_dir}")
        create_checkpoint(args.target, "Memory ecosystem bootstrapped", 0, "P10, P12, user screenshot, Ruflo, Context-Eng")

    elif args.checkpoint:
        create_checkpoint(args.target, args.checkpoint, args.phase)

    elif args.decision:
        # Simplified; in real would prompt for full fields or take more args
        record_decision(args.target, args.decision, "From conductor handoff", args.decision, "See full ADR", args.rationale or "Per principles", "Full traceability and memory update", "P10 + P12 + Ruflo memory + Context-Eng + knowledge-pack")

    else:
        print("No action. Use --help")

if __name__ == "__main__":
    main()
