# -*- coding: utf-8 -*-
"""Web Department: ricerca avanzata e crawl di siti/documentazione (Playwright, no API)."""

DEPT = "web-department"

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT, "level": 2, "lead": "conductor",
        "role": "Capo del reparto Web: gestisce ricerche avanzate e siti/documentazione, "
                "coordina web-researcher, site-crawler e doc-extractor, e consegna materiale "
                "testuale strutturato (con screenshot di UI dove utile) a Processing.",
        "mission": "Trasformare query/URL web in conoscenza strutturata per la wiki, usando "
                   "Playwright (no API), con screenshot delle sezioni chiave quando rilevante.",
        "skills": ["skills/tier1-department/web-pipeline-skill",
                   "skills/tier2-functional/web-research-skill"],
        "responsibilities": [
            "Classificare l'input: query di ricerca, singola pagina, o sito da crawlare.",
            "Delegare la ricerca avanzata a web-researcher (Playwright, no API).",
            "Far crawlare i siti rilevanti a site-crawler e estrarre il contenuto a doc-extractor.",
            "Far catturare screenshot delle sezioni chiave (UI/diagrammi) per la visione.",
            "Consegnare a Processing materiale testuale + eventuali screenshot con trace a URL.",
        ],
        "inputs": "query o URL/sito + focus dal Conductor.",
        "outputs": "run con contenuto testuale strutturato + screenshot + sources.json (URL).",
        "tools": [
            {"name": "web_research.py", "desc": "ricerca/crawl via Playwright (no API)",
             "cmd": "python scripts/web_research.py --query \"<q>\" --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Paywall/login", "symptom": "contenuto inaccessibile", "prevention": "rileva il blocco",
             "detection": "redirect login", "recovery": "salta, segnala, usa fonti aperte"},
            {"failure": "Robots/anti-bot", "symptom": "blocco crawler", "prevention": "rispetta robots, rate sobrio",
             "detection": "403/captcha", "recovery": "passa a fonte alternativa"},
            {"failure": "Contenuto dinamico", "symptom": "pagina vuota senza JS", "prevention": "Playwright (render JS)",
             "detection": "DOM vuoto", "recovery": "attendi il render, riprova"},
            {"failure": "Troppe pagine", "symptom": "crawl infinito", "prevention": "cap profondita'/pagine", "detection": "coda enorme",
             "recovery": "limita lo scope alle pagine pertinenti"},
            {"failure": "Fonte inaffidabile", "symptom": "contenuto di bassa qualita'", "prevention": "valuta autorevolezza",
             "detection": "segnali spam", "recovery": "declassa o scarta"},
        ],
        "evals": [
            {"name": "Ricerca", "input": "query focus", "expected": "fonti pertinenti con URL"},
            {"name": "Sito", "input": "URL doc", "expected": "contenuto estratto + screenshot sezioni chiave"},
            {"name": "Dinamico", "input": "SPA JS", "expected": "contenuto reso, non vuoto"},
            {"name": "Blocco", "input": "paywall", "expected": "gestito, fonte alternativa"},
        ],
        "memory": {"checkpoints": "ricerca/crawl web completati", "knowledge-state": "fonti web raccolte"},
        "trace": "risponde a 'siti web o ricerca estremamente avanzata sul web'.",
    },
    {
        "name": "web-researcher",
        "department": DEPT, "level": 3,
        "role": "Esegue ricerche web avanzate con Playwright (no API): trova fonti "
                "pertinenti, le valuta e produce una lista di URL da approfondire.",
        "skills": ["skills/tier2-functional/web-research-skill"],
        "responsibilities": [
            "Formulare ricerche efficaci per il focus (operatori, query multiple).",
            "Navigare i risultati con Playwright e raccogliere candidati URL.",
            "Valutare autorevolezza/pertinenza prima di approfondire.",
            "Produrre sources.json con URL + motivo di selezione.",
        ],
        "inputs": "query/focus.",
        "outputs": "runs/<run-id>/sources.json (URL + razionale).",
        "tools": [{"name": "web_research.py", "desc": "ricerca via Playwright",
                   "cmd": "python scripts/web_research.py --query \"<q>\" --run <run-id>"}],
        "failure_modes": [
            {"failure": "Query povere", "symptom": "risultati irrilevanti", "prevention": "varia le query", "detection": "match debole",
             "recovery": "riformula con sinonimi/operatori"},
            {"failure": "SEO spam", "symptom": "fonti di bassa qualita'", "prevention": "filtra per autorevolezza",
             "detection": "domini spam", "recovery": "scarta"},
            {"failure": "Captcha motore", "symptom": "ricerca bloccata", "prevention": "navigazione sobria", "detection": "captcha",
             "recovery": "usa fonti dirette/documentazione"},
            {"failure": "Bolla linguistica", "symptom": "solo risultati in 1 lingua", "prevention": "query multilingua",
             "detection": "lingua unica", "recovery": "aggiungi query in altra lingua"},
            {"failure": "Troppi risultati", "symptom": "rumore", "prevention": "cap top-N", "detection": "lista enorme",
             "recovery": "tieni i piu' pertinenti/autorevoli"},
        ],
        "evals": [
            {"name": "Fonti pertinenti", "input": "query focus", "expected": "URL pertinenti motivati"},
            {"name": "Anti-spam", "input": "risultati misti", "expected": "spam scartato"},
            {"name": "Multilingua", "input": "tema internazionale", "expected": "fonti in piu' lingue"},
            {"name": "Cap", "input": "molti risultati", "expected": "top-N selezionati"},
        ],
        "memory": {"checkpoints": "ricerca completata", "strategy-applications": "query usate ed esito"},
        "trace": "ricerca avanzata web senza API (Playwright).",
    },
    {
        "name": "site-crawler",
        "department": DEPT, "level": 3,
        "role": "Naviga e crawla i siti selezionati con Playwright, raccogliendo le pagine "
                "pertinenti e catturando screenshot di UI/diagrammi chiave.",
        "skills": ["skills/tier2-functional/web-research-skill"],
        "responsibilities": [
            "Aprire gli URL con Playwright (render JS) e seguire i link interni pertinenti.",
            "Rispettare cap di profondita'/pagine e robots.",
            "Catturare screenshot delle sezioni visive importanti (per la visione di Claude).",
            "Salvare HTML/markdown grezzo e screenshot con trace a URL.",
        ],
        "inputs": "sources.json (URL).",
        "outputs": "runs/<run-id>/web/ (pagine + screenshot) + manifest URL->file.",
        "tools": [{"name": "web_research.py (crawl)", "desc": "crawl + screenshot via Playwright",
                   "cmd": "python scripts/web_research.py --crawl <url> --run <run-id> --max-pages 10"}],
        "failure_modes": [
            {"failure": "Loop di link", "symptom": "crawl infinito", "prevention": "visited-set + cap", "detection": "ripetizioni",
             "recovery": "interrompi al cap"},
            {"failure": "Pagine pesanti", "symptom": "timeout render", "prevention": "timeout + lazy load", "detection": "render lento",
             "recovery": "screenshot parziale + testo"},
            {"failure": "Screenshot inutili", "symptom": "immagini senza valore", "prevention": "cattura solo sezioni chiave",
             "detection": "screenshot generici", "recovery": "mirati a UI/diagrammi"},
            {"failure": "Contenuto duplicato", "symptom": "stesse pagine", "prevention": "dedup per URL canonico", "detection": "URL ripetuti",
             "recovery": "deduplica"},
            {"failure": "Cookie/consent", "symptom": "overlay blocca", "prevention": "gestisci banner consent", "detection": "modale",
             "recovery": "chiudi/accetta il banner e procedi"},
        ],
        "evals": [
            {"name": "Crawl mirato", "input": "URL doc", "expected": "pagine pertinenti + screenshot chiave"},
            {"name": "Cap rispettato", "input": "sito grande", "expected": "max-pages rispettato"},
            {"name": "Render JS", "input": "SPA", "expected": "contenuto reso"},
            {"name": "Dedup", "input": "link ridondanti", "expected": "nessun duplicato"},
        ],
        "memory": {"checkpoints": "sito crawlato", "knowledge-state": "pagine raccolte con URL"},
        "trace": "crawl con Playwright (repo playwright fornita), screenshot per la visione.",
    },
    {
        "name": "doc-extractor",
        "department": DEPT, "level": 3,
        "role": "Estrae il contenuto utile dalle pagine crawlate (testo principale, code "
                "block, tabelle) ripulendolo da boilerplate, con trace all'URL.",
        "skills": ["skills/tier2-functional/web-research-skill"],
        "responsibilities": [
            "Estrarre il main content (no nav/footer/ads) dalle pagine raccolte.",
            "Preservare code block, tabelle, heading (struttura semantica).",
            "Allegare la trace all'URL (e allo screenshot se la sezione e' visiva).",
            "Produrre materiale testuale pulito per knowledge-extractor.",
        ],
        "inputs": "runs/<run-id>/web/ (pagine raccolte).",
        "outputs": "runs/<run-id>/web-content.md (pulito, con trace URL).",
        "tools": [{"name": "doc-extract", "desc": "estrazione main content (readability-like)",
                   "cmd": "(logica dell'agente; opzionale helper python in web-research-skill)"}],
        "failure_modes": [
            {"failure": "Boilerplate incluso", "symptom": "nav/ads nel testo", "prevention": "euristiche main-content",
             "detection": "rumore", "recovery": "ripulisci con euristiche piu' forti"},
            {"failure": "Code rotto", "symptom": "snippet sformattati", "prevention": "preserva <pre>/<code>", "detection": "code mescolato",
             "recovery": "ripristina i blocchi"},
            {"failure": "Tabelle perse", "symptom": "dati tabellari appiattiti", "prevention": "converti tabelle in markdown",
             "detection": "tabella assente", "recovery": "ricostruisci dalla struttura"},
            {"failure": "Trace mancante", "symptom": "testo senza URL", "prevention": "trace obbligatoria", "detection": "campo vuoto",
             "recovery": "riassocia all'URL sorgente"},
            {"failure": "Encoding", "symptom": "caratteri rotti", "prevention": "utf-8 robusto", "detection": "mojibake",
             "recovery": "normalizza encoding"},
        ],
        "evals": [
            {"name": "Main content", "input": "pagina con nav/ads", "expected": "solo contenuto utile"},
            {"name": "Code", "input": "pagina con snippet", "expected": "code block preservati"},
            {"name": "Tabelle", "input": "pagina con tabella", "expected": "tabella in markdown"},
            {"name": "Trace", "input": "qualunque", "expected": "ogni blocco con URL sorgente"},
        ],
        "memory": {"checkpoints": "contenuto web estratto", "knowledge-state": "testo web pulito con trace"},
        "trace": "prepara il materiale web per il forge, con tracciabilita' a URL.",
    },
]
