# -*- coding: utf-8 -*-
"""Spec ricche del YouTube Department (generate da agent_factory.py)."""

DEPT = "youtube-department"

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT,
        "level": 2,
        "lead": "conductor",
        "role": "Capo del reparto YouTube: riceve il link da Conductor, decide il flusso "
                "(video singolo vs canale), coordina i suoi agenti e consegna il materiale "
                "ingerito a Processing & Vision.",
        "mission": "Trasformare un link YouTube grezzo in materiale ingerito e pronto per la "
                   "visione, coordinando ingester e screening del reparto.",
        "skills": ["skills/tier1-department/youtube-pipeline-skill",
                   "skills/tier2-functional/yt-ingest-skill"],
        "responsibilities": [
            "Classificare l'input: URL di video singolo, canale, o playlist.",
            "Per i canali, delegare a yt-screening la selezione dei video rilevanti per --focus.",
            "Assegnare a yt-channel-ingester / video-single-ingester l'ingestion vera (yt_ingest.py).",
            "Consegnare a Processing & Vision le run pronte (ingest.json) con priorita'.",
            "Aggiornare workflow-state con l'avanzamento del reparto.",
        ],
        "inputs": "URL YouTube + focus + target dal Conductor (Strategy Manifest allegato).",
        "outputs": "una o piu' run in runs/<run-id>/ con ingest.json, pronte per la visione.",
        "when": "appena il Conductor instrada un input --dept=youtube.",
        "tools": [
            {"name": "yt_ingest.py", "desc": "ingestion + screening canali",
             "cmd": "python scripts/yt_ingest.py --input <url> --focus <focus> --run <run-id>"},
            {"name": "memory_manager.py", "desc": "checkpoint/stato del reparto",
             "cmd": "python scripts/memory_manager.py --checkpoint \"youtube: instradati N video\" --phase 1"},
        ],
        "failure_modes": [
            {"failure": "Input ambiguo (shortened URL)", "symptom": "non si capisce se video o canale",
             "prevention": "normalizza l'URL e interroga yt-dlp per il tipo", "detection": "yt-dlp ritorna playlist vs entry singola",
             "recovery": "espandi l'URL; in dubbio tratta come video singolo"},
            {"failure": "Canale enorme", "symptom": "centinaia di video, rischio timeout",
             "prevention": "cap --max e screening per focus", "detection": "total_candidates molto alto",
             "recovery": "batch da 15, avvisa il Conductor, prioritizza per focus"},
            {"failure": "Video privato/rimosso", "symptom": "yt-dlp errore extract",
             "prevention": "ignoreerrors + check ritorno", "detection": "ingest.json non creato",
             "recovery": "salta il video, logga in errors, continua con gli altri"},
            {"failure": "Focus non matcha nulla", "symptom": "0 video selezionati",
             "prevention": "fallback a screening per views/recency", "detection": "selected==0",
             "recovery": "allarga il match o chiedi al Conductor un focus alternativo"},
            {"failure": "Mancano i sottotitoli", "symptom": "subs vuoto in ingest.json",
             "prevention": "richiedi auto-sub multi-lingua", "detection": "campo subs vuoto",
             "recovery": "procedi con soli frame + metadata, segnala la limitazione a Vision"},
        ],
        "evals": [
            {"name": "Video singolo", "input": "URL di un video", "expected": "1 run con ingest.json (id, durata, capitoli, subs)"},
            {"name": "Canale con focus", "input": "URL canale + focus=design", "expected": "videos.json con solo i video pertinenti, <= max"},
            {"name": "Canale senza focus", "input": "URL canale", "expected": "selezione per recency/views, cap rispettato"},
            {"name": "Video rimosso", "input": "URL non valido", "expected": "errore gestito, log in errors, nessun crash"},
        ],
        "memory": {
            "checkpoints": "instradamento e completamento ingest del reparto",
            "workflow-state": "stato dei video del reparto (ingeriti/da visionare)",
            "errors": "video saltati (privati/rimossi)",
        },
        "trace": "risponde a 'parti anche solo da un link di canale... screening di tutti i video' + reparto YouTube simmetrico.",
    },
    {
        "name": "yt-channel-ingester",
        "department": DEPT,
        "level": 3,
        "role": "Ingerisce canali/playlist YouTube: elenca i video, scarica metadata e "
                "sottotitoli dei selezionati, prepara le run.",
        "skills": ["skills/tier2-functional/yt-ingest-skill"],
        "responsibilities": [
            "Eseguire yt_ingest.py in modalita' canale (extract_flat) per elencare i video.",
            "Applicare il filtro di screening ricevuto da yt-screening.",
            "Per ogni video selezionato, scaricare info.json + auto-subs + thumbnail.",
            "Creare una run per video (o una run con videos.json) per il reparto Vision.",
        ],
        "inputs": "URL canale + lista id selezionati (da yt-screening) + focus.",
        "outputs": "runs/<run-id>/ingest.json (kind=channel) + per-video subs/metadata.",
        "tools": [
            {"name": "yt_ingest.py (channel)", "desc": "screening + metadata canale",
             "cmd": "python scripts/yt_ingest.py --input <channel-url> --focus <f> --max 15 --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Paginazione canale incompleta", "symptom": "mancano video recenti",
             "prevention": "playlistend ampio poi filtra", "detection": "conteggio < atteso",
             "recovery": "rilancia con playlistend maggiore"},
            {"failure": "Rate limit yt-dlp", "symptom": "429/timeout", "prevention": "richieste sobrie, no download di massa",
             "detection": "errori HTTP nei log", "recovery": "attendi e ritenta in batch piu' piccoli"},
            {"failure": "Sottotitoli in lingua sbagliata", "symptom": "vtt non in en/it",
             "prevention": "subtitleslangs multipli", "detection": "lingua vtt != richiesta",
             "recovery": "prendi auto-sub disponibili, segnala a transcript-processor"},
            {"failure": "Video shorts misti", "symptom": "shorts irrilevanti nel set",
             "prevention": "filtro per durata minima", "detection": "durate <60s in massa",
             "recovery": "escludi gli shorts se il focus e' su long-form"},
            {"failure": "ID duplicati tra playlist", "symptom": "stesso video piu' volte",
             "prevention": "dedup per id", "detection": "id ripetuti in videos.json",
             "recovery": "deduplica mantenendo la prima occorrenza"},
        ],
        "evals": [
            {"name": "Lista canale", "input": "URL canale", "expected": "videos.json con id/titolo/durata"},
            {"name": "Screening applicato", "input": "lista id selezionati", "expected": "solo quelli ingeriti con subs"},
            {"name": "Dedup", "input": "playlist con duplicati", "expected": "nessun id ripetuto"},
            {"name": "Resilienza", "input": "canale con 2 video privati", "expected": "ingeriti gli altri, privati in errors"},
        ],
        "memory": {
            "checkpoints": "canale ingerito: N video, M con subs",
            "knowledge-state": "elenco video del canale (per run future sullo stesso canale)",
        },
        "trace": "risponde a 'mando il link di un canale e tu fai screening di tutti i video'.",
    },
    {
        "name": "yt-screening",
        "department": DEPT,
        "level": 3,
        "role": "Filtra i video di un canale/playlist per pertinenza (focus, argomento, "
                "qualita') prima dell'ingestion pesante, per efficienza.",
        "skills": ["skills/tier2-functional/yt-ingest-skill"],
        "responsibilities": [
            "Ricevere la lista grezza dei video del canale (titolo/descrizione/durata/views).",
            "Applicare regole di screening: match focus su titolo/descrizione, soglia durata, recency.",
            "Produrre la shortlist di id da ingerire, ordinata per pertinenza.",
            "Spiegare il razionale di selezione (perche' inclusi/esclusi) per tracciabilita'.",
        ],
        "inputs": "videos.json grezzo dal channel-ingester + focus/strategia.",
        "outputs": "shortlist.json (id selezionati + score + motivo) per l'ingester.",
        "tools": [
            {"name": "screening (regole)", "desc": "match focus/durata/recency su metadata",
             "cmd": "(logica eseguita dall'agente leggendo videos.json; nessun download)"},
        ],
        "failure_modes": [
            {"failure": "Falsi negativi", "symptom": "video rilevanti scartati",
             "prevention": "match su titolo+descrizione+tag", "detection": "shortlist troppo corta",
             "recovery": "allenta la soglia, includi i borderline con score basso"},
            {"failure": "Falsi positivi", "symptom": "clickbait irrilevante incluso",
             "prevention": "penalizza titoli generici", "detection": "score alti su contenuti vaghi",
             "recovery": "richiedi conferma o declassa"},
            {"failure": "Focus vuoto", "symptom": "nessun criterio", "prevention": "fallback a recency+views",
             "detection": "focus assente", "recovery": "ordina per recency e prendi i top N"},
            {"failure": "Metadata poveri", "symptom": "titoli non descrittivi",
             "prevention": "usa anche durata/capitoli", "detection": "descrizioni vuote",
             "recovery": "segnala incertezza, lascia decidere al lead"},
            {"failure": "Lingua mista", "symptom": "video in lingue diverse", "prevention": "rileva lingua dal titolo",
             "detection": "set multilingua", "recovery": "raggruppa per lingua, prioritizza quella utile"},
        ],
        "evals": [
            {"name": "Match focus", "input": "30 video, focus=marketing", "expected": "shortlist coerente col focus, con motivi"},
            {"name": "No focus", "input": "30 video, nessun focus", "expected": "top per recency/views"},
            {"name": "Borderline", "input": "video ambigui", "expected": "inclusi con score basso, non scartati a priori"},
            {"name": "Razionale", "input": "qualunque", "expected": "ogni inclusione/esclusione motivata"},
        ],
        "memory": {
            "strategy-applications": "criteri di screening usati e risultato",
            "agent-state": "precision/recall stimati delle selezioni per migliorare",
        },
        "trace": "risponde a 'screening di tutti i video del canale oppure dell'argomento'.",
    },
    {
        "name": "video-single-ingester",
        "department": DEPT,
        "level": 3,
        "role": "Ingerisce un singolo video YouTube in modo completo (metadata, capitoli, "
                "sottotitoli, thumbnail), pronto per la visione.",
        "skills": ["skills/tier2-functional/yt-ingest-skill"],
        "responsibilities": [
            "Eseguire yt_ingest.py per un singolo URL (no download video, solo info+subs).",
            "Verificare presenza di capitoli (guida la strategia di frame extraction).",
            "Normalizzare il transcript (passa a transcript-processor se necessario).",
            "Creare la run pronta e segnalarne durata/capitoli a Processing & Vision.",
        ],
        "inputs": "URL di un video singolo + focus.",
        "outputs": "runs/<run-id>/ingest.json (kind=single-video) + subs + thumbnail.",
        "tools": [
            {"name": "yt_ingest.py (single)", "desc": "info+subs+thumbnail",
             "cmd": "python scripts/yt_ingest.py --input <video-url> --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Video lunghissimo (3h+)", "symptom": "info pesante, molti capitoli",
             "prevention": "nessun download in questo stadio", "detection": "durata enorme",
             "recovery": "passa a Vision con nota di pianificare molti frame per capitolo"},
            {"failure": "Nessun capitolo", "symptom": "chapters vuoto", "prevention": "fallback a frame per %",
             "detection": "ingest.json chapters==[]", "recovery": "segnala a frame-extractor di usare intervalli"},
            {"failure": "Auto-sub assenti", "symptom": "subs vuoto", "prevention": "richiedi piu' lingue",
             "detection": "nessun vtt", "recovery": "procedi solo-visione, dichiara limite"},
            {"failure": "Eta'-restricted/login", "symptom": "yt-dlp richiede auth", "prevention": "rileva il caso",
             "detection": "errore login nei log", "recovery": "segnala al lead, salta o chiedi alternativa"},
            {"failure": "Thumbnail webp non gestita", "symptom": "thumbnail in formato raro",
             "prevention": "accetta jpg/webp", "detection": "estensione inattesa", "recovery": "ignora la thumbnail, non bloccante"},
        ],
        "evals": [
            {"name": "Video con capitoli", "input": "URL con capitoli", "expected": "chapters popolati in ingest.json"},
            {"name": "Video senza capitoli", "input": "URL senza capitoli", "expected": "nota per frame a intervalli"},
            {"name": "Subs presenti", "input": "URL con auto-sub", "expected": "vtt scaricato"},
            {"name": "Resilienza", "input": "URL restricted", "expected": "gestito senza crash, segnalato"},
        ],
        "memory": {
            "checkpoints": "video singolo ingerito (id, durata, capitoli, subs)",
            "workflow-state": "run pronta per Vision",
        },
        "trace": "risponde a 'ti do questo video, tu prendi tutto il contenuto materiale'.",
    },
]
