import sys; sys.path.insert(0, '/home/user/architettura_completa_7_livelli')
from core import Ecosystem

ECOSYSTEMS = []

# Helper to make sub-ecosystems rich
def sub_eco(name, controller, agents, teams, memories):
    return {"name": name, "controller": controller, "agents": agents, "teams": teams, "memories": memories, "description": f"Sub-ecosistema {name} attivo con agenti reali"}

ECOSYSTEMS.append(Ecosystem(
    name="ResearchEcosystem",
    controller_agent="ResearchEcosystemController L2",
    sub_ecosystems=[
        sub_eco("PlaywrightOperationsSubEcosystem","ResearchEcosystemController L2",["PlaywrightNavigatorMicroAgent L7","PlaywrightDataCaptureMicroAgent L7","PlaywrightScreenshotMicroAgent L7","PlaywrightErrorHandlerAgent L7","AmazonPageNavigatorAgent L7","AmazonDetailExtractorAgent L7","ReviewSiteNavigatorAgent L7","ReviewDataCaptureAgent L7","SaveOperationMicroAgent L7"],[],["ResearchCheckpoints","RawData"]),
        sub_eco("PersistenceSubEcosystem","DataPersistenceLeader L3",["PlaywrightSaveAgent L5","DataFormatterAgent L5","SaveValidatorAgent L6","RawDataArchiverAgent L5"], ["DataPersistenceTeam"], ["BookOpportunityRegistry","ReviewDataRegistry"]),
        sub_eco("ExpansionSubEcosystem","KeywordExpansionLeader L3",["KeywordVariationGeneratorAgent L5","SemanticKeywordExpanderAgent L5","LongTailKeywordAgent L5"], ["KeywordExpansionTeam"], ["KeywordExpansionLog"]),
        sub_eco("OptimizationSubEcosystem","SearchOptimizationLeader L3",["SearchStrategyOptimizerAgent L5","PlaywrightRotationManagerAgent L5"], ["SearchOptimizationTeam"], ["SearchOptimizationLog"]),
    ],
    agents_inside=[
        "ResearchEcosystemController L2",
        "AmazonResearchLeader L3","KeywordGeneratorAgent L5","AmazonSearchAgent L5","AmazonDataExtractorAgent L5","AmazonResultsValidatorAgent L6","KeywordQualityAnalystAgent L4","NicheCompetitionAnalystAgent L4","SearchQualityValidatorAgent L6","NicheViabilityValidatorAgent L6",
        "ReviewResearchLeader L3","ReviewSiteFinderAgent L5","ReviewDataExtractorAgent L5","ReviewScoreNormalizerAgent L6","ReviewDataValidatorAgent L6","ReviewSentimentAnalystAgent L4",
        "DataPersistenceLeader L3","PlaywrightSaveAgent L5","DataFormatterAgent L5","SaveValidatorAgent L6","RawDataArchiverAgent L5",
        "KeywordExpansionLeader L3","KeywordVariationGeneratorAgent L5","SemanticKeywordExpanderAgent L5","LongTailKeywordAgent L5",
        "SearchOptimizationLeader L3","SearchStrategyOptimizerAgent L5","PlaywrightRotationManagerAgent L5",
        "PlaywrightNavigatorMicroAgent L7","PlaywrightDataCaptureMicroAgent L7","PlaywrightScreenshotMicroAgent L7","PlaywrightErrorHandlerAgent L7","AmazonPageNavigatorAgent L7","AmazonDetailExtractorAgent L7","ReviewSiteNavigatorAgent L7","ReviewDataCaptureAgent L7","SaveOperationMicroAgent L7"
    ],
    teams_inside=["AmazonKeywordResearchTeam","ReviewAnalysisResearchTeam","DataPersistenceTeam","KeywordExpansionTeam","SearchOptimizationTeam"],
    flows_inside=["MAIN_PRODUCTION_FLOW Phase1 Research","PLAYWRIGHT_OPERATIONS_FLOW Navigation+Extraction+Save+Error Handling","SELF_HEALING_FLOW on empty result Playwright failure"],
    memory_components_inside=["ResearchCheckpoints","ResearchDecisions","BookOpportunityRegistry","ReviewDataRegistry","KeywordExpansionLog","SearchOptimizationLog","checkpoints","decisions","important_notes","RawData"],
    skills_inside=["BookNicheDecisionSkill","PlaywrightNavigationSkill","PlaywrightDataExtractionSkill","PlaywrightSaveSkill","SelfHealingSkill","MemoryReadWriteSkill","CheckpointManagementSkill"],
    integration_points={
        "MemoryEcosystem CoreMemorySub": ["MemoryWriterAgent L5 scrive BookOpportunityRegistry ReviewDataRegistry ResearchCheckpoints RawData via MemoryWriterAgent","MemoryReaderAgent L5 legge important_notes hierarchies FeedbackRegistry LearningLog PatternRegistry per keyword patterns","CheckpointManagerAgent L6 crea CP1 Research End parent CP0 valid True trigger end batch before handoff qualification on healing","MemoryValidatorAgent L6 valida ResearchCheckpoints BookOpportunityRegistry ReviewDataRegistry completeness coherence","DecisionLoggerAgent logs keyword_selection niche_ranking retry_strategy","HierarchyManagerAgent maintains hierarchies 7 levels routing escalation"],
        "SelfHealingEcosystem DetectionSub": ["DetectionTeam L3 OutputMonitorAgent L4 monitors books_found non empty structured_output ready","PlaywrightFailureDetectorAgent L6 detects Playwright timeout blocked CAPTCHA","ErrorDetectorAgent L7 detects errors exceptions","AnomalyDetectorAgent L4 detects empty result pattern","StallDetectorAgent L7 detects frozen search","RecoveryTeam RetryExecutor L5 retry adjusted keywords from important_notes LearningLog FeedbackRegistry SemanticKeywordExpander LongTailKeywordAgent - RollbackExecutor L6 rollback CP0 if Playwright failure via PlaywrightErrorHandlerAgent timeout++ user_agent rotate alternative selector","AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints"],
        "AutoImprovementEcosystem FeedbackSub": ["FeedbackCollectionTeam reads ResearchCheckpoints performance metrics self-healing frequency - PatternDetector detects keyword patterns success failure - LearningLog important_notes FeedbackRegistry PatternRegistry provides keyword learnings to KeywordGeneratorAgent SemanticKeywordExpanderAgent LongTailKeywordAgent","Future research quality improved via ParameterAdjusterAgent threshold updates"],
        "QualificationEcosystem handoff": ["Handoff Research->Qualification via Memory broker 8 steps: 1 Source DataPersistenceLeader creates package books_found review_sites_found raw_data refs BookOpportunityRegistry ReviewDataRegistry structured_output CP1 - 2 Memory logs via MemoryWriterAgent - 3 Source confirms ready writes checkpoint CP1 - 4 Target QualificationEcosystemController + QualificationLeader confirms receipt reads via MemoryReaderAgent - 5 Target validates completeness via QualificationAnalysisTeam validators - 6 If fails SelfHealing DetectionTeam - 7 If passes target begins qualification - 8 Memory logs completion - validation required checkpoint_required memory_logged self_healing on failure"],
        "PlaywrightOperationalToolReal": ["PlaywrightNavigatorMicroAgent L7 real navigate_amazon_keyword_search url https://www.amazon.com/s?k={keyword} - PlaywrightDataCaptureMicroAgent extract_data selectors title author ratings prices - PlaywrightScreenshotMicroAgent screenshot raw_data - PlaywrightSaveAgent save_results results sources URLs notes useful material - PlaywrightErrorHandlerAgent handle_error retry 3 max adjusted params timeout++ user_agent rotate alternative selector - VisualSaveMicroAgent used by Research RawData archiving - allowed uses #1 navigation data collection Amazon #2 review sites #3 saving results #4 visual support - compliance PLAYWRIGHT_USAGE_POLICY"],
        "SupremeOrchestrator L1": ["reports status to ResearchEcosystemController L2 -> SupremeOrchestratorAgent L1 cycle_start_signal, GO_rate, empty result count, Playwright failure count"]
    },
    hierarchy_levels_covered=[2,3,4,5,6,7],
    description="Research Ecosystem purpose: Find books via keyword search on Amazon, find sites that analyze or calculate Amazon reviews, collect all relevant data, save everything via Playwright. Teams: AmazonKeywordResearchTeam, ReviewAnalysisResearchTeam, DataPersistenceTeam, KeywordExpansionTeam, SearchOptimizationTeam. Sub-ecosystems: PlaywrightOperations, Persistence, Expansion, Optimization. Memory active system with agents Reader Writer Validator CheckpointManager DecisionLogger. Self-healing real with Detection Diagnosis Recovery."
))

ECOSYSTEMS.append(Ecosystem(
    name="QualificationEcosystem",
    controller_agent="QualificationEcosystemController L2",
    sub_ecosystems=[
        sub_eco("AnalysisSubEcosystem","QualificationLeader L3",["ReproducibilityAnalystAgent L4","AbsurdityDetectorAgent L4","ProductionSpeedAnalystAgent L4","MarketAlignmentAnalystAgent L4","PlanQualityAuditorAgent L4","CompetitionAnalystAgent L4","SustainabilityAnalystAgent L4","BusinessFitAnalystAgent L4"], ["QualificationAnalysisTeam"], ["QualificationCheckpoints","RiskRegistry"]),
        sub_eco("DecisionSubEcosystem","QualificationDecisionLeader L3",["DecisionAggregatorAgent L4","RiskFlagManagerAgent L4","QualificationReportWriterAgent L5","DecisionQualityCheckerAgent L5"], ["QualificationDecisionTeam"], ["QualificationDecisions","QualificationPlans"]),
    ],
    agents_inside=[
        "QualificationEcosystemController L2",
        "QualificationLeader L3","ReproducibilityAnalystAgent L4","AbsurdityDetectorAgent L4","ProductionSpeedAnalystAgent L4","MarketAlignmentAnalystAgent L4","PlanQualityAuditorAgent L4","CompetitionAnalystAgent L4","SustainabilityAnalystAgent L4","BusinessFitAnalystAgent L4",
        "QualificationDecisionLeader L3","DecisionAggregatorAgent L4","RiskFlagManagerAgent L4","QualificationReportWriterAgent L5","DecisionQualityCheckerAgent L5"
    ],
    teams_inside=["QualificationAnalysisTeam","QualificationDecisionTeam"],
    flows_inside=["MAIN_PRODUCTION_FLOW Phase2 Qualification + Decision Gate DG1 GO NO-GO","SELF_HEALING_FLOW on incoherent missing output no-go without alternative failed validation"],
    memory_components_inside=["QualificationCheckpoints","QualificationDecisions","QualificationPlans","RiskRegistry","BusinessFitScores","checkpoints","decisions","plans","important_notes"],
    skills_inside=["BookNicheDecisionSkill","QualificationDecisionSkill","SelfHealingSkill","AnomalyDetectionSkill","RecoveryExecutionSkill","SecondLevelPlanCoherenceSkill"],
    integration_points={
        "MemoryEcosystem": ["MemoryReaderAgent reads BookOpportunityRegistry ReviewDataRegistry ResearchDecisions important_notes FeedbackRegistry LearningLog - MemoryWriterAgent writes QualificationCheckpoints QualificationDecisions QualificationPlans RiskRegistry BusinessFitScores - DecisionLoggerAgent logs GO NO-GO immutable reasoning traceability - PlanStorageAgent stores qualification plans versioned - CheckpointManagerAgent creates CP2 Qualification End per book + batch parent CP1"],
        "SelfHealing": ["DetectionTeam monitors missing output incoherent output no-go without alternative failed validation - DiagnosisTeam RootCauseAnalyst ImpactAssessor - RecoveryTeam requalify with anomaly flag rollback CP1 AlternativePath requests new research cycle via ResearchEcosystemController - AnomalyLog DiagnosisLog RecoveryLog"],
        "AutoImprovement": ["FeedbackCollectionTeam collects qualification outcomes GO rate NO-GO main reasons - PatternDetector detects GO rate low nicchia - LearningLog important_notes FeedbackRegistry provides learnings - ParameterAdjusterAgent ThresholdUpdaterAgent updates GO threshold 70 based learning - future qualification decisions improved"],
        "Research handoff incoming": ["receives handoff Research->Qualification validated structured_output BookOpportunityRegistry ReviewDataRegistry CP1 via Memory broker 8 steps validation - if all NO-GO without alternative trigger new research cycle via AlternativePathAgent"],
        "Planning handoff outgoing": ["handoff Qualification->Planning only GO decisions via Memory broker: GO decision + qualification report + risk_flags + QualificationDecisions + QualificationPlans + CP2 - protocol 8 steps validation required checkpoint memory logged self-healing - only GO advances NO-GO archived archived + new research request"],
        "Skills": ["BookNicheDecisionSkill owner AmazonResearchLeader ReviewResearchLeader QualificationLeader MarketAlignmentAnalystAgent trigger enough data execution steps aggregate market demand competition reproducibility rank flag absurd too slow output ranked list motivation success at least one viable - QualificationDecisionSkill owner QualificationLeader DecisionAggregatorAgent trigger all analysts completated execution steps collect scores weighted reproducibility 30% speed 25% absurdity 20% market 25% threshold 70 GO NO-GO"]
    },
    hierarchy_levels_covered=[2,3,4,5,6],
    description="Qualification Ecosystem purpose: Receive research output, create detailed qualification plan, evaluate every book opportunity against strict criteria reproducibility absurdity speed market fit plan validity, determine if book can be reproduced, determine if absurd unrealistic too slow, evaluate qualification plan itself, output clear go/no-go decisions. Business goal quantity-performance: performanti riproducibili sostenibili non assurdi non lenti."
))

ECOSYSTEMS.append(Ecosystem(
    name="PlanningEcosystem",
    controller_agent="PlanningEcosystemController L2",
    sub_ecosystems=[
        sub_eco("StructureSubEcosystem","StructurePlanningLeader L3",["VideoStructureArchitectAgent L4","ChapterDesignerAgent L4","DetailFillerAgent L4","PlanCoherenceValidatorAgent L4","VideoStructureValidatorAgent L4","OutlineOptimizerAgent L4"], ["StructurePlanningTeam"], ["SecondLevelPlans","VideoStructureControlPoints"]),
        sub_eco("ReadinessSubEcosystem","ProductionReadinessLeader L3",["ReadinessCheckerAgent L5","ResourceEstimatorAgent L5","ProductionStartSignalAgent L5","RiskMitigationPlannerAgent L5"], ["ProductionReadinessTeam"], ["ProductionStartSignals","PlanningCheckpoints"]),
        sub_eco("ContentSubEcosystem","ContentPlanningLeader L3",["ContentDetailArchitectAgent L5","ContentFlowDesignerAgent L5","ResourceAllocationPlannerAgent L5"], ["ContentPlanningTeam"], ["SecondLevelPlans details enriched"]),
    ],
    agents_inside=[
        "PlanningEcosystemController L2",
        "StructurePlanningLeader L3","VideoStructureArchitectAgent L4 CRITICAL","ChapterDesignerAgent L4","DetailFillerAgent L4","PlanCoherenceValidatorAgent L4","VideoStructureValidatorAgent L4","OutlineOptimizerAgent L4",
        "ProductionReadinessLeader L3","ReadinessCheckerAgent L5","ResourceEstimatorAgent L5","ProductionStartSignalAgent L5","RiskMitigationPlannerAgent L5",
        "ContentPlanningLeader L3","ContentDetailArchitectAgent L5","ContentFlowDesignerAgent L5","ResourceAllocationPlannerAgent L5","ContentDetailArchitectAgent2 L5"
    ],
    teams_inside=["StructurePlanningTeam","ProductionReadinessTeam","ContentPlanningTeam"],
    flows_inside=["MAIN_PRODUCTION_FLOW Phase 3-5 Planning + Decision Gate DG2 Plan Approval + Control Point CP-VIDEO-01","SELF_HEALING_FLOW on missing video_structure CRITICAL incoherent output failed validation"],
    memory_components_inside=["PlanningCheckpoints","SecondLevelPlans","ProductionStartSignals","VideoStructureControlPoints","checkpoints","decisions","plans","important_notes"],
    skills_inside=["VideoStructureDesignSkill","ChapterDesignSkill","SecondLevelPlanCoherenceSkill","ProductionReadinessSkill","SelfHealingSkill","CheckpointManagementSkill","AnomalyDetectionSkill"],
    integration_points={
        "MemoryEcosystem": ["MemoryReaderAgent reads QualificationDecisions RiskRegistry plans decisions QualificationPlans - MemoryWriterAgent writes PlanningCheckpoints SecondLevelPlans ProductionStartSignals VideoStructureControlPoints - PlanStorageAgent stores second-level plans versioned not overwritten - DecisionLoggerAgent logs production_start_signal TRUE timestamp validated_by - CheckpointManagerAgent creates CP3 Planning End critical production start parent CP2 - MemoryValidatorAgent validates video_structure present verbatim chapters non-empty details concrete"],
        "SelfHealing": ["DetectionTeam OutputMonitor detects missing video_structure REQUIRED critical field missing -> AnomalyLog severity critical - DiagnosisTeam RootCauseAnalyst video_structure missing - ImpactAssessor impact all production blocked - RecoveryPlanner recovery plan retry forced read original requirement handle_ambiguity preserve_and_encapsulate - RecoveryTeam RetryExecutor retry with forced read original requirement handle_ambiguity preserve_and_encapsulate create validation checkpoint forbidden fill_with_assumptions - RollbackExecutor rollback CP2 - AlternativePath requalify - EscalationManager escalate to Supreme if 3 fails - RecoveryValidator validates"],
        "Qualification incoming": ["receives GO package QualificationDecisions QualificationPlans RiskRegistry CP2 via Memory broker validated"],
        "Production outgoing": ["handoff Planning->Production second_level_plan complete {video_structure REQUIRED preserved verbatim explicit control point CP-VIDEO-01 handle_ambiguity preserve_and_encapsulate + chapters list title description order purpose estimated_effort fast sustainable slow + details every relevant production detail concrete not vague production_constraints style_notes business_alignment_notes graphic_needs sustainability_check + production_start_signal TRUE timestamp validated_by ProductionReadinessLeader} + Content enriched + ProductionStartSignals + CP3 parent CP2 valid True - protocol 8 steps - marks actual start production flow per requirements - Decision Gate DG2 video_structure present verbatim non-empty non-reinterpreted chapters non-empty details concrete production_start_signal TRUE coherence validation passed"],
        "CriticalControlPoint": ["CP-VIDEO-01 video_structure REQUIRED preserved verbatim - original requirement do not remove reinterpret ignore - handle_ambiguity original_requirement ambiguity_detected True action preserve_and_encapsulate resolution_method create_validation_checkpoint forbidden_action fill_with_assumptions output explicit_control_point_in_workflow - VideoStructureArchitectAgent L4 CRITICAL designs video_structure - VideoStructureValidatorAgent L4 validates present verbatim - Control point explicit in second level plan - Self-healing critical failure if missing"]
    },
    hierarchy_levels_covered=[2,3,4,5,6],
    description="Planning Ecosystem purpose: Receive qualified book opportunities GO, create second-level operational plan, define video structure REQUIRED original requirement do not remove reinterpret, define chapters every detail, mark actual start production. Critical: video_structure control point."
))

ECOSYSTEMS.append(Ecosystem(
    name="ProductionEcosystem",
    controller_agent="ProductionEcosystemController L2",
    sub_ecosystems=[
        sub_eco("WritingSubEcosystem","BookWritingLeader L3",["ChapterWriterAgent L5","ConsistencyCheckerAgent L4","StyleEnforcerAgent L4","ContentQualityReviewerAgent L4","ChapterDependencyManagerAgent L5","WritingProgressTrackerAgent L4","ProductionLogWriterAgent L5"], ["BookWritingTeam"], ["ProductionCheckpoints","ProductionLog"]),
        sub_eco("QualitySubEcosystem","ProductionQualityLeader L3",["ManuscriptValidatorAgent L4","PlanComplianceCheckerAgent L4","FinalApprovalAgent L6","QualityMetricsCalculatorAgent L4","ContentValidationAgent L6"], ["ProductionQualityTeam"], ["CompletedManuscripts","ProductionCheckpoints"]),
        sub_eco("EditingSubEcosystem","EditingLeader L3",["EditingCoordinatorAgent L5","FinalProofreaderAgent L5","CrossReferenceCheckerAgent L5"], ["EditingTeam"], ["EditingLog"]),
    ],
    agents_inside=[
        "ProductionEcosystemController L2",
        "BookWritingLeader L3","ChapterWriterAgent L5 multiple instances","ConsistencyCheckerAgent L4","StyleEnforcerAgent L4","ContentQualityReviewerAgent L4","ChapterDependencyManagerAgent L5","WritingProgressTrackerAgent L4","WritingQualityCheckerAgent L6","ProductionLogWriterAgent L5",
        "ProductionQualityLeader L3","ManuscriptValidatorAgent L4","PlanComplianceCheckerAgent L4","FinalApprovalAgent L6","QualityMetricsCalculatorAgent L4","ContentValidationAgent L6",
        "EditingLeader L3","EditingCoordinatorAgent L5","FinalProofreaderAgent L5","CrossReferenceCheckerAgent L5"
    ],
    teams_inside=["BookWritingTeam","ProductionQualityTeam","EditingTeam"],
    flows_inside=["MAIN_PRODUCTION_FLOW Phase 6 Production Write Entire Book + Decision Gate DG3 Production Quality","SELF_HEALING_FLOW on blocked process incoherent output memory write failure stall"],
    memory_components_inside=["ProductionCheckpoints","ProductionLog","CompletedManuscripts","EditingLog","checkpoints","decisions","plans","important_notes"],
    skills_inside=["BookWritingConsistencySkill","StyleEnforcementSkill","MemoryReadWriteSkill","CheckpointManagementSkill","SelfHealingSkill","SecondLevelPlanCoherenceSkill"],
    integration_points={
        "MemoryEcosystem": ["MemoryReaderAgent L5 reads SecondLevelPlans ProductionStartSignals decisions plans checkpoints hierarchies important_notes qualification_plan risk_flags for context continuity - MemoryWriterAgent writes ProductionCheckpoints per chapter critical ProductionLog decisions_made consistency_checks deviations CompletedManuscripts EditingLog - CheckpointManagerAgent creates CP4 per chapter + CP4 final parent CP3 - MemoryValidatorAgent validates completeness - DecisionLoggerAgent logs editing decisions - PlanStorageAgent stores CompletedManuscripts validated approved final"],
        "SelfHealing": ["DetectionTeam StallDetectorAgent L7 detects blocked process heart beat missing phase timeout - OutputMonitorAgent L4 detects incoherent output vs second_level_plan - DiagnosisTeam RootCauseAnalyst impact assessment - RecoveryTeam RetryExecutor retry chapter memory read reconnection context - RollbackExecutor rollback last chapter CP4 - AlternativePath requalify partial anomaly flag - RecoveryValidator validates recovery without data loss - AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints important_notes handle_failure schema phase error_type checkpoint_restored True action_taken memory_updated True flow_continued True"],
        "Planning incoming": ["receives second_level_plan complete video_structure REQUIRED chapters details production_start_signal TRUE + ProductionStartSignals + CP3 via Memory broker 8 steps validated"],
        "Visual outgoing": ["handoff Production->Visual completed manuscript ref path Playwright save + plan reference SecondLevelPlans + production log + EditingLog + CP4 final parent CP3 valid True via Memory broker 8 steps validation required memory logged checkpoint required"],
        "BusinessGoal": ["quantity-performance: privilegia libri performanti riproducibili sostenibili non assurdi non troppo lenti da realizzare - production sustainability via ResourceEstimatorAgent + SpeedAnalyst"]
    },
    hierarchy_levels_covered=[2,3,4,5,6,7],
    description="Production Ecosystem purpose: Receive approved second-level plan, write entire book, maintain consistency with previous decisions constraints, read from memory to maintain context continuity. Teams: BookWritingTeam parallel chapter writing, ProductionQualityTeam validation compliance final approval, EditingTeam editing proofreading cross-reference."
))

ECOSYSTEMS.append(Ecosystem(
    name="VisualEcosystem",
    controller_agent="VisualEcosystemController L2",
    sub_ecosystems=[
        sub_eco("GraphicSubEcosystem","GraphicDesignLeader L3",["GraphicPromptCreatorAgent L5","GraphicGeneratorAgent L5","GraphicQualityReviewerAgent L6","GraphicRevisionAgent L6","GraphicStyleEnforcerAgent L5","VisualConsistencyCheckerAgent L4","GraphicPromptMicroAgent L7"], ["GraphicDesignTeam"], ["GraphicPrompts","GeneratedGraphics"]),
        sub_eco("CoverSubEcosystem","CoverDesignLeader L3",["CoverConceptAgent L4","CoverPromptCreatorAgent L5","CoverGeneratorAgent L5","CoverQualityReviewerAgent L6","CoverRevisionAgent L6","CoverMarketFitAnalystAgent L4","CoverPromptMicroAgent L7"], ["CoverDesignTeam"], ["CoverVersions"]),
        sub_eco("VisualPlaywrightSubEcosystem","VisualPlaywrightLeader L3",["VisualPlaywrightNavigatorAgent L7","VisualPlaywrightSaveAgent L6","VisualPlaywrightValidatorAgent L6","VisualPlaywrightCaptureAgent L7","VisualSaveMicroAgent L7"], ["VisualPlaywrightOperationsTeam"], ["GeneratedGraphics","CoverVersions"]),
        sub_eco("VisualQualitySubEcosystem","VisualQualityLeader L3",["VisualQualityAuditorAgent L4","FinalVisualApprovalAgent L6"], ["VisualQualityTeam"], ["VisualProductionLog","VisualQualityLog"]),
    ],
    agents_inside=[
        "VisualEcosystemController L2",
        "GraphicDesignLeader L3","GraphicPromptCreatorAgent L5","GraphicGeneratorAgent L5","GraphicQualityReviewerAgent L6","GraphicRevisionAgent L6","GraphicStyleEnforcerAgent L5","VisualConsistencyCheckerAgent L4","GraphicPromptMicroAgent L7",
        "CoverDesignLeader L3","CoverConceptAgent L4","CoverPromptCreatorAgent L5","CoverGeneratorAgent L5","CoverQualityReviewerAgent L6","CoverRevisionAgent L6","CoverMarketFitAnalystAgent L4","CoverPromptMicroAgent L7",
        "VisualPlaywrightLeader L3","VisualPlaywrightNavigatorAgent L7","VisualPlaywrightSaveAgent L6","VisualPlaywrightValidatorAgent L6","VisualPlaywrightCaptureAgent L7","VisualSaveMicroAgent L7",
        "VisualQualityLeader L3","VisualQualityAuditorAgent L4","FinalVisualApprovalAgent L6"
    ],
    teams_inside=["GraphicDesignTeam","CoverDesignTeam","VisualPlaywrightOperationsTeam","VisualQualityTeam"],
    flows_inside=["MAIN_PRODUCTION_FLOW Phase 7 Visual Graphics Prompts Cover via Playwright Support + Decision Gate DG4 Visual Quality + PLAYWRIGHT_OPERATIONS_FLOW visual_save","SELF_HEALING_FLOW on Playwright failure missing output cover missing"],
    memory_components_inside=["GraphicPrompts","GeneratedGraphics","CoverVersions","VisualProductionLog","VisualQualityLog","checkpoints"],
    skills_inside=["GraphicPromptEngineeringSkill","CoverConceptDesignSkill","PlaywrightNavigationSkill","PlaywrightSaveSkill","SelfHealingSkill","RecoveryExecutionSkill"],
    integration_points={
        "MemoryEcosystem": ["MemoryReaderAgent reads CompletedManuscripts SecondLevelPlans chapters production_log EditingLog details graphic_needs - MemoryWriterAgent writes GraphicPrompts GeneratedGraphics CoverVersions VisualProductionLog VisualQualityLog - CheckpointManagerAgent creates CP5 Visual End + CP_FINAL parent CP4 final valid True global - MemoryValidatorAgent validates graphics approved prompts tracciati cover final approved saved via Playwright confirmed - PlanStorageAgent stores CoverVersions versions"],
        "SelfHealing": ["DetectionTeam OutputMonitor detects missing output cover missing graphics missing prompts not tracciati - PlaywrightFailureDetector detects Playwright failure save visual - DiagnosisTeam RootCause Playwright failure - RecoveryTeam RetryExecutor retry PlaywrightErrorHandlerAgent adjusted params timeout++ user_agent rotate - RollbackExecutor rollback CP4 if needed - AlternativePath skip_and_log single graphic non-critical log continua where possible - cover critical cannot skip_and_log must escalate flag anomaly pause branch log important_notes EscaltionManager escalate to VisualEcosystemController then Supreme - RecoveryValidator validates without data loss - AnomalyLog DiagnosisLog RecoveryLog"],
        "Production incoming": ["receives completed manuscript ref + plan ref + production log + CP4 final parent CP3 via Memory broker 8 steps validated - handoff Production->Visual"],
        "PlaywrightToolReal": ["PlaywrightOperationalToolReal visual_save support visual creation saving processes allowed use #4 - VisualPlaywrightNavigatorAgent L7 navigation real tool - VisualPlaywrightSaveAgent L6 save_results visual_save destination memory GeneratedGraphics CoverVersions save confirmation via VisualPlaywrightValidatorAgent L6 validation - PlaywrightErrorHandlerAgent L7 handles failures retry 2x skip_and_log non-critical graphic escalate cover critical - MICRO agents GraphicPromptMicroAgent CoverPromptMicroAgent VisualSaveMicroAgent atomic single prompt single save"],
        "FinalAssembly": ["outputs all graphics approved refs via Playwright visual_save + graphic_prompts all prompts tracciati GraphicPrompts + cover final approved CoverVersions critical + VisualProductionLog VisualQualityLog + CP5 CP_FINAL + final package ready for Amazon - Decision Gate DG4 visual quality graphics approved or skipped non-critical logged prompts tracciati cover final approved Playwright saves confirmed visual consistency quality audit final approval"],
        "FinalValidation": ["Validation: complete_book not partial coherence with second_level_plan chapters respected video_structure considered per VideoStructureControlPoints no absurd flagged RiskRegistry cover present final approved not missing graphic_prompts tracciati graphics saved via Playwright confirmed VisualPlaywrightValidatorAgent memory_write complete all categories CP_FINAL exists valid parent chain"]
    },
    hierarchy_levels_covered=[2,3,4,5,6,7],
    description="Visual Ecosystem purpose: Create all graphics, create all prompts for graphics generation, create book cover, use Playwright where needed real operational tool support visual creation saving. Teams: GraphicDesignTeam prompt creation generation quality review revision loop, CoverDesignTeam concept prompt generation quality critical cannot skip, VisualPlaywrightOperationsTeam navigation save via Playwright, VisualQualityTeam quality audit final approval."
))

ECOSYSTEMS.append(Ecosystem(
    name="MemoryEcosystem",
    controller_agent="MemoryEcosystemController L2",
    sub_ecosystems=[
        sub_eco("CoreMemorySubEcosystem","MemoryManagerLeader L3",["MemoryWriterAgent L5","MemoryReaderAgent L5","MemoryValidatorAgent L6","CheckpointManagerAgent L6","DecisionLoggerAgent L6","PlanStorageAgent L6","HierarchyManagerAgent L6","ImportantNotesAgent L6"], ["MemoryManagementTeam"], ["checkpoints","decisions","plans","hierarchies","important_notes"]),
        sub_eco("CheckpointSubEcosystem","CheckpointSubLeader L3",["CheckpointCreatorAgent L5","CheckpointValidatorAgent L6","CheckpointRestorerAgent L6","CheckpointPrunerAgent L6","CheckpointCreateMicroAgent L7","CheckpointRestoreMicroAgent L7"], ["CheckpointSubEcosystem"], ["checkpoints","SelfHealingCheckpoints","ResearchCheckpoints","QualificationCheckpoints","PlanningCheckpoints","ProductionCheckpoints"]),
        sub_eco("DecisionLogSubEcosystem","DecisionLogSubLeader L3",["DecisionLogWriterAgent L5","DecisionLogReaderAgent L6","DecisionTraceabilityAgent L6","DecisionLogMicroAgent L7"], ["DecisionLogSubEcosystem"], ["decisions","QualificationDecisions","ProductionStartSignals","AnomalyLog","DiagnosisLog","RecoveryLog"]),
        sub_eco("PlanStorageSubEcosystem","MemoryManagerLeader L3",["PlanStorageAgent L6"], ["MemoryManagementTeam"], ["SecondLevelPlans","QualificationPlans","CompletedManuscripts","CoverVersions","ImprovementPlans"]),
        sub_eco("ImportantNotesSubEcosystem","MemoryManagerLeader L3",["ImportantNotesAgent L6"], ["MemoryManagementTeam"], ["important_notes","RiskRegistry","VisualProductionLog","LearningLog","FeedbackRegistry"]),
    ],
    agents_inside=[
        "MemoryEcosystemController L2",
        "MemoryManagerLeader L3","MemoryWriterAgent L5","MemoryReaderAgent L5","MemoryValidatorAgent L6","CheckpointManagerAgent L6","DecisionLoggerAgent L6","PlanStorageAgent L6","HierarchyManagerAgent L6","ImportantNotesAgent L6",
        "CheckpointSubLeader L3","CheckpointCreatorAgent L5","CheckpointValidatorAgent L6","CheckpointRestorerAgent L6","CheckpointPrunerAgent L6",
        "DecisionLogSubLeader L3","DecisionLogWriterAgent L5","DecisionLogReaderAgent L6","DecisionTraceabilityAgent L6",
        "MemoryReadMicroAgent L7","MemoryWriteMicroAgent L7","CheckpointCreateMicroAgent L7","CheckpointRestoreMicroAgent L7","DecisionLogMicroAgent L7"
    ],
    teams_inside=["MemoryManagementTeam","CheckpointSubEcosystem","DecisionLogSubEcosystem"],
    flows_inside=["MEMORY_MAINTENANCE_FLOW periodic or triggered by MemoryValidatorAgent corruption gap detection - Consistency Check Gap Detection Corruption Detection Cleanup Optimization Validation","MAIN_PRODUCTION_FLOW checkpoint creation at every phase transition","SELF_HEALING_FLOW checkpoint restoration via RollbackExecutorAgent","AUTO_IMPROVEMENT_FLOW LearningLog FeedbackRegistry reads writes"],
    memory_components_inside=["checkpoints","decisions","plans","hierarchies","important_notes","ResearchCheckpoints","ResearchDecisions","BookOpportunityRegistry","ReviewDataRegistry","KeywordExpansionLog","SearchOptimizationLog","QualificationCheckpoints","QualificationDecisions","QualificationPlans","RiskRegistry","BusinessFitScores","PlanningCheckpoints","SecondLevelPlans","ProductionStartSignals","VideoStructureControlPoints","ProductionCheckpoints","ProductionLog","CompletedManuscripts","EditingLog","GraphicPrompts","GeneratedGraphics","CoverVersions","VisualProductionLog","VisualQualityLog","AnomalyLog","DiagnosisLog","RecoveryLog","SelfHealingCheckpoints","FeedbackRegistry","ImprovementPlans","PerformanceHistory","LearningLog","PatternRegistry"],
    skills_inside=["MemoryReadWriteSkill","CheckpointManagementSkill","SelfHealingSkill","AnomalyDetectionSkill","RecoveryExecutionSkill"],
    integration_points={
        "AllEcosystems AllTeams AllAgents always_active always_integrated": ["ACTIVE SYSTEM NOT PASSIVE STORAGE - contains agents that manage validate serve memory to all other ecosystems - small but super efficient memory ecosystem always active always integrated always accessible - Every ecosystem has memory connector that communicates with MemoryManagementTeam L3 - Writes validated before storage by MemoryValidatorAgent L6 - Reads served with context timestamp by MemoryReaderAgent L5 - Checkpoints created automatically at every phase transition before major decision before handoff on self-healing activation by CheckpointManagerAgent L6 - Decisions logged immutable with full context reasoning chain by DecisionLoggerAgent L6 append-only - Plans stored versioned via PlanStorageAgent L6 validity score - Hierarchies maintained via HierarchyManagerAgent L6 agents hierarchies 7 levels - ImportantNotes stored via ImportantNotesAgent L6 critical notions risk flags anomaly logs keyword patterns improvement suggestions - Read/Write protocols defined: read(category, requester) returns data timestamp, write(category, data, writer) returns data_written checkpoint_created timestamp","Memory Structure 5 core categories per original requirements: checkpoints state snapshots critical points written by all teams read by self-healing all teams on recovery when end each phase critical decision - decisions all go/no-go qualification decisions written by qualification planning read by production auto-improvement when every decision point - plans qualification plans second-level plans written by qualification planning read by production visual when plan approved validated - hierarchies agent hierarchies team responsibilities written by orchestrator read by all teams when initialization update - important notes critical notions risk flags anomaly logs written by all teams self-healing engine read by all teams auto-improvement whenever relevant signal detected"],
        "SelfHealingEcosystem": ["MemoryValidatorAgent L6 detects corruption gaps triggers SelfHealing flow DetectionTeam OutputMonitor - CheckpointManagerAgent L6 restoration target for RollbackExecutorAgent L6 RollbackExecutor restores from checkpoint_before anomaly - SelfHealingCheckpoints stored before after each recovery parent chain - AnomalyLog DiagnosisLog RecoveryLog logged via MemoryWriterAgent - MemoryFailureDetectorAgent L6 detects memory write failure corruption gap"],
        "SupremeOrchestrator L1": ["HierarchyManagerAgent receives hierarchies from SupremeOrchestratorAgent L1 at initialization and on update - CheckpointManagerAgent reports global checkpoints CP0-CP_FINAL to Supreme - LearningLog PerformanceHistory FeedbackRegistry reports to Supreme for macro decisions - DecisionLoggerAgent logs Supreme overrides"],
        "MemoryValidation": ["MemoryValidatorAgent L6 validates consistency: checkpoints align with decisions plans hierarchies important_notes - decisions have reasoning traceable not empty - plans have validity score - hierarchies exactly 7 levels not corrupted Supreme 1 L2 8 L3 19-25 L4 35-40 L5 40-45 L6 35-40 L7 20-25 - important_notes not empty content - checkpoint chain parent IDs valid parent exists valid True - BookOpportunityRegistry amazon_url valid Amazon - SecondLevelPlans video_structure present verbatim - If fails trigger MEMORY_MAINTENANCE_FLOW Cleanup Optimization - If critical corruption trigger SelfHealing rollback"],
        "CheckpointLogic": ["CheckpointManagerAgent: creation triggers end of each phase before each major decision GO NO-GO before each handoff on self-healing activation per chapter in production periodic - storage via CheckpointManagerAgent versioned with parent ID valid flag created_by - restoration via RollbackExecutorAgent + CheckpointManagerAgent restore with parent chain - validation MemoryValidatorAgent checks alignment decisions plans - checkpoint categories: ResearchCheckpoints, QualificationCheckpoints, PlanningCheckpoints, ProductionCheckpoints, VisualProductionLog? actually CP5 Visual End, CP_FINAL global, SelfHealingCheckpoints before after recovery, Core checkpoints global - 9+ rollback points CP0_INIT CP1 CP2 CP3 CP4 per chapter CP4 final CP5 CP_FINAL SelfHealingCheckpoints any checkpoint via CheckpointManager"]
    },
    hierarchy_levels_covered=[2,3,5,6,7],
    description="Memory Ecosystem purpose: Provide small but super efficient memory ecosystem always active always integrated always accessible contains agents managing memory validating serving to all other ecosystems. NOT passive storage - active system with own agents MemoryWriter Reader Validator CheckpointManager DecisionLogger PlanStorage HierarchyManager ImportantNotes + sub-ecosystems CheckpointSub DecisionLogSub PlanStorageSub ImportantNotesSub. Stores checkpoints decisions plans hierarchies important notes per original requirements + 35 expanded components."
))

ECOSYSTEMS.append(Ecosystem(
    name="SelfHealingEcosystem",
    controller_agent="SelfHealingEcosystemController L2",
    sub_ecosystems=[
        sub_eco("DetectionSubEcosystem","DetectionLeader L3",["OutputMonitorAgent L4","ErrorDetectorAgent L7","AnomalyDetectorAgent L4","StallDetectorAgent L7","PlaywrightFailureDetectorAgent L6","MemoryFailureDetectorAgent L6","ValidationCheckMicroAgent L7"], ["DetectionTeam"], ["AnomalyLog"]),
        sub_eco("DiagnosisSubEcosystem","DiagnosisLeader L3",["RootCauseAnalystAgent L4","ImpactAssessorAgent L4","RecoveryPlannerAgent L4","FailurePatternAnalyzerAgent L4"], ["DiagnosisTeam"], ["DiagnosisLog","PatternRegistry"]),
        sub_eco("RecoverySubEcosystem","RecoveryLeader L3",["RetryExecutorAgent L5","RollbackExecutorAgent L6","AlternativePathAgent L7","RecoveryValidatorAgent L6","EscalationManagerAgent L6"], ["RecoveryTeam"], ["RecoveryLog","SelfHealingCheckpoints"]),
    ],
    agents_inside=[
        "SelfHealingEcosystemController L2",
        "DetectionLeader L3","OutputMonitorAgent L4","ErrorDetectorAgent L7","AnomalyDetectorAgent L4","StallDetectorAgent L7","PlaywrightFailureDetectorAgent L6","MemoryFailureDetectorAgent L6","ValidationCheckMicroAgent L7",
        "DiagnosisLeader L3","RootCauseAnalystAgent L4","ImpactAssessorAgent L4","RecoveryPlannerAgent L4","FailurePatternAnalyzerAgent L4",
        "RecoveryLeader L3","RetryExecutorAgent L5","RollbackExecutorAgent L6","AlternativePathAgent L7","RecoveryValidatorAgent L6","EscalationManagerAgent L6"
    ],
    teams_inside=["DetectionTeam","DiagnosisTeam","RecoveryTeam"],
    flows_inside=["SELF_HEALING_FLOW Detection Diagnosis Recovery Planning Execution Validation Memory Update - start any anomaly anywhere","MAIN_PRODUCTION_FLOW integrated healing on each phase failure","MEMORY_MAINTENANCE_FLOW triggered on memory corruption gap","PLAYWRIGHT_OPERATIONS_FLOW error handling via PlaywrightErrorHandlerAgent"],
    memory_components_inside=["AnomalyLog","DiagnosisLog","RecoveryLog","SelfHealingCheckpoints","checkpoints","important_notes","PatternRegistry"],
    skills_inside=["SelfHealingSkill","AnomalyDetectionSkill","RecoveryExecutionSkill","CheckpointManagementSkill","MemoryReadWriteSkill","PlaywrightNavigationSkill"],
    integration_points={
        "AllEcosystems Always-On Real Active System": ["REAL ACTIVE ALWAYS-ON SELF-HEALING ACROSS ENTIRE WORKFLOW - NOT description - real system with real agents that detect diagnose fix problems - DetectionTeam L3 Leader manages OutputMonitorAgent L4 monitors phase outputs completeness coherence vs expected schemas books_found non empty qualification plan 5 criteria second_level_plan video_structure REQUIRED complete_book non empty graphics+cover present - ErrorDetectorAgent L7 detects errors exceptions failures logs - AnomalyDetectorAgent L4 unusual patterns unexpected states all NO-GO without alternative video_structure missing cover missing memory gap - StallDetectorAgent L7 stalled frozen no heartbeat timeout - PlaywrightFailureDetectorAgent L6 Playwright timeout blocked CAPTCHA - MemoryFailureDetectorAgent L6 memory write failure corruption gap - aggregated anomaly report severity critical high medium low location team agent error_type context checkpoint_before timestamp status detected - DiagnosisTeam L3 Leader RootCauseAnalystAgent L4 root cause categorization Playwright failure data extraction validation empty result memory stall absurdity - ImpactAssessorAgent L4 impact affected phases data loss risk checkpoint availability rollback possible alternative path severity scoring - FailurePatternAnalyzer recurring patterns - RecoveryPlannerAgent L4 creates recovery plan choosing action retry rollback escalate skip_and_log requalify with adjusted params checkpoint ID anomaly flag mapping error_type to action per SelfHealingEngine response_actions - RecoveryTeam L3 Leader RetryExecutorAgent L5 retry adjusted params timeout++ user_agent rotate alternative selector new keywords memory reread - RollbackExecutorAgent L6 rollback to previous checkpoints via CheckpointManagerAgent restore parent chain - AlternativePathAgent L7 finds executes alternative path different keyword strategy skip_and_log non-critical graphic requalify back qualification anomaly flag - RecoveryValidatorAgent L6 validates recovery success without data loss checkpoint valid no residual anomaly - EscalationManagerAgent L6 escalates to controller L2 then Supreme L1 after max 3 retries fails - 8 detection triggers: missing output, incoherent output, blocked process, failed validation, empty result from research, no-go without alternative path, memory write failure, Playwright failure - 5 response actions: retry adjusted params, rollback to last valid checkpoint, escalate flag anomaly pause branch log important_notes, skip_and_log broken step log continue where possible only non-critical, requalify send back qualification anomaly flag - handle_failure schema mental: phase error_type checkpoint_restored True action_taken response_actions[error_type] or escalate memory_updated True flow_continued True"],
        "MemoryEcosystem": ["reads checkpoints decisions important_notes AnomalyLog via MemoryReaderAgent L5 - writes AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints important_notes via MemoryWriterAgent L5 - CheckpointManagerAgent L6 restoration target RollbackExecutorAgent restore checkpoint_before - MemoryValidatorAgent L6 triggers flow on corruption gap - SelfHealingCheckpoints stored before after each recovery parent chain"],
        "PlaywrightToolReal": ["PlaywrightErrorHandlerAgent L7 handles timeouts blocked pages connection failures CAPTCHAs with retry alternative strategies timeout++ user_agent rotate alternative selector max 3 retries then escalate - PlaywrightFailureDetectorAgent detects Playwright failures - RetryExecutor executes retry with adjusted params - integration PlaywrightOperationalToolReal handle_error method returns handling_strategy with adjusted_params memory_log_required checkpoint_ref self_healing_integration"],
        "SupremeOrchestrator L1": ["escalates to SupremeOrchestratorAgent L1 after max retries fails 3 per anomaly - escalation action flag anomaly pause branch log important_notes - full diagnosis log AnomalyLog DiagnosisLog RecoveryLog + anomaly report severity location context - Supreme overrides global rollback CP0_INIT if critical"],
        "Skills": ["SelfHealingSkill owner all detection diagnosis recovery agents + PlaywrightErrorHandlerAgent CheckpointManagerAgent MemoryValidatorAgent - trigger any anomaly error stall incoherent output - execution steps 1 Detect DetectionTeam OutputMonitor ErrorDetector AnomalyDetector StallDetector 2 Diagnose root cause impact - RootCauseAnalyst ImpactAssessor 3 Create recovery plan RecoveryPlanner mapping error_type action 4 Execute recovery RetryExecutor RollbackExecutor AlternativePath 5 Validate recovery RecoveryValidator 6 Log memory AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints important_notes 7 If fails after max retries escalate to controller - success criteria workflow continues without data loss - failure handling escalate to Supreme - retry logic max 3 retries per anomaly then escalate checkpoint creation before after each recovery"]
    },
    hierarchy_levels_covered=[2,3,4,5,6,7],
    description="Self-Healing Ecosystem purpose: Provide real active always-on self-healing across entire workflow - NOT description - real system with real agents that detect diagnose fix problems - Teams: DetectionTeam 6 agents monitoring outputs errors anomalies stalls Playwright failures memory failures, DiagnosisTeam 4 agents root cause impact recovery planning pattern analysis, RecoveryTeam 5 agents retry rollback alternative validation escalation - Flows: SELF_HEALING_FLOW 6 phases Detection Diagnosis Recovery Planning Execution Validation Memory Update - 8 triggers 5 actions handle_failure schema - Integration Memory Playwright Supreme - Skill SelfHealingSkill transversal reused every team dedicated logic memory access."
))

ECOSYSTEMS.append(Ecosystem(
    name="AutoImprovementEcosystem",
    controller_agent="AutoImprovementEcosystemController L2",
    sub_ecosystems=[
        sub_eco("FeedbackSubEcosystem","FeedbackCollectionLeader L3",["OutcomeCollectorAgent L5","PerformanceMetricsAgent L6","PatternDetectorAgent L6","CycleOutcomeAnalyzerAgent L5","OutcomeAnalyzerAgent L5","MetricCaptureMicroAgent L7","PatternCheckMicroAgent L7"], ["FeedbackCollectionTeam"], ["FeedbackRegistry","PerformanceHistory","PatternRegistry"]),
        sub_eco("PlanningSubEcosystem","ImprovementPlanningLeader L3",["ImprovementAnalystAgent L4","PriorityRankerAgent L4","ImprovementPlanWriterAgent L6","OpportunityIdentifierAgent L4"], ["ImprovementPlanningTeam"], ["ImprovementPlans"]),
        sub_eco("ExecutionSubEcosystem","ImprovementExecutionLeader L3",["ParameterAdjusterAgent L5","ThresholdUpdaterAgent L6","WorkflowOptimizerAgent L6","LearningLoggerAgent L5"], ["ImprovementExecutionTeam"], ["LearningLog","important_notes"]),
    ],
    agents_inside=[
        "AutoImprovementEcosystemController L2",
        "FeedbackCollectionLeader L3","OutcomeCollectorAgent L5","PerformanceMetricsAgent L6","PatternDetectorAgent L6","CycleOutcomeAnalyzerAgent L5","OutcomeAnalyzerAgent L5","MetricCaptureMicroAgent L7","PatternCheckMicroAgent L7",
        "ImprovementPlanningLeader L3","ImprovementAnalystAgent L4","PriorityRankerAgent L4","ImprovementPlanWriterAgent L6","OpportunityIdentifierAgent L4",
        "ImprovementExecutionLeader L3","ParameterAdjusterAgent L5","ThresholdUpdaterAgent L6","WorkflowOptimizerAgent L6","LearningLoggerAgent L5"
    ],
    teams_inside=["FeedbackCollectionTeam","ImprovementPlanningTeam","ImprovementExecutionTeam"],
    flows_inside=["AUTO_IMPROVEMENT_FLOW Outcome Collection Performance Analysis Pattern Detection Improvement Planning Improvement Execution Validation - completion at least one measurable improvement applied","MAIN_PRODUCTION_FLOW integrated feedback collection after each cycle CP_FINAL","MEMORY_MAINTENANCE_FLOW PatternRegistry PerformanceHistory reads"],
    memory_components_inside=["FeedbackRegistry","ImprovementPlans","PerformanceHistory","LearningLog","PatternRegistry","important_notes","decisions","AnomalyLog","RecoveryLog"],
    skills_inside=["FeedbackCollectionSkill","ImprovementPlanningSkill","SelfHealingSkill","MemoryReadWriteSkill","CheckpointManagementSkill","AnomalyDetectionSkill"],
    integration_points={
        "AllEcosystems Real Active Continuous Improvement": ["REAL ACTIVE CONTINUOUS IMPROVEMENT ACROSS ENTIRE WORKFLOW - NOT description - system learns from outcomes adjusts future behavior - FeedbackCollectionTeam L3 Leader manages OutcomeCollectorAgent L5 collects outcomes all completed cycles qualification outcomes GO rate NO-GO reasons production speed metrics internal time per phase chapter flagged too slow real vs estimated no invented metrics only internal measurement, PerformanceMetricsAgent L6 calculates metrics per phase 6 feedback signals: qualification outcomes, production speed metrics, book performance signals from Amazon keyword search + review analysis sites signals observed, self-healing activation frequency count per phase, plan validity scores list, memory retrieval patterns what read often gap, PatternDetectorAgent L6 detects recurring patterns positive negative keywords leading too slow GO rate low nicchia Playwright failures frequent time video_structure missing pattern cover revision loop frequent - ImprovementPlanningTeam L3 Leader ImprovementAnalystAgent L4 analyzes feedback identifies improvement opportunities for 5 targets: future research quality, future qualification decisions, future plan accuracy, production flow speed, risk detection sensitivity - PriorityRankerAgent L4 ranks by impact feasibility aligned business goal quantity-performance guadagnare quantita libri performanti - OpportunityIdentifierAgent L4 positive patterns - ImprovementPlanWriterAgent L6 writes prioritized improvement plan targeting - ImprovementExecutionTeam L3 Leader ParameterAdjusterAgent L5 adjusts workflow params keyword strategies batch size retry limits, ThresholdUpdaterAgent L6 updates decision thresholds GO threshold 70 based learning, WorkflowOptimizerAgent L6 optimizes flow sequences based performance data improve handoff validation reduce self-healing triggers fixing root causes - LearningLoggerAgent L5 logs changes LearningLog important_notes per generate_improvement_signal schema mental: source_phase outcome_summary improvement_suggestion derived outcome target next cycle or next similar phase memory_write True - Validation changes not introduce absurd too slow maintain operational clarity concrete precise - At least one measurable improvement applied logged LearningLog memory_write True - Real active continuous improvement"],
        "MemoryEcosystem": ["reads decisions ProductionLog AnomalyLog DiagnosisLog RecoveryLog PerformanceHistory FeedbackRegistry PatternRegistry etc via MemoryReaderAgent L5 - writes FeedbackRegistry ImprovementPlans PerformanceHistory LearningLog PatternRegistry important_notes via MemoryWriterAgent L5 - LearningLog read by ResearchEcosystem KeywordGeneratorAgent ReviewResearchLeader before new cycle adapt keyword strategies - QualificationEcosystem DecisionAggregatorAgent before new qualification adapt thresholds - ResearchEcosystem future research quality improved via ParameterAdjusterAgent - PatternRegistry provides patterns success failure - CheckpointManagerAgent for FeedbackRegistry checkpoints - MemoryValidatorAgent validates FeedbackRegistry ImprovementPlans consistency"],
        "ResearchEcosystem Future Research Quality": ["provides keyword pattern learnings success failure via important_notes LearningLog FeedbackRegistry PatternRegistry to KeywordGeneratorAgent L5 SemanticKeywordExpanderAgent L5 LongTailKeywordAgent L5 - updates future research quality target - example: if qualification scarta 80% too slow nicchia X -> AutoImprovement segnala Research deprioritizza keyword X -> research quality migliorata risk sensitivity aumentata speed"],
        "QualificationEcosystem Future Qualification Decisions": ["updates future qualification decisions thresholds - GO rate low -> adjust weighted scoring or threshold 70 via ThresholdUpdaterAgent - provides GO NO-GO pattern learnings via LearningLog - improves risk detection sensitivity"],
        "PlanningEcosystem Future Plan Accuracy": ["If Planning many rollbacks video_structure missing -> improvement target future plan accuracy -> aggiunta checklist validation F3 -> PlanCoherenceValidatorAgent VideoStructureValidatorAgent enhanced checklist"],
        "ProductionEcosystem Production Flow Speed": ["If Production blocked processes frequent -> WorkflowOptimizerAgent optimizes flow sequences ChapterWriterAgent parallelization ChapterDependencyManagerAgent - improves production flow speed"],
        "SelfHealingEcosystem Risk Detection Sensitivity": ["self-healing activation frequency feedback - high frequency -> improves risk detection sensitivity target - PatternDetector detects self-healing frequent phase -> ImprovementAnalyst suggests improving validator agents - improves risk sensitivity"],
        "SupremeOrchestrator L1": ["reports improvement plans learning logs PerformanceHistory FeedbackRegistry to SupremeOrchestratorAgent L1 - Supreme can adjust global thresholds macro decisions based on learning - GO_rate <20% -> Supreme adjusts BookNicheDecisionSkill thresholds via ThresholdUpdaterAgent + increase retry attempts Research - LearningLog PerformanceHistory read by Supreme for global state"],
        "Skills": ["FeedbackCollectionSkill owner OutcomeCollectorAgent PerformanceMetricsAgent PatternDetectorAgent trigger completion any production cycle CP_FINAL or periodic - execution steps collect outcomes calculate metrics detect patterns output structured feedback - ImprovementPlanningSkill owner ImprovementAnalystAgent PriorityRankerAgent PlanWriter - FeedbackCollectionSkill success at least one outcome collected - ImprovementPlanningSkill success prioritized plan targeting 5 improvement targets"]
    },
    hierarchy_levels_covered=[2,3,4,5,6,7],
    description="Auto-Improvement Ecosystem purpose: Provide real active continuous improvement across entire workflow - learns from outcomes adjusts future behavior - Teams: FeedbackCollectionTeam 7 agents collects outcomes metrics patterns real improvement, ImprovementPlanningTeam 4 agents analyzes feedback ranks priorities writes plans, ImprovementExecutionTeam 4 agents adjusts params updates thresholds optimizes workflows execution reale logs LearningLog. Feedback signals 6: qualification outcomes, production speed metrics internal time, book performance signals Amazon+review sites, self-healing activation frequency, plan validity scores, memory retrieval patterns. Improvement targets 5: future research quality, future qualification decisions, future plan accuracy, production flow speed, risk detection sensitivity. generate_improvement_signal schema source_phase outcome_summary improvement_suggestion target memory_write True."
))

ECOSYSTEMS.append(Ecosystem(
    name="PlaywrightOperationsSubEcosystem",
    controller_agent="ResearchEcosystemController L2",
    sub_ecosystems=[
        sub_eco("NavigationSub","ResearchEcosystemController L2",["PlaywrightNavigatorMicroAgent L7","AmazonPageNavigatorAgent L7","ReviewSiteNavigatorAgent L7","VisualPlaywrightNavigatorAgent L7"],[],["ResearchCheckpoints"]),
        sub_eco("ExtractionSub","DataPersistenceLeader L3",["PlaywrightDataCaptureMicroAgent L7","AmazonDetailExtractorAgent L7","ReviewDataCaptureAgent L7","VisualPlaywrightCaptureAgent L7"],[],["BookOpportunityRegistry","ReviewDataRegistry"]),
        sub_eco("SaveSub","DataPersistenceLeader L3",["PlaywrightSaveAgent L5","VisualPlaywrightSaveAgent L6","SaveOperationMicroAgent L7","VisualSaveMicroAgent L7"],[],["ResearchCheckpoints","GeneratedGraphics","CoverVersions"]),
    ],
    agents_inside=[
        "PlaywrightNavigatorMicroAgent L7","PlaywrightDataCaptureMicroAgent L7","PlaywrightScreenshotMicroAgent L7","PlaywrightErrorHandlerAgent L7 critical self-healing",
        "AmazonPageNavigatorAgent L7","AmazonDetailExtractorAgent L7",
        "ReviewSiteNavigatorAgent L7","ReviewDataCaptureAgent L7",
        "VisualPlaywrightNavigatorAgent L7","VisualPlaywrightCaptureAgent L7",
        "SaveOperationMicroAgent L7","VisualSaveMicroAgent L7"
    ],
    teams_inside=[],
    flows_inside=["PLAYWRIGHT_OPERATIONS_FLOW 5 phases Navigation Data Capture Extraction Screenshot Raw Data Save Results Error Handling Self-Healing - atomic tasks"],
    memory_components_inside=["ResearchCheckpoints","RawData","BookOpportunityRegistry","ReviewDataRegistry","GeneratedGraphics","CoverVersions","AnomalyLog on failure"],
    skills_inside=["PlaywrightNavigationSkill","PlaywrightDataExtractionSkill","PlaywrightSaveSkill","SelfHealingSkill"],
    integration_points={
        "PlaywrightOperationalToolReal": ["Real operational tool instance methods navigate_amazon_keyword_search url https://www.amazon.com/s?k={keyword} - navigate_review_site url site that analyzes Amazon reviews - extract_data url selectors title author ratings prices categories - save_results data destination memory BookOpportunityRegistry ReviewDataRegistry results sources URLs notes - visual_save asset_type asset_data purpose supporting visual team - screenshot url path screenshots - handle_error failed_op error returns handling_strategy action retry escalate adjusted_params timeout_increased user_agent_rotated alternative_selector memory_log_required checkpoint_ref - rotate_user_agent - allowed uses only 4 per PLAYWRIGHT_USAGE_POLICY - forbidden uses any not derivable invented integrations - Integration points ResearchEcosystem VisualEcosystem SelfHealing with PlaywrightErrorHandlerAgent L7 handles timeouts blocked pages CAPTCHAs connection failures retry alternative max 3"],
        "ResearchEcosystem": ["used by AmazonSearchAgent L5 ReviewSiteFinderAgent L5 AmazonDataExtractorAgent L5 ReviewDataExtractorAgent L5 PlaywrightSaveAgent L5 DataFormatterAgent L5 - L7 micro spawned per atomic task per keyword per site - auto-terminated after task - checkpoint before after each micro"],
        "VisualEcosystem": ["shared error handler with VisualPlaywrightOperationsTeam L3 VisualPlaywrightNavigatorAgent L7 VisualPlaywrightSaveAgent L6 - VisualSaveMicroAgent L7 atomic save visual - GraphicGeneratorAgent L5 CoverGeneratorAgent L5 via visual_save - VisualPlaywrightValidatorAgent validates saves - Cover cannot skip must escalate - graphics single non-critical can skip_and_log"],
        "SelfHealing": ["PlaywrightErrorHandlerAgent L7 core self-healing for Playwright with retry 3 max adjusted params timeout increased timeout_ms = 30000 + retry_count*10000 user_agent rotated True if retry>=2 alternative selector True if retry>=2 wait_until networkidle if retry==2 retry_delay 1000*retry_count - PlaywrightFailureDetectorAgent L6 DetectionTeam detects Playwright failures - RetryExecutorAgent L5 executes retry - AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints memory log - handle_failure schema phase error_type checkpoint_restored True action_taken memory_updated True flow_continued True"],
        "MemoryEcosystem": ["CheckpointManagerAgent L6 creates checkpoint before after each Playwright operation - MemoryWriterAgent L5 writes ResearchCheckpoints BookOpportunityRegistry AnomalyLog on failure - MemoryReaderAgent reads important_notes search patterns - RawDataArchiverAgent archives raw_data refs + screenshot refs"]
    },
    hierarchy_levels_covered=[7],
    description="Playwright Operations Sub-Ecosystem purpose: Provide real operational Playwright tool integration as real tool not concept - atomic micro-agents for single navigation single extraction single screenshot single save - error handler with retry alternative strategies - used by ResearchEcosystem and VisualEcosystem per allowed uses - self-healing integration real system - Rule 12 compliance."
))

print(f"ECOSYSTEMS EXPANDED: {len(ECOSYSTEMS)} ecosystems (8 main + 1 sub)")
for eco in ECOSYSTEMS:
    print(f"  {eco.name}: controller={eco.controller_agent}, teams={len(eco.teams_inside)}, agents={len(eco.agents_inside)}, sub_ecos={len(eco.sub_ecosystems)}, memories={len(eco.memory_components_inside)}, skills={len(eco.skills_inside)}, levels={eco.hierarchy_levels_covered}")
