
import sys
sys.path.insert(0, '/home/user/workflow_architecture')
from core import Ecosystem

ProductionEcosystem = Ecosystem(
    name="ProductionEcosystem",
    controller_agent="ProductionEcosystemController L2",
    sub_ecosystems=[{'name': 'WritingSubEcosystem', 'controller': 'BookWritingLeader L3', 'agents': ['ChapterWriterAgent L5', 'ConsistencyCheckerAgent L4', 'StyleEnforcerAgent L4', 'ContentQualityReviewerAgent L4', 'ChapterDependencyManagerAgent L5', 'WritingProgressTrackerAgent L4', 'ProductionLogWriterAgent L5'], 'teams': ['BookWritingTeam'], 'memories': ['ProductionCheckpoints', 'ProductionLog'], 'description': 'Sub-ecosistema WritingSubEcosystem attivo con agenti reali'}, {'name': 'QualitySubEcosystem', 'controller': 'ProductionQualityLeader L3', 'agents': ['ManuscriptValidatorAgent L4', 'PlanComplianceCheckerAgent L4', 'FinalApprovalAgent L6', 'QualityMetricsCalculatorAgent L4', 'ContentValidationAgent L6'], 'teams': ['ProductionQualityTeam'], 'memories': ['CompletedManuscripts', 'ProductionCheckpoints'], 'description': 'Sub-ecosistema QualitySubEcosystem attivo con agenti reali'}, {'name': 'EditingSubEcosystem', 'controller': 'EditingLeader L3', 'agents': ['EditingCoordinatorAgent L5', 'FinalProofreaderAgent L5', 'CrossReferenceCheckerAgent L5'], 'teams': ['EditingTeam'], 'memories': ['EditingLog'], 'description': 'Sub-ecosistema EditingSubEcosystem attivo con agenti reali'}],
    agents_inside=['ProductionEcosystemController L2', 'BookWritingLeader L3', 'ChapterWriterAgent L5 multiple instances', 'ConsistencyCheckerAgent L4', 'StyleEnforcerAgent L4', 'ContentQualityReviewerAgent L4', 'ChapterDependencyManagerAgent L5', 'WritingProgressTrackerAgent L4', 'WritingQualityCheckerAgent L6', 'ProductionLogWriterAgent L5', 'ProductionQualityLeader L3', 'ManuscriptValidatorAgent L4', 'PlanComplianceCheckerAgent L4', 'FinalApprovalAgent L6', 'QualityMetricsCalculatorAgent L4', 'ContentValidationAgent L6', 'EditingLeader L3', 'EditingCoordinatorAgent L5', 'FinalProofreaderAgent L5', 'CrossReferenceCheckerAgent L5'],
    teams_inside=['BookWritingTeam', 'ProductionQualityTeam', 'EditingTeam'],
    flows_inside=['MAIN_PRODUCTION_FLOW Phase 6 Production Write Entire Book + Decision Gate DG3 Production Quality', 'SELF_HEALING_FLOW on blocked process incoherent output memory write failure stall'],
    memory_components_inside=['ProductionCheckpoints', 'ProductionLog', 'CompletedManuscripts', 'EditingLog', 'checkpoints', 'decisions', 'plans', 'important_notes'],
    skills_inside=['BookWritingConsistencySkill', 'StyleEnforcementSkill', 'MemoryReadWriteSkill', 'CheckpointManagementSkill', 'SelfHealingSkill', 'SecondLevelPlanCoherenceSkill'],
    integration_points={'MemoryEcosystem': ['MemoryReaderAgent L5 reads SecondLevelPlans ProductionStartSignals decisions plans checkpoints hierarchies important_notes qualification_plan risk_flags for context continuity - MemoryWriterAgent writes ProductionCheckpoints per chapter critical ProductionLog decisions_made consistency_checks deviations CompletedManuscripts EditingLog - CheckpointManagerAgent creates CP4 per chapter + CP4 final parent CP3 - MemoryValidatorAgent validates completeness - DecisionLoggerAgent logs editing decisions - PlanStorageAgent stores CompletedManuscripts validated approved final'], 'SelfHealing': ['DetectionTeam StallDetectorAgent L7 detects blocked process heart beat missing phase timeout - OutputMonitorAgent L4 detects incoherent output vs second_level_plan - DiagnosisTeam RootCauseAnalyst impact assessment - RecoveryTeam RetryExecutor retry chapter memory read reconnection context - RollbackExecutor rollback last chapter CP4 - AlternativePath requalify partial anomaly flag - RecoveryValidator validates recovery without data loss - AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints important_notes handle_failure schema phase error_type checkpoint_restored True action_taken memory_updated True flow_continued True'], 'Planning incoming': ['receives second_level_plan complete video_structure REQUIRED chapters details production_start_signal TRUE + ProductionStartSignals + CP3 via Memory broker 8 steps validated'], 'Visual outgoing': ['handoff Production->Visual completed manuscript ref path Playwright save + plan reference SecondLevelPlans + production log + EditingLog + CP4 final parent CP3 valid True via Memory broker 8 steps validation required memory logged checkpoint required'], 'BusinessGoal': ['quantity-performance: privilegia libri performanti riproducibili sostenibili non assurdi non troppo lenti da realizzare - production sustainability via ResourceEstimatorAgent + SpeedAnalyst']},
    hierarchy_levels_covered=[2, 3, 4, 5, 6, 7],
    description="""Production Ecosystem purpose: Receive approved second-level plan, write entire book, maintain consistency with previous decisions constraints, read from memory to maintain context continuity. Teams: BookWritingTeam parallel chapter writing, ProductionQualityTeam validation compliance final approval, EditingTeam editing proofreading cross-reference."""
)

print(f"Ecosystem dedicated file ProductionEcosystem - controller {'ProductionEcosystemController L2'} - teams {len(ProductionEcosystem.teams_inside)} - agents {len(ProductionEcosystem.agents_inside)}")
