
import sys
sys.path.insert(0, '/home/user/workflow_architecture')
from core import Ecosystem

QualificationEcosystem = Ecosystem(
    name="QualificationEcosystem",
    controller_agent="QualificationEcosystemController L2",
    sub_ecosystems=[{'name': 'AnalysisSubEcosystem', 'controller': 'QualificationLeader L3', 'agents': ['ReproducibilityAnalystAgent L4', 'AbsurdityDetectorAgent L4', 'ProductionSpeedAnalystAgent L4', 'MarketAlignmentAnalystAgent L4', 'PlanQualityAuditorAgent L4', 'CompetitionAnalystAgent L4', 'SustainabilityAnalystAgent L4', 'BusinessFitAnalystAgent L4'], 'teams': ['QualificationAnalysisTeam'], 'memories': ['QualificationCheckpoints', 'RiskRegistry'], 'description': 'Sub-ecosistema AnalysisSubEcosystem attivo con agenti reali'}, {'name': 'DecisionSubEcosystem', 'controller': 'QualificationDecisionLeader L3', 'agents': ['DecisionAggregatorAgent L4', 'RiskFlagManagerAgent L4', 'QualificationReportWriterAgent L5', 'DecisionQualityCheckerAgent L5'], 'teams': ['QualificationDecisionTeam'], 'memories': ['QualificationDecisions', 'QualificationPlans'], 'description': 'Sub-ecosistema DecisionSubEcosystem attivo con agenti reali'}],
    agents_inside=['QualificationEcosystemController L2', 'QualificationLeader L3', 'ReproducibilityAnalystAgent L4', 'AbsurdityDetectorAgent L4', 'ProductionSpeedAnalystAgent L4', 'MarketAlignmentAnalystAgent L4', 'PlanQualityAuditorAgent L4', 'CompetitionAnalystAgent L4', 'SustainabilityAnalystAgent L4', 'BusinessFitAnalystAgent L4', 'QualificationDecisionLeader L3', 'DecisionAggregatorAgent L4', 'RiskFlagManagerAgent L4', 'QualificationReportWriterAgent L5', 'DecisionQualityCheckerAgent L5'],
    teams_inside=['QualificationAnalysisTeam', 'QualificationDecisionTeam'],
    flows_inside=['MAIN_PRODUCTION_FLOW Phase2 Qualification + Decision Gate DG1 GO NO-GO', 'SELF_HEALING_FLOW on incoherent missing output no-go without alternative failed validation'],
    memory_components_inside=['QualificationCheckpoints', 'QualificationDecisions', 'QualificationPlans', 'RiskRegistry', 'BusinessFitScores', 'checkpoints', 'decisions', 'plans', 'important_notes'],
    skills_inside=['BookNicheDecisionSkill', 'QualificationDecisionSkill', 'SelfHealingSkill', 'AnomalyDetectionSkill', 'RecoveryExecutionSkill', 'SecondLevelPlanCoherenceSkill'],
    integration_points={'MemoryEcosystem': ['MemoryReaderAgent reads BookOpportunityRegistry ReviewDataRegistry ResearchDecisions important_notes FeedbackRegistry LearningLog - MemoryWriterAgent writes QualificationCheckpoints QualificationDecisions QualificationPlans RiskRegistry BusinessFitScores - DecisionLoggerAgent logs GO NO-GO immutable reasoning traceability - PlanStorageAgent stores qualification plans versioned - CheckpointManagerAgent creates CP2 Qualification End per book + batch parent CP1'], 'SelfHealing': ['DetectionTeam monitors missing output incoherent output no-go without alternative failed validation - DiagnosisTeam RootCauseAnalyst ImpactAssessor - RecoveryTeam requalify with anomaly flag rollback CP1 AlternativePath requests new research cycle via ResearchEcosystemController - AnomalyLog DiagnosisLog RecoveryLog'], 'AutoImprovement': ['FeedbackCollectionTeam collects qualification outcomes GO rate NO-GO main reasons - PatternDetector detects GO rate low nicchia - LearningLog important_notes FeedbackRegistry provides learnings - ParameterAdjusterAgent ThresholdUpdaterAgent updates GO threshold 70 based learning - future qualification decisions improved'], 'Research handoff incoming': ['receives handoff Research->Qualification validated structured_output BookOpportunityRegistry ReviewDataRegistry CP1 via Memory broker 8 steps validation - if all NO-GO without alternative trigger new research cycle via AlternativePathAgent'], 'Planning handoff outgoing': ['handoff Qualification->Planning only GO decisions via Memory broker: GO decision + qualification report + risk_flags + QualificationDecisions + QualificationPlans + CP2 - protocol 8 steps validation required checkpoint memory logged self-healing - only GO advances NO-GO archived archived + new research request'], 'Skills': ['BookNicheDecisionSkill owner AmazonResearchLeader ReviewResearchLeader QualificationLeader MarketAlignmentAnalystAgent trigger enough data execution steps aggregate market demand competition reproducibility rank flag absurd too slow output ranked list motivation success at least one viable - QualificationDecisionSkill owner QualificationLeader DecisionAggregatorAgent trigger all analysts completated execution steps collect scores weighted reproducibility 30% speed 25% absurdity 20% market 25% threshold 70 GO NO-GO']},
    hierarchy_levels_covered=[2, 3, 4, 5, 6],
    description="""Qualification Ecosystem purpose: Receive research output, create detailed qualification plan, evaluate every book opportunity against strict criteria reproducibility absurdity speed market fit plan validity, determine if book can be reproduced, determine if absurd unrealistic too slow, evaluate qualification plan itself, output clear go/no-go decisions. Business goal quantity-performance: performanti riproducibili sostenibili non assurdi non lenti."""
)

print(f"Ecosystem dedicated file QualificationEcosystem - controller {'QualificationEcosystemController L2'} - teams {len(QualificationEcosystem.teams_inside)} - agents {len(QualificationEcosystem.agents_inside)}")
