
import sys
sys.path.insert(0, '/home/user/workflow_architecture')
from core import Ecosystem

VisualEcosystem = Ecosystem(
    name="VisualEcosystem",
    controller_agent="VisualEcosystemController L2",
    sub_ecosystems=[{'name': 'GraphicSubEcosystem', 'controller': 'GraphicDesignLeader L3', 'agents': ['GraphicPromptCreatorAgent L5', 'GraphicGeneratorAgent L5', 'GraphicQualityReviewerAgent L6', 'GraphicRevisionAgent L6', 'GraphicStyleEnforcerAgent L5', 'VisualConsistencyCheckerAgent L4', 'GraphicPromptMicroAgent L7'], 'teams': ['GraphicDesignTeam'], 'memories': ['GraphicPrompts', 'GeneratedGraphics'], 'description': 'Sub-ecosistema GraphicSubEcosystem attivo con agenti reali'}, {'name': 'CoverSubEcosystem', 'controller': 'CoverDesignLeader L3', 'agents': ['CoverConceptAgent L4', 'CoverPromptCreatorAgent L5', 'CoverGeneratorAgent L5', 'CoverQualityReviewerAgent L6', 'CoverRevisionAgent L6', 'CoverMarketFitAnalystAgent L4', 'CoverPromptMicroAgent L7'], 'teams': ['CoverDesignTeam'], 'memories': ['CoverVersions'], 'description': 'Sub-ecosistema CoverSubEcosystem attivo con agenti reali'}, {'name': 'VisualPlaywrightSubEcosystem', 'controller': 'VisualPlaywrightLeader L3', 'agents': ['VisualPlaywrightNavigatorAgent L7', 'VisualPlaywrightSaveAgent L6', 'VisualPlaywrightValidatorAgent L6', 'VisualPlaywrightCaptureAgent L7', 'VisualSaveMicroAgent L7'], 'teams': ['VisualPlaywrightOperationsTeam'], 'memories': ['GeneratedGraphics', 'CoverVersions'], 'description': 'Sub-ecosistema VisualPlaywrightSubEcosystem attivo con agenti reali'}, {'name': 'VisualQualitySubEcosystem', 'controller': 'VisualQualityLeader L3', 'agents': ['VisualQualityAuditorAgent L4', 'FinalVisualApprovalAgent L6'], 'teams': ['VisualQualityTeam'], 'memories': ['VisualProductionLog', 'VisualQualityLog'], 'description': 'Sub-ecosistema VisualQualitySubEcosystem attivo con agenti reali'}],
    agents_inside=['VisualEcosystemController L2', 'GraphicDesignLeader L3', 'GraphicPromptCreatorAgent L5', 'GraphicGeneratorAgent L5', 'GraphicQualityReviewerAgent L6', 'GraphicRevisionAgent L6', 'GraphicStyleEnforcerAgent L5', 'VisualConsistencyCheckerAgent L4', 'GraphicPromptMicroAgent L7', 'CoverDesignLeader L3', 'CoverConceptAgent L4', 'CoverPromptCreatorAgent L5', 'CoverGeneratorAgent L5', 'CoverQualityReviewerAgent L6', 'CoverRevisionAgent L6', 'CoverMarketFitAnalystAgent L4', 'CoverPromptMicroAgent L7', 'VisualPlaywrightLeader L3', 'VisualPlaywrightNavigatorAgent L7', 'VisualPlaywrightSaveAgent L6', 'VisualPlaywrightValidatorAgent L6', 'VisualPlaywrightCaptureAgent L7', 'VisualSaveMicroAgent L7', 'VisualQualityLeader L3', 'VisualQualityAuditorAgent L4', 'FinalVisualApprovalAgent L6'],
    teams_inside=['GraphicDesignTeam', 'CoverDesignTeam', 'VisualPlaywrightOperationsTeam', 'VisualQualityTeam'],
    flows_inside=['MAIN_PRODUCTION_FLOW Phase 7 Visual Graphics Prompts Cover via Playwright Support + Decision Gate DG4 Visual Quality + PLAYWRIGHT_OPERATIONS_FLOW visual_save', 'SELF_HEALING_FLOW on Playwright failure missing output cover missing'],
    memory_components_inside=['GraphicPrompts', 'GeneratedGraphics', 'CoverVersions', 'VisualProductionLog', 'VisualQualityLog', 'checkpoints'],
    skills_inside=['GraphicPromptEngineeringSkill', 'CoverConceptDesignSkill', 'PlaywrightNavigationSkill', 'PlaywrightSaveSkill', 'SelfHealingSkill', 'RecoveryExecutionSkill'],
    integration_points={'MemoryEcosystem': ['MemoryReaderAgent reads CompletedManuscripts SecondLevelPlans chapters production_log EditingLog details graphic_needs - MemoryWriterAgent writes GraphicPrompts GeneratedGraphics CoverVersions VisualProductionLog VisualQualityLog - CheckpointManagerAgent creates CP5 Visual End + CP_FINAL parent CP4 final valid True global - MemoryValidatorAgent validates graphics approved prompts tracciati cover final approved saved via Playwright confirmed - PlanStorageAgent stores CoverVersions versions'], 'SelfHealing': ['DetectionTeam OutputMonitor detects missing output cover missing graphics missing prompts not tracciati - PlaywrightFailureDetector detects Playwright failure save visual - DiagnosisTeam RootCause Playwright failure - RecoveryTeam RetryExecutor retry PlaywrightErrorHandlerAgent adjusted params timeout++ user_agent rotate - RollbackExecutor rollback CP4 if needed - AlternativePath skip_and_log single graphic non-critical log continua where possible - cover critical cannot skip_and_log must escalate flag anomaly pause branch log important_notes EscaltionManager escalate to VisualEcosystemController then Supreme - RecoveryValidator validates without data loss - AnomalyLog DiagnosisLog RecoveryLog'], 'Production incoming': ['receives completed manuscript ref + plan ref + production log + CP4 final parent CP3 via Memory broker 8 steps validated - handoff Production->Visual'], 'PlaywrightToolReal': ['PlaywrightOperationalToolReal visual_save support visual creation saving processes allowed use #4 - VisualPlaywrightNavigatorAgent L7 navigation real tool - VisualPlaywrightSaveAgent L6 save_results visual_save destination memory GeneratedGraphics CoverVersions save confirmation via VisualPlaywrightValidatorAgent L6 validation - PlaywrightErrorHandlerAgent L7 handles failures retry 2x skip_and_log non-critical graphic escalate cover critical - MICRO agents GraphicPromptMicroAgent CoverPromptMicroAgent VisualSaveMicroAgent atomic single prompt single save'], 'FinalAssembly': ['outputs all graphics approved refs via Playwright visual_save + graphic_prompts all prompts tracciati GraphicPrompts + cover final approved CoverVersions critical + VisualProductionLog VisualQualityLog + CP5 CP_FINAL + final package ready for Amazon - Decision Gate DG4 visual quality graphics approved or skipped non-critical logged prompts tracciati cover final approved Playwright saves confirmed visual consistency quality audit final approval'], 'FinalValidation': ['Validation: complete_book not partial coherence with second_level_plan chapters respected video_structure considered per VideoStructureControlPoints no absurd flagged RiskRegistry cover present final approved not missing graphic_prompts tracciati graphics saved via Playwright confirmed VisualPlaywrightValidatorAgent memory_write complete all categories CP_FINAL exists valid parent chain']},
    hierarchy_levels_covered=[2, 3, 4, 5, 6, 7],
    description="""Visual Ecosystem purpose: Create all graphics, create all prompts for graphics generation, create book cover, use Playwright where needed real operational tool support visual creation saving. Teams: GraphicDesignTeam prompt creation generation quality review revision loop, CoverDesignTeam concept prompt generation quality critical cannot skip, VisualPlaywrightOperationsTeam navigation save via Playwright, VisualQualityTeam quality audit final approval."""
)

print(f"Ecosystem dedicated file VisualEcosystem - controller {'VisualEcosystemController L2'} - teams {len(VisualEcosystem.teams_inside)} - agents {len(VisualEcosystem.agents_inside)}")
