
import sys
sys.path.insert(0, '/home/user/workflow_architecture')
from core import Ecosystem

PlanningEcosystem = Ecosystem(
    name="PlanningEcosystem",
    controller_agent="PlanningEcosystemController L2",
    sub_ecosystems=[{'name': 'StructureSubEcosystem', 'controller': 'StructurePlanningLeader L3', 'agents': ['VideoStructureArchitectAgent L4', 'ChapterDesignerAgent L4', 'DetailFillerAgent L4', 'PlanCoherenceValidatorAgent L4', 'VideoStructureValidatorAgent L4', 'OutlineOptimizerAgent L4'], 'teams': ['StructurePlanningTeam'], 'memories': ['SecondLevelPlans', 'VideoStructureControlPoints'], 'description': 'Sub-ecosistema StructureSubEcosystem attivo con agenti reali'}, {'name': 'ReadinessSubEcosystem', 'controller': 'ProductionReadinessLeader L3', 'agents': ['ReadinessCheckerAgent L5', 'ResourceEstimatorAgent L5', 'ProductionStartSignalAgent L5', 'RiskMitigationPlannerAgent L5'], 'teams': ['ProductionReadinessTeam'], 'memories': ['ProductionStartSignals', 'PlanningCheckpoints'], 'description': 'Sub-ecosistema ReadinessSubEcosystem attivo con agenti reali'}, {'name': 'ContentSubEcosystem', 'controller': 'ContentPlanningLeader L3', 'agents': ['ContentDetailArchitectAgent L5', 'ContentFlowDesignerAgent L5', 'ResourceAllocationPlannerAgent L5'], 'teams': ['ContentPlanningTeam'], 'memories': ['SecondLevelPlans details enriched'], 'description': 'Sub-ecosistema ContentSubEcosystem attivo con agenti reali'}],
    agents_inside=['PlanningEcosystemController L2', 'StructurePlanningLeader L3', 'VideoStructureArchitectAgent L4 CRITICAL', 'ChapterDesignerAgent L4', 'DetailFillerAgent L4', 'PlanCoherenceValidatorAgent L4', 'VideoStructureValidatorAgent L4', 'OutlineOptimizerAgent L4', 'ProductionReadinessLeader L3', 'ReadinessCheckerAgent L5', 'ResourceEstimatorAgent L5', 'ProductionStartSignalAgent L5', 'RiskMitigationPlannerAgent L5', 'ContentPlanningLeader L3', 'ContentDetailArchitectAgent L5', 'ContentFlowDesignerAgent L5', 'ResourceAllocationPlannerAgent L5', 'ContentDetailArchitectAgent2 L5'],
    teams_inside=['StructurePlanningTeam', 'ProductionReadinessTeam', 'ContentPlanningTeam'],
    flows_inside=['MAIN_PRODUCTION_FLOW Phase 3-5 Planning + Decision Gate DG2 Plan Approval + Control Point CP-VIDEO-01', 'SELF_HEALING_FLOW on missing video_structure CRITICAL incoherent output failed validation'],
    memory_components_inside=['PlanningCheckpoints', 'SecondLevelPlans', 'ProductionStartSignals', 'VideoStructureControlPoints', 'checkpoints', 'decisions', 'plans', 'important_notes'],
    skills_inside=['VideoStructureDesignSkill', 'ChapterDesignSkill', 'SecondLevelPlanCoherenceSkill', 'ProductionReadinessSkill', 'SelfHealingSkill', 'CheckpointManagementSkill', 'AnomalyDetectionSkill'],
    integration_points={'MemoryEcosystem': ['MemoryReaderAgent reads QualificationDecisions RiskRegistry plans decisions QualificationPlans - MemoryWriterAgent writes PlanningCheckpoints SecondLevelPlans ProductionStartSignals VideoStructureControlPoints - PlanStorageAgent stores second-level plans versioned not overwritten - DecisionLoggerAgent logs production_start_signal TRUE timestamp validated_by - CheckpointManagerAgent creates CP3 Planning End critical production start parent CP2 - MemoryValidatorAgent validates video_structure present verbatim chapters non-empty details concrete'], 'SelfHealing': ['DetectionTeam OutputMonitor detects missing video_structure REQUIRED critical field missing -> AnomalyLog severity critical - DiagnosisTeam RootCauseAnalyst video_structure missing - ImpactAssessor impact all production blocked - RecoveryPlanner recovery plan retry forced read original requirement handle_ambiguity preserve_and_encapsulate - RecoveryTeam RetryExecutor retry with forced read original requirement handle_ambiguity preserve_and_encapsulate create validation checkpoint forbidden fill_with_assumptions - RollbackExecutor rollback CP2 - AlternativePath requalify - EscalationManager escalate to Supreme if 3 fails - RecoveryValidator validates'], 'Qualification incoming': ['receives GO package QualificationDecisions QualificationPlans RiskRegistry CP2 via Memory broker validated'], 'Production outgoing': ['handoff Planning->Production second_level_plan complete {video_structure REQUIRED preserved verbatim explicit control point CP-VIDEO-01 handle_ambiguity preserve_and_encapsulate + chapters list title description order purpose estimated_effort fast sustainable slow + details every relevant production detail concrete not vague production_constraints style_notes business_alignment_notes graphic_needs sustainability_check + production_start_signal TRUE timestamp validated_by ProductionReadinessLeader} + Content enriched + ProductionStartSignals + CP3 parent CP2 valid True - protocol 8 steps - marks actual start production flow per requirements - Decision Gate DG2 video_structure present verbatim non-empty non-reinterpreted chapters non-empty details concrete production_start_signal TRUE coherence validation passed'], 'CriticalControlPoint': ['CP-VIDEO-01 video_structure REQUIRED preserved verbatim - original requirement do not remove reinterpret ignore - handle_ambiguity original_requirement ambiguity_detected True action preserve_and_encapsulate resolution_method create_validation_checkpoint forbidden_action fill_with_assumptions output explicit_control_point_in_workflow - VideoStructureArchitectAgent L4 CRITICAL designs video_structure - VideoStructureValidatorAgent L4 validates present verbatim - Control point explicit in second level plan - Self-healing critical failure if missing']},
    hierarchy_levels_covered=[2, 3, 4, 5, 6],
    description="""Planning Ecosystem purpose: Receive qualified book opportunities GO, create second-level operational plan, define video structure REQUIRED original requirement do not remove reinterpret, define chapters every detail, mark actual start production. Critical: video_structure control point."""
)

print(f"Ecosystem dedicated file PlanningEcosystem - controller {'PlanningEcosystemController L2'} - teams {len(PlanningEcosystem.teams_inside)} - agents {len(PlanningEcosystem.agents_inside)}")
