
import sys
sys.path.insert(0, '/home/user/workflow_architecture')
from core import Ecosystem

PlaywrightOperationsSubEcosystem = Ecosystem(
    name="PlaywrightOperationsSubEcosystem",
    controller_agent="ResearchEcosystemController L2",
    sub_ecosystems=[{'name': 'NavigationSub', 'controller': 'ResearchEcosystemController L2', 'agents': ['PlaywrightNavigatorMicroAgent L7', 'AmazonPageNavigatorAgent L7', 'ReviewSiteNavigatorAgent L7', 'VisualPlaywrightNavigatorAgent L7'], 'teams': [], 'memories': ['ResearchCheckpoints'], 'description': 'Sub-ecosistema NavigationSub attivo con agenti reali'}, {'name': 'ExtractionSub', 'controller': 'DataPersistenceLeader L3', 'agents': ['PlaywrightDataCaptureMicroAgent L7', 'AmazonDetailExtractorAgent L7', 'ReviewDataCaptureAgent L7', 'VisualPlaywrightCaptureAgent L7'], 'teams': [], 'memories': ['BookOpportunityRegistry', 'ReviewDataRegistry'], 'description': 'Sub-ecosistema ExtractionSub attivo con agenti reali'}, {'name': 'SaveSub', 'controller': 'DataPersistenceLeader L3', 'agents': ['PlaywrightSaveAgent L5', 'VisualPlaywrightSaveAgent L6', 'SaveOperationMicroAgent L7', 'VisualSaveMicroAgent L7'], 'teams': [], 'memories': ['ResearchCheckpoints', 'GeneratedGraphics', 'CoverVersions'], 'description': 'Sub-ecosistema SaveSub attivo con agenti reali'}],
    agents_inside=['PlaywrightNavigatorMicroAgent L7', 'PlaywrightDataCaptureMicroAgent L7', 'PlaywrightScreenshotMicroAgent L7', 'PlaywrightErrorHandlerAgent L7 critical self-healing', 'AmazonPageNavigatorAgent L7', 'AmazonDetailExtractorAgent L7', 'ReviewSiteNavigatorAgent L7', 'ReviewDataCaptureAgent L7', 'VisualPlaywrightNavigatorAgent L7', 'VisualPlaywrightCaptureAgent L7', 'SaveOperationMicroAgent L7', 'VisualSaveMicroAgent L7'],
    teams_inside=[],
    flows_inside=['PLAYWRIGHT_OPERATIONS_FLOW 5 phases Navigation Data Capture Extraction Screenshot Raw Data Save Results Error Handling Self-Healing - atomic tasks'],
    memory_components_inside=['ResearchCheckpoints', 'RawData', 'BookOpportunityRegistry', 'ReviewDataRegistry', 'GeneratedGraphics', 'CoverVersions', 'AnomalyLog on failure'],
    skills_inside=['PlaywrightNavigationSkill', 'PlaywrightDataExtractionSkill', 'PlaywrightSaveSkill', 'SelfHealingSkill'],
    integration_points={'PlaywrightOperationalToolReal': ['Real operational tool instance methods navigate_amazon_keyword_search url https://www.amazon.com/s?k={keyword} - navigate_review_site url site that analyzes Amazon reviews - extract_data url selectors title author ratings prices categories - save_results data destination memory BookOpportunityRegistry ReviewDataRegistry results sources URLs notes - visual_save asset_type asset_data purpose supporting visual team - screenshot url path screenshots - handle_error failed_op error returns handling_strategy action retry escalate adjusted_params timeout_increased user_agent_rotated alternative_selector memory_log_required checkpoint_ref - rotate_user_agent - allowed uses only 4 per PLAYWRIGHT_USAGE_POLICY - forbidden uses any not derivable invented integrations - Integration points ResearchEcosystem VisualEcosystem SelfHealing with PlaywrightErrorHandlerAgent L7 handles timeouts blocked pages CAPTCHAs connection failures retry alternative max 3'], 'ResearchEcosystem': ['used by AmazonSearchAgent L5 ReviewSiteFinderAgent L5 AmazonDataExtractorAgent L5 ReviewDataExtractorAgent L5 PlaywrightSaveAgent L5 DataFormatterAgent L5 - L7 micro spawned per atomic task per keyword per site - auto-terminated after task - checkpoint before after each micro'], 'VisualEcosystem': ['shared error handler with VisualPlaywrightOperationsTeam L3 VisualPlaywrightNavigatorAgent L7 VisualPlaywrightSaveAgent L6 - VisualSaveMicroAgent L7 atomic save visual - GraphicGeneratorAgent L5 CoverGeneratorAgent L5 via visual_save - VisualPlaywrightValidatorAgent validates saves - Cover cannot skip must escalate - graphics single non-critical can skip_and_log'], 'SelfHealing': ['PlaywrightErrorHandlerAgent L7 core self-healing for Playwright with retry 3 max adjusted params timeout increased timeout_ms = 30000 + retry_count*10000 user_agent rotated True if retry>=2 alternative selector True if retry>=2 wait_until networkidle if retry==2 retry_delay 1000*retry_count - PlaywrightFailureDetectorAgent L6 DetectionTeam detects Playwright failures - RetryExecutorAgent L5 executes retry - AnomalyLog DiagnosisLog RecoveryLog SelfHealingCheckpoints memory log - handle_failure schema phase error_type checkpoint_restored True action_taken memory_updated True flow_continued True'], 'MemoryEcosystem': ['CheckpointManagerAgent L6 creates checkpoint before after each Playwright operation - MemoryWriterAgent L5 writes ResearchCheckpoints BookOpportunityRegistry AnomalyLog on failure - MemoryReaderAgent reads important_notes search patterns - RawDataArchiverAgent archives raw_data refs + screenshot refs']},
    hierarchy_levels_covered=[7],
    description="""Playwright Operations Sub-Ecosystem purpose: Provide real operational Playwright tool integration as real tool not concept - atomic micro-agents for single navigation single extraction single screenshot single save - error handler with retry alternative strategies - used by ResearchEcosystem and VisualEcosystem per allowed uses - self-healing integration real system - Rule 12 compliance."""
)

print(f"Ecosystem dedicated file PlaywrightOperationsSubEcosystem - controller {'ResearchEcosystemController L2'} - teams {len(PlaywrightOperationsSubEcosystem.teams_inside)} - agents {len(PlaywrightOperationsSubEcosystem.agents_inside)}")
