#!/usr/bin/env python3
"""
Strategy Manifest Generator — Tool per agenti del Strategy Department (Step 4)

Uso:
  python generate_strategy_manifest.py --input-type "youtube" --focus "design" --duration "120min" --output "manifest.json"

Genera automaticamente il Strategy Manifest basandosi su STRATEGY-REGISTRY e regole.

Questo script è usato da:
- Strategy Coordinator (per creare il manifest)
- Strategy Controller (per validare)
- Strategy Improver (per analizzare)

Output: JSON + markdown summary salvato in memory/strategy-applications/
"""

import argparse
import json
import datetime
from pathlib import Path

def get_timestamp():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def generate_manifest(input_type: str, focus: str, duration: str = "", run_id: str = "") -> dict:
    """Logica semplice di selezione strategie (da espandere con registry reale)."""
    
    manifest = {
        "run_id": run_id or f"run-{get_timestamp().replace(' ', 'T')}",
        "timestamp": get_timestamp(),
        "input": {
            "type": input_type,
            "focus": focus,
            "duration": duration
        },
        "selected_strategies": {},
        "rules": [],
        "wiki_style": "",
        "rationale": "",
        "trace": "generated by generate_strategy_manifest.py"
    }

    # Selezione base (da espandere con Strategy Registry completo)
    if "youtube" in input_type.lower():
        manifest["selected_strategies"]["department"] = "YouTube Department Strategy v1.0"
        manifest["rules"].append("frame ogni capitolo + mid points")
        
        if "design" in focus.lower() or "system" in focus.lower():
            manifest["selected_strategies"]["content_type"] = "YouTube + Design System Strategy v1.1"
            manifest["rules"].extend([
                "frame su export/component creation",
                "descrizioni visive dettagliate >60 parole",
                "trace frame per ogni atomo chiave"
            ])
            manifest["wiki_style"] = "Visual-Heavy Reference + Update-Proposal Integrated"
            manifest["rationale"] = "Video lungo YouTube su design system → frame densi + visual depth + update proposal"
        else:
            manifest["selected_strategies"]["content_type"] = "Marketing Content Strategy"
            manifest["wiki_style"] = "Playbook Style"
            manifest["rationale"] = "YouTube marketing content"

    elif "tiktok" in input_type.lower():
        manifest["selected_strategies"]["department"] = "TikTok Department Strategy v1.0"
        manifest["selected_strategies"]["content_type"] = "Automazioni Content Strategy"
        manifest["wiki_style"] = "Quick-Reference"
        manifest["rules"] = ["frame densi ogni 5-10s", "focus su hook visivi e tool output"]
        manifest["rationale"] = "TikTok breve → micro-passaggi e quick wins"

    else:
        manifest["selected_strategies"]["department"] = "Web Department Strategy v1.0"
        manifest["wiki_style"] = "Reference / Knowledge Base"
        manifest["rationale"] = "Web content"

    # Aggiungi sempre update proposal se rilevante
    if "design" in focus.lower() or "automation" in focus.lower() or "skill" in focus.lower():
        manifest["rules"].append("genera update proposals per workflow esistenti")

    return manifest

def main():
    parser = argparse.ArgumentParser(description="Genera Strategy Manifest per Strategy Department")
    parser.add_argument("--input-type", required=True, help="youtube / tiktok / web")
    parser.add_argument("--focus", required=True, help="design, marketing, automation, etc.")
    parser.add_argument("--duration", default="", help="es. 120min")
    parser.add_argument("--output", default="strategy-manifest.json")
    parser.add_argument("--run-id", default="")
    args = parser.parse_args()

    manifest = generate_manifest(args.input_type, args.focus, args.duration, args.run_id)
    
    output_path = Path(args.output)
    with open(output_path, "w") as f:
        json.dump(manifest, f, indent=2)
    
    # Anche versione markdown per leggibilità
    md_path = output_path.with_suffix(".md")
    with open(md_path, "w") as f:
        f.write(f"# Strategy Manifest\n\n**Run:** {manifest['run_id']}\n**Timestamp:** {manifest['timestamp']}\n\n")
        f.write(f"**Input:** {manifest['input']}\n\n")
        f.write("**Strategie Selezionate:**\n")
        for k, v in manifest["selected_strategies"].items():
            f.write(f"- {k}: {v}\n")
        f.write("\n**Regole da rispettare:**\n")
        for rule in manifest["rules"]:
            f.write(f"- {rule}\n")
        f.write(f"\n**Wiki Style:** {manifest['wiki_style']}\n")
        f.write(f"\n**Rationale:** {manifest['rationale']}\n")
        f.write(f"\n**Trace:** {manifest['trace']}\n")

    print(f"Manifest generato: {output_path}")
    print(f"Markdown: {md_path}")
    print("Ricorda: salva anche in memory/strategy-applications/ e fai CP/DEC.")

if __name__ == "__main__":
    main()
