"""
glossary_de_it.py — Glossario automotive DE→IT (Half B / Gael, S3).

Fonte di verità per la traduzione deterministica di optional/dotazioni (`equipment_de`)
e per il rilevamento di residui tedeschi (usato in modo INDIPENDENTE anche da qa_gate.py).

Due tabelle:
- PHRASES: frasi/termini composti (match prioritario, case-insensitive, più lungo prima).
- WORDS:   singole parole (fallback token-per-token).

Estendere liberamente: ogni voce aggiunta migliora la copertura di Gate B.
Il seed copre i termini più frequenti negli annunci mobile.de.
"""
from __future__ import annotations

import re

# --------------------------------------------------------------------------- #
# Frasi / termini composti (match prima delle singole parole). Chiavi lowercase.
# --------------------------------------------------------------------------- #
PHRASES: dict[str, str] = {
    # seed dell'handoff
    "anhängerkupplung (ahk)": "gancio traino",
    "anhängerkupplung schwenkbar": "gancio traino estraibile",
    "anhängerkupplung abnehmbar": "gancio traino removibile",
    "led-scheinwerfer": "fari LED",
    "led scheinwerfer": "fari LED",
    "led-tagfahrlicht": "luci diurne LED",
    "voll-led-scheinwerfer": "fari full LED",
    "xenon-scheinwerfer": "fari allo xeno",
    "xenonscheinwerfer": "fari allo xeno",
    "bi-xenon": "bi-xeno",
    "bi-xenon-scheinwerfer": "fari bi-xeno",
    "bixenon-scheinwerfer": "fari bi-xeno",
    "kurvenlicht": "fari adattivi in curva",
    "nebelscheinwerfer": "fendinebbia",
    "navigationssystem": "navigatore",
    "navigationsvorbereitung": "predisposizione navigatore",
    "klimaautomatik": "climatizzatore automatico",
    "2-zonen-klimaautomatik": "climatizzatore automatico bizona",
    "3-zonen-klimaautomatik": "climatizzatore automatico trizona",
    "4-zonen-klimaautomatik": "climatizzatore automatico quadrizona",
    "sitzheizung": "sedili riscaldati",
    "sitzheizung vorn": "sedili anteriori riscaldati",
    "sitzheizung hinten": "sedili posteriori riscaldati",
    "elektrische sitzeinstellung mit memory-funktion": "regolazione elettrica dei sedili con memoria",
    "elektrische sitzeinstellung mit memory": "regolazione elettrica dei sedili con memoria",
    "elektrische sitzeinstellung": "regolazione elettrica dei sedili",
    "sitzeinstellung mit memory": "regolazione sedili con memoria",
    "sitzeinstellung elektrisch": "regolazione elettrica dei sedili",
    "sitzeinstellung": "regolazione sedili",
    "sitzverstellung": "regolazione sedili",
    "sitzbelüftung": "sedili ventilati",
    "lenkradheizung": "volante riscaldato",
    "standheizung": "riscaldamento autonomo",
    "rückfahrkamera": "telecamera posteriore",
    "360°-kamera": "telecamera a 360°",
    "360-kamera": "telecamera a 360°",
    "einparkhilfe": "sensori di parcheggio",
    "einparkhilfe vorne": "sensori di parcheggio anteriori",
    "einparkhilfe hinten": "sensori di parcheggio posteriori",
    "einparkhilfe vorne+hinten": "sensori di parcheggio ant.+post.",
    "park distance control": "sensori di parcheggio",
    "parklenkassistent": "assistente al parcheggio",
    "panoramadach": "tetto panoramico",
    "panorama-schiebedach": "tetto panoramico apribile",
    "schiebedach": "tetto apribile",
    "elektrisches schiebedach": "tetto apribile elettrico",
    "tempomat": "cruise control",
    "adaptiver tempomat": "cruise control adattivo",
    "abstandstempomat": "cruise control adattivo",
    "geschwindigkeitsregelanlage": "regolatore di velocità",
    "geschwindigkeitsbegrenzer": "limitatore di velocità",
    "lederausstattung": "interni in pelle",
    "teillederausstattung": "interni in pelle e tessuto",
    "kunstleder": "interni in similpelle",
    "alcantara": "interni in alcantara",
    "stoffausstattung": "interni in tessuto",
    "sportsitze": "sedili sportivi",
    "elektrische sitze": "sedili elettrici",
    "elektrisch verstellbare sitze": "sedili regolabili elettricamente",
    "memory-sitze": "sedili con memoria",
    "memory-paket": "pacchetto memoria",
    "beheizbares lenkrad": "volante riscaldato",
    "multifunktionslenkrad": "volante multifunzione",
    "lederlenkrad": "volante in pelle",
    "head-up-display": "head-up display",
    "digitales cockpit": "quadro strumenti digitale",
    "virtual cockpit": "quadro strumenti digitale",
    "schlüssellose zentralverriegelung": "chiusura centralizzata senza chiave",
    "schlüsselloser zugang": "accesso senza chiave",
    "keyless go": "accesso e avviamento senza chiave",
    "keyless-go": "accesso e avviamento senza chiave",
    "zentralverriegelung": "chiusura centralizzata",
    "elektrische fensterheber": "alzacristalli elettrici",
    "elektr. fensterheber": "alzacristalli elettrici",
    "elektrische heckklappe": "portellone elettrico",
    "elektr. heckklappe": "portellone elettrico",
    "elektrisch anklappbare außenspiegel": "specchietti ripiegabili elettricamente",
    "beheizbare außenspiegel": "specchietti riscaldati",
    "abstandswarner": "avviso distanza di sicurezza",
    "spurhalteassistent": "assistente mantenimento corsia",
    "spurwechselassistent": "assistente cambio corsia",
    "totwinkelassistent": "assistente angolo cieco",
    "notbremsassistent": "assistente frenata di emergenza",
    "verkehrszeichenerkennung": "riconoscimento segnali stradali",
    "müdigkeitswarner": "rilevatore di stanchezza",
    "berganfahrassistent": "assistente partenza in salita",
    "regensensor": "sensore pioggia",
    "lichtsensor": "sensore luci",
    "start-stopp-automatik": "sistema start&stop",
    "start/stopp-automatik": "sistema start&stop",
    "schaltwippen": "palette al volante",
    "sportfahrwerk": "assetto sportivo",
    "luftfederung": "sospensioni pneumatiche",
    "adaptives fahrwerk": "assetto adattivo",
    "elektrische servolenkung": "servosterzo elettrico",
    "servolenkung": "servosterzo",
    "leichtmetallfelgen": "cerchi in lega",
    "alufelgen": "cerchi in lega",
    "winterreifen": "pneumatici invernali",
    "sommerreifen": "pneumatici estivi",
    "allwetterreifen": "pneumatici quattro stagioni",
    "freisprecheinrichtung": "vivavoce",
    "bluetooth-schnittstelle": "interfaccia Bluetooth",
    "apple carplay": "Apple CarPlay",
    "android auto": "Android Auto",
    "dab-radio": "radio DAB",
    "soundsystem": "impianto audio premium",
    "isofix": "attacchi Isofix",
    "nichtraucherfahrzeug": "veicolo non fumatori",
    "nichtraucher-fahrzeug": "veicolo non fumatori",
    "nichtraucher": "non fumatori",
    "scheckheftgepflegt": "tagliandi regolari certificati",
    "garantie": "garanzia",
    "gebrauchtwagengarantie": "garanzia auto usata",
    "unfallfrei": "non incidentata",
    "erste hand": "primo proprietario",
    "zweite hand": "secondo proprietario",
    "metallic-lackierung": "vernice metallizzata",
    "metallic": "metallizzato",
    "tagfahrlicht": "luci diurne",
    "abstandsregeltempomat": "cruise control adattivo",
    "innenraumfilter": "filtro abitacolo",
    "raucherpaket": "pacchetto fumatori",
    "winterpaket": "pacchetto invernale",
    "sportpaket": "pacchetto sportivo",
    "komfortpaket": "pacchetto comfort",
    "assistenzpaket": "pacchetto assistenza alla guida",
    # --- estensione copertura reale mobile.de ---
    "ambiente-beleuchtung": "illuminazione d'ambiente",
    "ambientebeleuchtung": "illuminazione d'ambiente",
    "ambiente beleuchtung": "illuminazione d'ambiente",
    "led-ambientebeleuchtung": "illuminazione d'ambiente a LED",
    "fernlichtassistent": "assistente abbaglianti",
    "adaptiver fernlichtassistent": "assistente abbaglianti adattivo",
    "lordosenstütze": "supporto lombare",
    "lordosenstuetze": "supporto lombare",
    "panorama-dach": "tetto panoramico",
    "panorama-glasdach": "tetto panoramico in vetro",
    "panoramaglasdach": "tetto panoramico in vetro",
    "multibeam led": "fari MULTIBEAM LED",
    "multibeam-led": "fari MULTIBEAM LED",
    "anhängevorrichtung": "gancio traino",
    "anhängevorrichtung mit esp": "gancio traino con ESP",
    "windschott": "frangivento",
    "adaptives kurvenlicht": "fari adattivi in curva",
    "totwinkel-assistent": "assistente angolo cieco",
    "spurhalte-assistent": "assistente mantenimento corsia",
    "verkehrsschild-erkennung": "riconoscimento segnali stradali",
    "volldigitales instrumenten-display": "quadro strumenti digitale",
    "volldigitales kombiinstrument": "quadro strumenti digitale",
    "wärmedämmend dunkel getöntes glas": "vetri oscurati termoisolanti",
    "getönte scheiben": "vetri oscurati",
    "dachreling schwarz": "barre sul tetto nere",
    "easy-pack heckklappe": "portellone Easy-Pack",
    "beheizbare frontscheibe": "parabrezza riscaldato",
    "allradantrieb": "trazione integrale",
    "elektr. seitenspiegel": "specchietti laterali elettrici",
    "elektrische seitenspiegel": "specchietti laterali elettrici",
    "seitenspiegel": "specchietti laterali",
    "innenspiegel autom. abblendend": "specchietto interno autoschermante",
    "automatisch abblendender innenspiegel": "specchietto interno autoschermante",
    "innenspiegel": "specchietto interno",
    "notrufsystem": "sistema di chiamata d'emergenza",
    "pannenkit": "kit riparazione pneumatici",
    "reifenpannenset": "kit riparazione pneumatici",
    "dieselpartikelfilter": "filtro antiparticolato",
    "partikelfilter": "filtro antiparticolato",
    "reifendruckkontrollsystem": "controllo pressione pneumatici",
    "reifendruckkontrolle": "controllo pressione pneumatici",
    "traktionskontrolle": "controllo di trazione",
    "musikstreaming integriert": "streaming musicale integrato",
    "induktionsladen für smartphones": "ricarica wireless per smartphone",
    "induktionsladen": "ricarica a induzione",
    "elektr. wegfahrsperre": "immobilizzatore elettronico",
    "wegfahrsperre": "immobilizzatore",
    # tipi di carrozzeria (Fahrzeugtyp)
    "kombi": "Station Wagon",
    "limousine": "Berlina",
    "kleinwagen": "Utilitaria",
    "geländewagen": "Fuoristrada",
    "gelaendewagen": "Fuoristrada",
    "cabrio": "Cabrio",
    "cabriolet": "Cabrio",
    "coupé": "Coupé",
    "coupe": "Coupé",
    "sportwagen": "Sportiva",
    "van/kleinbus": "Van",
    "van": "Van",
    "pkw": "Autovettura",
}

# --------------------------------------------------------------------------- #
# Singole parole (fallback). Chiavi lowercase.
# --------------------------------------------------------------------------- #
WORDS: dict[str, str] = {
    "tüv": "revisione",
    "hauptuntersuchung": "revisione",
    "abgasuntersuchung": "controllo emissioni",
    "vorbereitung": "predisposizione",
    "allrad": "trazione integrale",
    "frontantrieb": "trazione anteriore",
    "heckantrieb": "trazione posteriore",
    "schaltgetriebe": "cambio manuale",
    "automatik": "cambio automatico",
    "automatikgetriebe": "cambio automatico",
    "doppelkupplungsgetriebe": "cambio doppia frizione",
    "klimaanlage": "climatizzatore",
    "klimaautomatik": "climatizzatore automatico",
    "sitzheizung": "sedili riscaldati",
    "standheizung": "riscaldamento autonomo",
    "navigationssystem": "navigatore",
    "navi": "navigatore",
    "für": "per",
    "beleuchtung": "illuminazione",
    "fernlicht": "abbaglianti",
    "kurvenlicht": "fari in curva",
    "anhängevorrichtung": "gancio traino",
    "windschott": "frangivento",
    "getönt": "oscurato",
    "getönte": "oscurati",
    "getöntes": "oscurato",
    "scheiben": "vetri",
    "frontscheibe": "parabrezza",
    "heckklappe": "portellone",
    "wärmedämmend": "termoisolante",
    "paket": "pacchetto",
    "elektr": "elettrico",
    "elektr.": "elettrico",
    "allradantrieb": "trazione integrale",
    "abblendend": "autoschermante",
    "notrufsystem": "sistema chiamata emergenza",
    "pannenkit": "kit riparazione",
    "partikelfilter": "filtro antiparticolato",
    "musikstreaming": "streaming musicale",
    "integriert": "integrato",
    "reifendruckkontrolle": "controllo pressione pneumatici",
    "traktionskontrolle": "controllo di trazione",
    "seitenspiegel": "specchietti laterali",
    "innenspiegel": "specchietto interno",
    "rückfahrkamera": "telecamera posteriore",
    "tempomat": "cruise control",
    "panoramadach": "tetto panoramico",
    "schiebedach": "tetto apribile",
    "lederausstattung": "interni in pelle",
    "leder": "pelle",
    "teilleder": "pelle e tessuto",
    "stoff": "tessuto",
    "alcantara": "alcantara",
    "xenon": "xeno",
    "nebelscheinwerfer": "fendinebbia",
    "sitzbelüftung": "sedili ventilati",
    "lenkradheizung": "volante riscaldato",
    "einparkhilfe": "sensori di parcheggio",
    "rückfahrsensoren": "sensori posteriori",
    "freisprecheinrichtung": "vivavoce",
    "sprachsteuerung": "comandi vocali",
    "regensensor": "sensore pioggia",
    "lichtsensor": "sensore luci",
    "nichtraucherfahrzeug": "veicolo non fumatori",
    "garantie": "garanzia",
    "unfallfrei": "non incidentata",
    "scheckheftgepflegt": "tagliandi certificati",
    "metallic": "metallizzato",
    "alufelgen": "cerchi in lega",
    "leichtmetallfelgen": "cerchi in lega",
    "winterreifen": "pneumatici invernali",
    "sommerreifen": "pneumatici estivi",
    "isofix": "attacchi Isofix",
    "bordcomputer": "computer di bordo",
    "multifunktionslenkrad": "volante multifunzione",
    "lederlenkrad": "volante in pelle",
    "sportsitze": "sedili sportivi",
    "sportfahrwerk": "assetto sportivo",
    "luftfederung": "sospensioni pneumatiche",
    "servolenkung": "servosterzo",
    "zentralverriegelung": "chiusura centralizzata",
    "wegfahrsperre": "immobilizzatore",
    "airbag": "airbag",
    "seitenairbag": "airbag laterali",
    "kopfairbag": "airbag per la testa",
    "esp": "ESP",
    "abs": "ABS",
    "isofix-befestigung": "attacchi Isofix",
    "anhängerkupplung": "gancio traino",
    "dachreling": "barre sul tetto",
    "dachträger": "portapacchi",
    "soundsystem": "impianto audio premium",
    "subwoofer": "subwoofer",
    "armlehne": "bracciolo",
    "sitzheizung": "sedili riscaldati",
    "beheizbar": "riscaldabile",
    "elektrisch": "elettrico",
    "elektrische": "elettrici",
    "verstellbar": "regolabile",
    "vorne": "anteriore",
    "hinten": "posteriore",
    "vorn": "anteriore",
    "und": "e",
    "mit": "con",
    "inkl.": "incl.",
    "inklusive": "incluso",
    "schwarz": "nero",
    "weiß": "bianco",
    "grau": "grigio",
    "silber": "argento",
    "blau": "blu",
    "rot": "rosso",
    "grün": "verde",
    "braun": "marrone",
    "beige": "beige",
    "gold": "oro",
    "orange": "arancione",
}

# --------------------------------------------------------------------------- #
# Rilevamento residui tedeschi (usato da qa_gate in modo indipendente).
# Parole/indicatori tipicamente tedeschi che NON devono restare in output IT.
# --------------------------------------------------------------------------- #
GERMAN_STOPWORDS: frozenset[str] = frozenset({
    "und", "mit", "ohne", "für", "der", "die", "das", "den", "dem", "des",
    "ein", "eine", "einen", "einem", "einer", "ist", "sind", "wurde", "wird",
    "nicht", "auch", "sehr", "oder", "aber", "wie", "bei", "vom", "zum", "zur",
    "auf", "aus", "nach", "über", "unter", "vor", "hinten", "vorne", "vorn",
    "inkl", "inklusive", "fahrzeug", "ausstattung", "neu", "gebraucht",
    "scheckheftgepflegt", "unfallfrei", "garantie", "leder", "stoff", "schwarz",
    "weiß", "grau", "silber", "blau", "rot", "elektrisch", "beheizbar",
    "schiebedach", "sitzheizung", "klimaanlage", "navigationssystem",
})

# suffissi tedeschi FORTI: solo match a FINE parola (endswith), per evitare falsi
# positivi su parole italiane (es. "telecamera", "assistente", "automatico").
GERMAN_MORPHEMES: tuple[str, ...] = (
    "ung", "heit", "keit", "schaft", "getriebe", "fahrzeug", "assistent",
    "heizung", "scheinwerfer", "verriegelung", "fensterheber", "kupplung",
    "antrieb", "system", "kontrolle", "filter", "spiegel", "laden",
)

UMLAUT_RE = re.compile(r"[äöüßÄÖÜ]")


def has_umlaut(text: str) -> bool:
    return bool(UMLAUT_RE.search(text or ""))


def looks_german(token: str) -> bool:
    """Euristica INDIPENDENTE: True se il token sembra tedesco non tradotto."""
    t = re.sub(r"[^\wäöüßÄÖÜ-]", "", (token or "")).lower()
    if len(t) < 3:
        return False
    if has_umlaut(t):
        return True
    if t in GERMAN_STOPWORDS:
        return True
    # morfemi tedeschi lunghi (evita falsi positivi su parole IT corte)
    if len(t) >= 6 and any(t.endswith(suf) for suf in GERMAN_MORPHEMES):
        return True
    return False


# =========================================================================== #
# AMPLIAMENTO VOCABOLARIO (2026-07-03) — copertura ~totale annunci mobile.de
# =========================================================================== #

# --- MORFEMI BASE: mattoni per lo "spezza-parole" dei composti tedeschi ------
# Usati da translate_copy._decompose(): una parola mai vista viene scomposta
# in questi mattoni e tradotta (es. Sitzeinstellung = sitz+einstellung).
MORPHEMES: dict[str, str] = {
    # parti auto
    "sitz": "sedile", "sitze": "sedili", "lenkrad": "volante", "rad": "ruota", "räder": "ruote",
    "reifen": "pneumatici", "felge": "cerchio", "felgen": "cerchi", "tür": "porta", "türen": "porte",
    "fenster": "finestrino", "scheibe": "vetro", "spiegel": "specchietto", "dach": "tetto",
    "motor": "motore", "getriebe": "cambio", "bremse": "freno", "bremsen": "freni", "kupplung": "frizione",
    "tank": "serbatoio", "auspuff": "scarico", "fahrwerk": "assetto", "federung": "sospensioni",
    "achse": "asse", "kolben": "pistone", "zylinder": "cilindro", "turbo": "turbo",
    "kamera": "telecamera", "sensor": "sensore", "sensoren": "sensori", "scheinwerfer": "fari",
    "leuchte": "luce", "leuchten": "luci", "licht": "luce", "blinker": "indicatore",
    "lenkung": "sterzo", "servolenkung": "servosterzo", "kotflügel": "parafango",
    "stoßstange": "paraurti", "stossstange": "paraurti", "haube": "cofano", "klappe": "portello",
    "heckklappe": "portellone", "kofferraum": "bagagliaio", "gepäckraum": "vano bagagli",
    "armlehne": "bracciolo", "kopfstütze": "poggiatesta", "gurt": "cintura", "polster": "rivestimento",
    # funzioni / sistemi
    "heizung": "riscaldamento", "kühlung": "raffreddamento", "klima": "climatizzatore",
    "klimaanlage": "climatizzatore", "lüftung": "ventilazione", "belüftung": "ventilazione",
    "einstellung": "regolazione", "verstellung": "regolazione", "steuerung": "comando",
    "regelung": "regolazione", "kontrolle": "controllo", "überwachung": "monitoraggio",
    "erkennung": "riconoscimento", "warnung": "avviso", "warner": "avviso", "assistent": "assistente",
    "assistenz": "assistenza", "system": "sistema", "anlage": "impianto", "automatik": "automatico",
    "funktion": "funzione", "paket": "pacchetto", "speicher": "memoria", "memory": "memoria",
    "verriegelung": "chiusura", "schließung": "chiusura", "sperre": "blocco", "zugang": "accesso",
    "navigation": "navigazione", "kommunikation": "comunicazione", "verbindung": "connessione",
    "beleuchtung": "illuminazione", "ausstattung": "dotazione", "einrichtung": "dispositivo",
    "vorrichtung": "dispositivo", "vorbereitung": "predisposizione", "regler": "regolatore",
    "begrenzer": "limitatore", "halter": "supporto", "halterung": "supporto", "stütze": "supporto",
    "träger": "portapacchi", "kupplungs": "gancio", "anhänger": "rimorchio",
    # materiali / colori base
    "leder": "pelle", "stoff": "tessuto", "alcantara": "alcantara", "holz": "legno",
    "aluminium": "alluminio", "chrom": "cromo", "metall": "metallo", "kunststoff": "plastica",
    "glas": "vetro", "carbon": "carbonio",
    "schwarz": "nero", "weiß": "bianco", "grau": "grigio", "silber": "argento", "blau": "blu",
    "rot": "rosso", "grün": "verde", "braun": "marrone", "beige": "beige", "gelb": "giallo",
    "orange": "arancione", "gold": "oro", "bronze": "bronzo", "anthrazit": "antracite",
    # posizione / qualificatori (utili nei composti)
    "vorder": "anteriore", "hinter": "posteriore", "seiten": "laterale", "mittel": "centrale",
    "vorne": "anteriore", "hinten": "posteriore", "innen": "interno", "außen": "esterno",
    "aussen": "esterno", "rück": "posteriore", "rückfahr": "retromarcia", "front": "anteriore",
    "heck": "posteriore", "dach": "tetto", "boden": "pavimento", "voll": "completo",
    "halb": "semi", "elektrisch": "elettrico", "elektr": "elettrico", "beheizbar": "riscaldabile",
    "beheiz": "riscaldato", "beheizt": "riscaldato", "verstellbar": "regolabile", "klappbar": "ripiegabile",
    "abnehmbar": "removibile", "schwenkbar": "estraibile", "automatisch": "automatico",
    "adaptiv": "adattivo", "aktiv": "attivo", "digital": "digitale", "schlüssellos": "senza chiave",
    # concetti auto
    "geschwindigkeit": "velocità", "abstand": "distanza", "spur": "corsia", "wechsel": "cambio",
    "halte": "mantenimento", "park": "parcheggio", "einpark": "parcheggio", "brems": "frenata",
    "not": "emergenza", "notbrems": "frenata di emergenza", "kollision": "collisione",
    "verkehr": "traffico", "verkehrs": "traffico", "zeichen": "segnale", "schild": "segnale",
    "müdigkeit": "stanchezza", "totwinkel": "angolo cieco", "winkel": "angolo", "tot": "cieco",
    "regen": "pioggia", "licht": "luce", "tag": "giorno", "nacht": "notte", "fern": "abbagliante",
    "abblend": "anabbagliante", "kurven": "curva", "nebel": "fendinebbia",
    "antrieb": "trazione", "allrad": "trazione integrale", "vorderrad": "trazione anteriore",
    "hinterrad": "trazione posteriore", "verbrauch": "consumo", "leistung": "potenza",
    "hubraum": "cilindrata", "drehmoment": "coppia", "emission": "emissioni", "abgas": "gas di scarico",
    "kraftstoff": "carburante", "benzin": "benzina", "diesel": "diesel", "hybrid": "ibrido",
    "elektro": "elettrico", "erdgas": "metano", "autogas": "GPL",
    "komfort": "comfort", "sport": "sport", "winter": "invernale", "sommer": "estivo",
    "sicherheit": "sicurezza", "sicherheits": "sicurezza", "schutz": "protezione",
    "wagen": "vettura", "fahrzeug": "veicolo", "fahrer": "conducente", "beifahrer": "passeggero",
    "personen": "persone", "gepäck": "bagagli", "raum": "vano", "kind": "bambino", "kinder": "bambini",
    "sound": "audio", "lautsprecher": "altoparlanti", "radio": "radio", "bildschirm": "schermo",
    "display": "display", "anzeige": "indicatore", "instrument": "strumento", "cockpit": "quadro strumenti",
    "sitzheizung": "sedili riscaldati", "standheizung": "riscaldamento autonomo",
    "multifunktion": "multifunzione", "multifunktions": "multifunzione",
    "fensterheber": "alzacristalli", "zentralverriegelung": "chiusura centralizzata",
}

# --- FRASI aggiuntive (composti frequenti già "pronti") ----------------------
EXTRA_PHRASES: dict[str, str] = {
    "elektrische sitzverstellung": "regolazione elettrica dei sedili",
    "elektrisch verstellbare sitze mit memory": "sedili elettrici con memoria",
    "beheizbare frontscheibe": "parabrezza riscaldabile",
    "beheizbares lederlenkrad": "volante in pelle riscaldato",
    "multifunktions-lederlenkrad": "volante multifunzione in pelle",
    "verkehrszeichenerkennung": "riconoscimento segnali stradali",
    "spurhalteassistent": "assistente mantenimento corsia",
    "spurverlassenswarnung": "avviso superamento corsia",
    "notbremsassistent": "assistente frenata di emergenza",
    "auffahrwarnsystem": "sistema avviso tamponamento",
    "abstandsregeltempomat": "cruise control adattivo",
    "berganfahrhilfe": "assistente partenza in salita",
    "reifendruckkontrollsystem": "sistema controllo pressione pneumatici",
    "reifendruckkontrolle": "controllo pressione pneumatici",
    "geschwindigkeitsbegrenzungsanlage": "limitatore di velocità",
    "aktive geschwindigkeitsregelanlage": "regolatore di velocità attivo",
    "elektrische heckklappe": "portellone elettrico",
    "elektrisch anklappbare außenspiegel": "specchietti ripiegabili elettricamente",
    "schlüsselloses zugangssystem": "sistema di accesso senza chiave",
    "schlüssellose zentralverriegelung": "chiusura centralizzata senza chiave",
    "led-tagfahrlicht": "luci diurne a LED",
    "adaptives kurvenlicht": "fari adattivi in curva",
    "dynamische kurvenlichtfunktion": "fari dinamici in curva",
    "panorama-glasschiebedach": "tetto panoramico apribile in vetro",
    "durchladeeinrichtung": "vano passante posteriore",
    "gepäckraumabdeckung": "copertura bagagliaio",
    "gepäckraumabtrennung": "rete divisoria bagagliaio",
    "gepaeckraumabtrennung": "rete divisoria bagagliaio",
    "umklappbare rücksitzbank": "sedili posteriori abbattibili",
    "geteilt umklappbare rücksitze": "sedili posteriori abbattibili frazionati",
    "isofix-aufnahmen": "attacchi Isofix",
    "regensensor mit lichtsensor": "sensore pioggia e luci",
    "start-stopp-system": "sistema start&stop",
    "achtfach elektrisch verstellbare sitze": "sedili regolabili elettricamente",
    "innenraumfilter": "filtro abitacolo",
    "aktivkohlefilter": "filtro a carboni attivi",
    "wärmeschutzverglasung": "vetri termici",
    "getönte scheiben": "vetri oscurati",
    "abgedunkelte scheiben": "vetri oscurati",
    # --- dotazioni viste in campo il 2026-09-02 (uscivano in tedesco nel PDF, E16) ---
    "anhängerrangierassistent": "assistente manovra rimorchio",
    "anhaengerrangierassistent": "assistente manovra rimorchio",
    "ausparkassistent": "assistente uscita dal parcheggio",
    "einparkassistent": "assistente al parcheggio",
    "blendfreies fernlicht": "abbaglianti antiabbagliamento",
    "cd-spieler": "lettore CD",
    "cd-wechsler": "caricatore CD",
    "scheinwerferreinigung": "lavafari",
    "scheinwerferreinigungsanlage": "lavafari",
    "skisack": "sacca portasci",
    "durchladesystem": "vano passante posteriore",
    "umklappbarer beifahrersitz": "sedile passeggero abbattibile",
    "elektr. seitenspiegel anklappbar": "specchietti laterali elettrici ripiegabili",
    "elektrisch anklappbare außenspiegel": "specchietti esterni ripiegabili elettricamente",
    "elektr. sitzeinstellung": "sedili a regolazione elettrica",
    "elektr. sitzeinstellung mit memory-funktion": "sedili a regolazione elettrica con memoria",
    "elektrische sitzeinstellung": "sedili a regolazione elettrica",
    "isofix beifahrersitz": "attacchi Isofix sedile passeggero",
    "inspektion neu": "tagliando appena eseguito",
    "scheckheftgepflegt": "tagliandi regolari certificati",
}

# --- PAROLE aggiuntive (singole) --------------------------------------------
EXTRA_WORDS: dict[str, str] = {
    # condizioni / stato annuncio
    "gepflegt": "curata", "scheckheftgepflegt": "tagliandi certificati", "neuwertig": "come nuova",
    "unfallfrei": "non incidentata", "fahrbereit": "marciante", "zugelassen": "immatricolata",
    "erstzulassung": "prima immatricolazione", "vorbesitzer": "proprietari precedenti",
    "hand": "mano", "garantie": "garanzia", "gewährleistung": "garanzia", "inspektion": "tagliando",
    "inspektionen": "tagliandi", "service": "assistenza", "checkheft": "libretto tagliandi",
    "nichtraucher": "non fumatori", "nichtraucherfahrzeug": "veicolo non fumatori",
    "importfahrzeug": "veicolo d'importazione", "reimport": "reimportata", "jahreswagen": "km zero",
    "vorführwagen": "auto dimostrativa", "gebraucht": "usata", "neu": "nuova", "neufahrzeug": "auto nuova",
    "tüv": "revisione", "hu": "revisione", "au": "controllo emissioni",
    # carrozzeria / tipo
    "limousine": "berlina", "kombi": "station wagon", "kleinwagen": "utilitaria", "kleinwagen": "utilitaria",
    "geländewagen": "fuoristrada", "cabriolet": "cabrio", "cabrio": "cabrio", "coupé": "coupé",
    "roadster": "roadster", "van": "van", "kleinbus": "minibus", "pickup": "pick-up",
    "schrägheck": "due volumi", "stufenheck": "tre volumi", "sportwagen": "sportiva",
    # meccanica / dati
    "schaltgetriebe": "cambio manuale", "handschaltung": "cambio manuale", "gangschaltung": "cambio",
    "doppelkupplungsgetriebe": "cambio doppia frizione", "wandlerautomatik": "cambio automatico",
    "vierradantrieb": "trazione integrale", "frontantrieb": "trazione anteriore",
    "heckantrieb": "trazione posteriore", "zylinder": "cilindri", "türig": "porte", "sitzig": "posti",
    "türer": "porte", "gänge": "marce", "gang": "marcia", "kw": "kW", "ps": "CV",
    # comfort / interni
    "klimaautomatik": "climatizzatore automatico", "klimaanlage": "climatizzatore",
    "sitzheizung": "sedili riscaldati", "lenkradheizung": "volante riscaldato",
    "ledersitze": "sedili in pelle", "sportsitze": "sedili sportivi", "komfortsitze": "sedili comfort",
    "massagesitze": "sedili con massaggio", "belüftete": "ventilati", "beheizte": "riscaldati",
    "ambientebeleuchtung": "illuminazione d'ambiente", "innenbeleuchtung": "illuminazione interna",
    "make-up-spiegel": "specchietto di cortesia", "handschuhfach": "vano portaoggetti",
    "becherhalter": "portabicchieri", "mittelarmlehne": "bracciolo centrale",
    "panoramadach": "tetto panoramico", "schiebedach": "tetto apribile", "glasdach": "tetto in vetro",
    # sicurezza / assistenza
    "airbags": "airbag", "seitenairbags": "airbag laterali", "kopfairbags": "airbag per la testa",
    "knieairbag": "airbag per le ginocchia", "wegfahrsperre": "immobilizzatore",
    "alarmanlage": "antifurto", "diebstahlwarnanlage": "antifurto", "notbremsassistent": "assistente frenata",
    "bremsassistent": "assistente frenata", "berganfahrassistent": "assistente partenza in salita",
    "einparkhilfe": "sensori di parcheggio", "parksensoren": "sensori di parcheggio",
    "rückfahrkamera": "telecamera posteriore", "umgebungskamera": "telecamera perimetrale",
    "totwinkelassistent": "assistente angolo cieco", "müdigkeitswarner": "rilevatore di stanchezza",
    "fernlichtassistent": "assistente abbaglianti", "regensensor": "sensore pioggia",
    "lichtsensor": "sensore luci", "tempomat": "cruise control", "geschwindigkeitsregelanlage": "regolatore di velocità",
    # multimedia
    "navigationssystem": "navigatore", "navi": "navigatore", "bluetooth": "Bluetooth",
    "freisprecheinrichtung": "vivavoce", "sprachsteuerung": "comandi vocali", "touchscreen": "touchscreen",
    "bordcomputer": "computer di bordo", "soundsystem": "impianto audio", "subwoofer": "subwoofer",
    "usb": "USB", "aux": "AUX", "dab": "DAB", "cd-wechsler": "caricatore CD",
    "kabelloses": "wireless", "induktives": "a induzione", "ladeschale": "ricarica wireless",
    # ruote / esterni
    "leichtmetallfelgen": "cerchi in lega", "alufelgen": "cerchi in lega", "stahlfelgen": "cerchi in acciaio",
    "winterreifen": "pneumatici invernali", "sommerreifen": "pneumatici estivi",
    "allwetterreifen": "pneumatici quattro stagioni", "reserverad": "ruota di scorta",
    "dachreling": "barre sul tetto", "dachträger": "portapacchi", "anhängerkupplung": "gancio traino",
    "metalliclackierung": "vernice metallizzata", "metallic": "metallizzato", "lackierung": "verniciatura",
    "nebelscheinwerfer": "fendinebbia", "xenon": "xeno", "bixenon": "bi-xeno", "matrix": "matrix",
    # parole comuni nelle descrizioni
    "fahrzeug": "veicolo", "zustand": "condizioni", "ausstattung": "dotazione", "farbe": "colore",
    "preis": "prezzo", "verhandlungsbasis": "trattabile", "festpreis": "prezzo fisso",
    "finanzierung": "finanziamento", "leasing": "leasing", "inzahlungnahme": "permuta",
    "lieferung": "consegna", "verfügbar": "disponibile", "sofort": "subito", "wenige": "pochi",
    "kilometer": "chilometri", "erstbesitz": "primo proprietario", "vollausstattung": "full optional",
    "gepflegter": "curato", "top": "ottimo", "sehr": "molto", "guter": "buono", "gutem": "buono",
    "guten": "buono", "hochwertig": "di pregio", "elegant": "elegante", "sportlich": "sportivo",
    "komfortabel": "confortevole", "zuverlässig": "affidabile", "sparsam": "economico",
    "und": "e", "mit": "con", "ohne": "senza", "für": "per", "sowie": "nonché", "inklusive": "incluso",
    "inkl": "incl.", "bzw": "ovvero", "u": "e", "sonderausstattung": "optional",
    "serienausstattung": "dotazione di serie", "extras": "extra", "diverse": "vari",
}

# fonde gli ampliamenti nelle tabelle principali (le voci nuove non sovrascrivono le esistenti)
for _k, _v in EXTRA_PHRASES.items():
    PHRASES.setdefault(_k, _v)
for _k, _v in EXTRA_WORDS.items():
    WORDS.setdefault(_k, _v)
