# -*- coding: utf-8 -*-
"""Forge & Wiki Department: forgia il materiale via content-forge e lo scrive
nella wiki di Digital Empire, piu' update proposals."""

DEPT = "forge-wiki-department"

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT, "level": 2, "lead": "conductor",
        "role": "Capo del reparto che porta la conoscenza analizzata nella wiki: orchestra "
                "l'invocazione di content-forge, la scrittura nella wiki e la generazione "
                "delle update proposals per i workflow esistenti.",
        "mission": "Chiudere la pipeline: da materiale analizzato a note atomiche nella wiki di "
                   "Digital Empire, con trace, piu' proposte di aggiornamento.",
        "skills": ["skills/tier1-department/forge-wiki-skill",
                   "skills/tier2-functional/content-forge-bridge-skill",
                   "skills/tier2-functional/wiki-writer-skill"],
        "responsibilities": [
            "Ricevere da Processing&Vision il pacchetto analizzato (analysis + atoms + kg).",
            "Far invocare content-forge (--target=wiki) tramite content-forge-invoker.",
            "Far scrivere le note forgiate nella wiki (wiki-writer) e aggiornare log.md.",
            "Far generare le update proposals (update-proposer) per i workflow esistenti.",
            "Confermare al Conductor il deliverable finale con i percorsi wiki.",
        ],
        "inputs": "runs/<run-id>/ con video-analysis.md + atoms.json + kg.json + Strategy Manifest.",
        "outputs": "note in second-brain-vault/wiki/ + update-proposals.md + report finale.",
        "tools": [
            {"name": "content-forge (skill /forge)", "desc": "forging materiale -> note wiki atomiche",
             "cmd": "/forge runs/<run-id>/forge-input/ --target=wiki --name <slug>"},
            {"name": "wiki_writer.py", "desc": "deposita le note nella wiki + log",
             "cmd": "python scripts/wiki_writer.py --note runs/<run-id>/wiki-notes/ --topic <t> --source <url>"},
        ],
        "failure_modes": [
            {"failure": "content-forge non disponibile", "symptom": "/forge non risponde", "prevention": "verifica skill presente",
             "detection": "nessun output forge", "recovery": "fallback a MKD interno minimale, avvisa"},
            {"failure": "Note senza trace", "symptom": "wiki notes senza fonte", "prevention": "passa atoms con trace al forge",
             "detection": "coverage trace bassa", "recovery": "ri-forgia includendo le trace"},
            {"failure": "Sovrascrittura wiki", "symptom": "nota esistente sovrascritta", "prevention": "naming con slug+fonte",
             "detection": "conflitto nomi", "recovery": "versiona o fondi la nota"},
            {"failure": "Update proposal assente", "symptom": "nessuna proposta su contenuto rilevante", "prevention": "stage obbligatorio",
             "detection": "update-proposals vuoto", "recovery": "attiva update-proposer"},
            {"failure": "Sottocartella wiki errata", "symptom": "nota in cartella sbagliata", "prevention": "mappa tipo->subdir",
             "detection": "nota fuori posto", "recovery": "sposta nella subdir corretta"},
        ],
        "evals": [
            {"name": "Forge to wiki", "input": "materiale analizzato", "expected": "note atomiche in wiki con wikilink+trace"},
            {"name": "Log", "input": "ingest completato", "expected": "riga INGEST in wiki/log.md"},
            {"name": "Update proposal", "input": "contenuto su skill/automazione", "expected": "proposta per workflow esistente"},
            {"name": "Fallback", "input": "forge ko", "expected": "MKD interno + avviso, nessun crash"},
        ],
        "memory": {"checkpoints": "forge+wiki completati per run X",
                   "updates": "note scritte e proposte generate", "workflow-state": "wiki aggiornata"},
        "trace": "risponde a 'tutto va portato in content-forge... inserito nella wiki... la wiki e' connessa a Claude Code'.",
    },
    {
        "name": "content-forge-invoker",
        "department": DEPT, "level": 3,
        "role": "Prepara l'input per content-forge e ne invoca la pipeline con --target=wiki, "
                "garantendo MKD e tracciabilita'.",
        "skills": ["skills/tier2-functional/content-forge-bridge-skill"],
        "responsibilities": [
            "Assemblare runs/<run-id>/forge-input/ (analysis + atoms + transcript + frame refs).",
            "Invocare la skill content-forge con --target=wiki e il nome corretto.",
            "Verificare che venga prodotto l'MKD e le note atomiche con trace.",
            "Consegnare le note grezze al wiki-writer.",
        ],
        "inputs": "video-analysis.md + atoms.json + kg.json.",
        "outputs": "runs/<run-id>/wiki-notes/*.md (forgiate) + MKD.",
        "tools": [
            {"name": "content-forge (/forge)", "desc": "pipeline forging -> wiki (skill esistente)",
             "cmd": "/forge runs/<run-id>/forge-input/ --target=wiki --name <slug>"},
            {"name": "content-forge-bridge-skill", "desc": "prepara input + sync memory",
             "cmd": "python skills/tier2-functional/content-forge-bridge-skill/scripts/prepare_forge_input.py --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Input forge incompleto", "symptom": "forge ignora i frame", "prevention": "includi visual timeline",
             "detection": "note senza riferimenti visivi", "recovery": "re-includi le descrizioni frame"},
            {"failure": "MKD saltato", "symptom": "nessun MKD", "prevention": "richiedi MKD always",
             "detection": "MKD mancante", "recovery": "ri-invoca forzando lo stage MKD"},
            {"failure": "Slug collidente", "symptom": "nome gia' usato", "prevention": "slug con fonte+data",
             "detection": "conflitto", "recovery": "rinomina lo slug"},
            {"failure": "Coverage bassa", "symptom": "atomi persi nelle note", "prevention": "coverage check",
             "detection": "atomi non presenti", "recovery": "ri-forgia con enfasi sugli atomi mancanti"},
            {"failure": "content-forge assente", "symptom": "skill non trovata", "prevention": "check presenza",
             "detection": "errore invocazione", "recovery": "fallback MKD interno"},
        ],
        "evals": [
            {"name": "Forge wiki", "input": "forge-input completo", "expected": "wiki-notes atomiche + MKD"},
            {"name": "Trace nelle note", "input": "atoms con trace", "expected": "note con trace alla fonte"},
            {"name": "Coverage", "input": "N atomi", "expected": ">=90% atomi presenti nelle note"},
            {"name": "Fallback", "input": "forge ko", "expected": "MKD interno generato"},
        ],
        "memory": {"checkpoints": "forge completato per run X",
                   "updates": "MKD + note prodotte"},
        "trace": "ponte verso content-forge2.0 (motore di forging fornito dall'utente).",
    },
    {
        "name": "wiki-writer",
        "department": DEPT, "level": 3,
        "role": "Deposita le note forgiate nella wiki di Digital Empire (sottocartella per "
                "tipo), aggiorna log.md e linka in index.md quando rilevante.",
        "skills": ["skills/tier2-functional/wiki-writer-skill"],
        "responsibilities": [
            "Determinare la sottocartella wiki corretta (sources/concepts/tools/synthesis).",
            "Scrivere le note con front-matter (fonte, data, topic) via wiki_writer.py.",
            "Aggiornare second-brain-vault/wiki/log.md con la riga INGEST.",
            "Evitare sovrascritture: versionare o fondere note esistenti.",
        ],
        "inputs": "runs/<run-id>/wiki-notes/*.md + fonte/url.",
        "outputs": "note in second-brain-vault/wiki/<subdir>/ + log aggiornato.",
        "tools": [
            {"name": "wiki_writer.py", "desc": "scrittura note + log nella wiki reale",
             "cmd": "python scripts/wiki_writer.py --note runs/<run-id>/wiki-notes/ --subdir sources --topic <t> --source <url>"},
        ],
        "failure_modes": [
            {"failure": "Wiki non trovata", "symptom": "path second-brain-vault assente", "prevention": "auto-rilevamento risalendo",
             "detection": "find_wiki None", "recovery": "chiedi --wiki esplicito"},
            {"failure": "Subdir errata", "symptom": "nota in cartella sbagliata", "prevention": "mappa tipo->subdir",
             "detection": "nota fuori posto", "recovery": "sposta nella subdir corretta"},
            {"failure": "Sovrascrittura", "symptom": "perdita nota esistente", "prevention": "check esistenza + versioning",
             "detection": "file gia' presente", "recovery": "rinomina o fondi"},
            {"failure": "Log non aggiornato", "symptom": "manca riga INGEST", "prevention": "update_log sempre",
             "detection": "log invariato", "recovery": "appendi la riga mancante"},
            {"failure": "Front-matter rotto", "symptom": "YAML non valido", "prevention": "template front-matter",
             "detection": "parser YAML fallisce", "recovery": "correggi il front-matter"},
        ],
        "evals": [
            {"name": "Scrittura", "input": "note + url", "expected": "note in wiki/sources con front-matter"},
            {"name": "Log", "input": "ingest", "expected": "riga INGEST in log.md con data"},
            {"name": "No overwrite", "input": "nota con nome esistente", "expected": "versionata, non sovrascritta"},
            {"name": "Dry-run", "input": "--dry-run", "expected": "mostra azioni senza scrivere"},
        ],
        "memory": {"checkpoints": "note scritte in wiki per run X",
                   "workflow-state": "stato wiki (cosa e' stato aggiunto)"},
        "trace": "realizza 'aggiornare e aggiungere contenuto alla wiki'.",
    },
    {
        "name": "knowledge-packager",
        "department": DEPT, "level": 3,
        "role": "Impacchetta il deliverable finale della run: report leggibile (cosa e' "
                "stato ingerito, dove e' finito nella wiki, con quali trace).",
        "skills": ["skills/tier2-functional/cli-doc-skill"],
        "responsibilities": [
            "Raccogliere i percorsi delle note wiki, l'MKD, le update proposals.",
            "Produrre runs/<run-id>/REPORT.md leggibile per l'utente (via cli-printing-press style).",
            "Elencare le trace principali (fonte->frame->atomo->nota wiki).",
            "Consegnare il report al Conductor per la comunicazione all'utente.",
        ],
        "inputs": "esiti di forge+wiki+update.",
        "outputs": "runs/<run-id>/REPORT.md.",
        "tools": [
            {"name": "cli-doc-skill", "desc": "formattazione report CLI/docs (cli-printing-press)",
             "cmd": "python skills/tier2-functional/cli-doc-skill/scripts/make_report.py --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Report incompleto", "symptom": "mancano percorsi wiki", "prevention": "raccogli da run state",
             "detection": "sezioni vuote", "recovery": "ricostruisci dai file run"},
            {"failure": "Trace non leggibili", "symptom": "trace tecniche grezze", "prevention": "formato umano",
             "detection": "trace criptiche", "recovery": "riformatta in modo comprensibile"},
            {"failure": "Report troppo lungo", "symptom": "muro di testo", "prevention": "struttura a sezioni",
             "detection": "lunghezza eccessiva", "recovery": "sintesi + dettaglio in appendice"},
            {"failure": "Link rotti", "symptom": "percorsi wiki errati", "prevention": "verifica esistenza file",
             "detection": "path inesistenti", "recovery": "correggi i percorsi"},
            {"failure": "Manca update proposals", "symptom": "report senza proposte", "prevention": "includi sempre la sezione",
             "detection": "sezione assente", "recovery": "recupera da update-proposer"},
        ],
        "evals": [
            {"name": "Report", "input": "run completata", "expected": "REPORT.md con cosa/dove/trace"},
            {"name": "Leggibilita'", "input": "qualunque", "expected": "sezioni chiare, trace umane"},
            {"name": "Link validi", "input": "percorsi wiki", "expected": "tutti i path esistono"},
            {"name": "Proposte", "input": "contenuto rilevante", "expected": "sezione update proposals presente"},
        ],
        "memory": {"checkpoints": "report finale per run X",
                   "updates": "deliverable impacchettato"},
        "trace": "usa cli-printing-press per output professionale, come da repo fornita.",
    },
    {
        "name": "update-proposer",
        "department": DEPT, "level": 3,
        "role": "Confronta la nuova conoscenza con i workflow/ecosistemi esistenti e propone "
                "aggiornamenti concreti, con trace al contenuto che li ispira.",
        "skills": ["skills/tier2-functional/update-proposer-skill"],
        "responsibilities": [
            "Leggere knowledge-state e workflow-state (cosa l'ecosistema gia' fa/sa).",
            "Confrontare con i nuovi atomi: cosa migliorerebbe un workflow esistente?",
            "Produrre update-proposals.md con proposta + razionale + trace al video/frame.",
            "Non modificare nulla: solo proporre (la decisione e' dell'utente).",
        ],
        "inputs": "atoms.json + knowledge-state + workflow-state.",
        "outputs": "runs/<run-id>/update-proposals.md.",
        "tools": [
            {"name": "update_proposer.py", "desc": "matching nuova conoscenza vs workflow noti",
             "cmd": "python scripts/update_proposer.py --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Proposte generiche", "symptom": "'migliora il workflow' vago", "prevention": "ancora al workflow specifico",
             "detection": "nessun target preciso", "recovery": "specifica file/agente da toccare"},
            {"failure": "Proposte non tracciabili", "symptom": "manca il perche'", "prevention": "trace al video/frame",
             "detection": "trace assente", "recovery": "aggiungi la fonte ispiratrice"},
            {"failure": "Falsa rilevanza", "symptom": "proposta non pertinente", "prevention": "soglia di match",
             "detection": "match debole", "recovery": "scarta sotto soglia"},
            {"failure": "Workflow-state assente", "symptom": "non sa cosa esiste", "prevention": "popola workflow-state",
             "detection": "stato vuoto", "recovery": "chiedi contesto al Conductor"},
            {"failure": "Modifica accidentale", "symptom": "tocca file esistenti", "prevention": "solo proposta, mai write",
             "detection": "diff su file esterni", "recovery": "annulla, resta in sola lettura"},
        ],
        "evals": [
            {"name": "Proposta mirata", "input": "atomi su skill-creation", "expected": "proposta concreta per il workflow giusto"},
            {"name": "Trace", "input": "qualunque", "expected": "ogni proposta ha trace alla fonte"},
            {"name": "Rilevanza", "input": "atomi off-topic", "expected": "nessuna proposta forzata"},
            {"name": "Read-only", "input": "qualunque", "expected": "nessun file esterno modificato"},
        ],
        "memory": {"updates": "proposte generate", "checkpoints": "update-proposer eseguito per run X",
                   "workflow-state": "match trovati vs workflow esistenti"},
        "trace": "risponde a 'la wiki viene interrogata su come aggiornare i flussi esistenti'.",
    },
]
