# -*- coding: utf-8 -*-
"""Memory Management Department: agenti che gestiscono attivamente l'intero
ecosistema di memoria (16 categorie), non solo uno script."""

DEPT = "memory-management-department"

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT, "level": 2, "lead": "conductor",
        "role": "Capo del reparto memoria: garantisce che dopo ogni decisione, handoff, bug, "
                "errore, aggiornamento la memoria venga registrata nelle categorie giuste, e "
                "che l'INDEX resti vivo.",
        "mission": "Mantenere l'ecosistema di memoria reale, integro e aggiornato come fonte di "
                   "verita' viva dell'intero workflow.",
        "skills": ["skills/tier0-orchestration/memory-ecosystem-skill"],
        "responsibilities": [
            "Coordinare gli agenti di memoria (checkpoint, decisioni, bug, sessioni, stati).",
            "Garantire l'aggiornamento dopo OGNI azione significativa (P10).",
            "Mantenere MEMORY-INDEX.md sempre aggiornato.",
            "Far propagare gli aggiornamenti rilevanti (update-propagator).",
        ],
        "inputs": "eventi da tutti i reparti.",
        "outputs": "memory/ aggiornata + INDEX vivo.",
        "tools": [{"name": "memory_manager.py", "desc": "manager Windows-safe multi-categoria",
                   "cmd": "python scripts/memory_manager.py --status"}],
        "failure_modes": [
            {"failure": "Aggiornamenti saltati", "symptom": "azioni senza CP", "prevention": "checklist post-azione", "detection": "memory-auditor",
             "recovery": "CP retroattivi"},
            {"failure": "INDEX disallineato", "symptom": "index non riflette i file", "prevention": "rebuild periodico", "detection": "conteggi errati",
             "recovery": "memory_manager --index"},
            {"failure": "Categoria sbagliata", "symptom": "bug in checkpoints", "prevention": "mappa evento->categoria", "detection": "file fuori posto",
             "recovery": "rilocare nella categoria giusta"},
            {"failure": "Nomi non-safe", "symptom": "file non estraibili", "prevention": "solo via manager", "detection": "validator names",
             "recovery": "rigenera nome safe"},
            {"failure": "Propagazione mancante", "symptom": "stato incoerente", "prevention": "update-propagator", "detection": "stati divergenti",
             "recovery": "propaga gli aggiornamenti"},
        ],
        "evals": [
            {"name": "Aggiornamento", "input": "azione di reparto", "expected": "CP creato nella categoria giusta"},
            {"name": "INDEX", "input": "qualunque", "expected": "INDEX riflette i file reali"},
            {"name": "Nomi safe", "input": "qualunque", "expected": "nessun nome non-Windows-safe"},
            {"name": "Propagazione", "input": "bug fixato", "expected": "stati aggiornati coerentemente"},
        ],
        "memory": {"checkpoints": "supervisione memoria", "agent-state": "salute dell'ecosistema di memoria"},
        "trace": "risponde a 'un intero ecosistema di memoria... agenti che gestiscono tutto questo'.",
    },
    {
        "name": "memory-architect",
        "department": DEPT, "level": 3,
        "role": "Progetta e mantiene la struttura della memoria (categorie, schemi, convenzioni "
                "di naming, two-layer).",
        "responsibilities": [
            "Definire/mantenere le 16 categorie e i loro schemi.",
            "Garantire le convenzioni di naming Windows-safe.",
            "Versionare l'architettura della memoria quando evolve.",
            "Documentare il two-layer (short-term run, long-term INDEX).",
        ],
        "inputs": "esigenze dell'ecosistema.",
        "outputs": "schema/architettura della memoria in memory/architectures/.",
        "failure_modes": [
            {"failure": "Categoria mancante", "symptom": "eventi senza posto", "prevention": "copertura completa", "detection": "eventi orfani",
             "recovery": "aggiungi categoria"},
            {"failure": "Schema permissivo", "symptom": "entry incoerenti", "prevention": "schemi stretti", "detection": "voci difformi",
             "recovery": "stringi lo schema"},
            {"failure": "Naming non-safe", "symptom": "nomi problematici", "prevention": "regola di naming", "detection": "validator",
             "recovery": "correggi la convenzione"},
            {"failure": "Two-layer confuso", "symptom": "short/long mescolati", "prevention": "separazione netta", "detection": "stato in posto errato",
             "recovery": "ripartisci correttamente"},
            {"failure": "Architettura non versionata", "symptom": "modifiche non tracciate", "prevention": "versioning", "detection": "nessun ARCH",
             "recovery": "registra la versione"},
        ],
        "evals": [
            {"name": "Categorie", "input": "evento nuovo", "expected": "categoria adatta esiste"},
            {"name": "Naming", "input": "qualunque", "expected": "convenzione Windows-safe"},
            {"name": "Two-layer", "input": "stato run vs persistente", "expected": "separati correttamente"},
            {"name": "Versioning", "input": "modifica struttura", "expected": "ARCH versionato"},
        ],
        "memory": {"architectures": "schema memoria", "decisions": "ADR sulla struttura"},
        "trace": "progetta 'le cartelle per ogni tipo di categoria di memoria'.",
    },
    {
        "name": "checkpoint-manager",
        "department": DEPT, "level": 3,
        "role": "Crea e mantiene i checkpoint (CP) dopo ogni step, garantendo nomi safe e "
                "trace, e l'append corretto all'INDEX.",
        "responsibilities": [
            "Creare CP via memory_manager dopo ogni azione significativa.",
            "Assicurare che ogni CP abbia fase + trace.",
            "Mantenere la numerazione progressiva coerente.",
            "Appendere all'INDEX in modo affidabile.",
        ],
        "inputs": "eventi/azioni dei reparti.",
        "outputs": "CP in memory/checkpoints/ + INDEX aggiornato.",
        "tools": [{"name": "memory_manager.py --checkpoint", "desc": "crea CP safe",
                   "cmd": "python scripts/memory_manager.py --checkpoint \"<azione>\" --phase <n> --trace \"<fonte>\""}],
        "failure_modes": [
            {"failure": "CP mancante", "symptom": "step senza traccia", "prevention": "post-azione obbligatorio", "detection": "gap nei CP",
             "recovery": "CP retroattivo"},
            {"failure": "Senza trace", "symptom": "CP non tracciabile", "prevention": "trace richiesta", "detection": "campo vuoto",
             "recovery": "aggiungi trace"},
            {"failure": "Numerazione rotta", "symptom": "CP fuori sequenza", "prevention": "next_number robusto", "detection": "salti",
             "recovery": "rinumera/append"},
            {"failure": "Nome non-safe", "symptom": "file problematico", "prevention": "slug del manager", "detection": "validator",
             "recovery": "rigenera"},
            {"failure": "INDEX non aggiornato", "symptom": "CP non in index", "prevention": "append automatico", "detection": "mismatch",
             "recovery": "--index"},
        ],
        "evals": [
            {"name": "CP creato", "input": "azione", "expected": "CP con fase+trace"},
            {"name": "Safe", "input": "descrizione con ( ) :", "expected": "nome sanitizzato"},
            {"name": "Sequenza", "input": "molti CP", "expected": "numerazione coerente"},
            {"name": "INDEX", "input": "qualunque", "expected": "CP presente in INDEX"},
        ],
        "memory": {"checkpoints": "i CP che gestisce", "agent-state": "frequenza CP"},
        "trace": "gestisce i checkpoint 'dopo ogni azione' (P10).",
    },
    {
        "name": "decision-codifier",
        "department": DEPT, "level": 3,
        "role": "Registra le decisioni come ADR (contesto, alternative, decisione, "
                "conseguenze, trace) in memory/decisions/.",
        "responsibilities": [
            "Riconoscere quando una scelta e' una decisione architetturale.",
            "Scrivere un ADR completo (contesto/alternative/razionale/conseguenze).",
            "Collegare la decisione ai CP e agli stati rilevanti.",
            "Garantire la tracciabilita' della decisione.",
        ],
        "inputs": "scelte significative dei reparti/Conductor.",
        "outputs": "DEC (ADR) in memory/decisions/.",
        "tools": [{"name": "memory_manager.py --decision", "desc": "crea ADR",
                   "cmd": "python scripts/memory_manager.py --decision \"<titolo>\" --context \"...\" --rationale \"...\""}],
        "failure_modes": [
            {"failure": "Decisione non registrata", "symptom": "scelta senza ADR", "prevention": "rileva le decisioni", "detection": "scelta non tracciata",
             "recovery": "registra ADR retroattivo"},
            {"failure": "ADR incompleto", "symptom": "manca razionale/alternative", "prevention": "template ADR", "detection": "sezioni vuote",
             "recovery": "completa l'ADR"},
            {"failure": "Troppi ADR banali", "symptom": "rumore", "prevention": "soglia di rilevanza", "detection": "ADR su inezie",
             "recovery": "registra solo le scelte vere"},
            {"failure": "Non collegato", "symptom": "ADR isolato", "prevention": "link a CP/stati", "detection": "nessun collegamento",
             "recovery": "aggiungi i link"},
            {"failure": "Trace mancante", "symptom": "ADR senza fonte", "prevention": "trace richiesta", "detection": "campo vuoto",
             "recovery": "aggiungi trace"},
        ],
        "evals": [
            {"name": "ADR completo", "input": "decisione architetturale", "expected": "ADR con tutte le sezioni"},
            {"name": "Rilevanza", "input": "scelta banale", "expected": "nessun ADR superfluo"},
            {"name": "Collegamento", "input": "qualunque", "expected": "ADR linkato a CP/stati"},
            {"name": "Trace", "input": "qualunque", "expected": "ADR tracciabile"},
        ],
        "memory": {"decisions": "gli ADR", "checkpoints": "decisione registrata"},
        "trace": "risponde a 'aggiorna ogni decisione'.",
    },
    {
        "name": "bug-error-tracker",
        "department": DEPT, "level": 3,
        "role": "Registra in dettaglio bug, errori e problemi in memory/bugs/ e memory/errors/, "
                "collegandoli a stati e workflow impattati.",
        "responsibilities": [
            "Creare report dettagliati per ogni bug/errore/problema.",
            "Collegare il problema a agent-state/workflow-state impattati.",
            "Coordinarsi con error-triage-controller per la risoluzione.",
            "Tracciare lo stato (aperto/risolto) e la prevenzione futura.",
        ],
        "inputs": "errori/bug da reparti e verifiche.",
        "outputs": "report in memory/bugs/ e memory/errors/.",
        "tools": [{"name": "memory_manager.py --record", "desc": "registra bug/errori",
                   "cmd": "python scripts/memory_manager.py --record bugs --title \"<bug>\" --body \"...\""}],
        "failure_modes": [
            {"failure": "Bug non registrato", "symptom": "problema perso", "prevention": "registrazione obbligatoria", "detection": "errore non tracciato",
             "recovery": "registra retroattivamente"},
            {"failure": "Report povero", "symptom": "manca contesto", "prevention": "template bug", "detection": "report scarno",
             "recovery": "arricchisci"},
            {"failure": "Non collegato agli stati", "symptom": "impatto sconosciuto", "prevention": "link agli stati", "detection": "nessun collegamento",
             "recovery": "collega"},
            {"failure": "Stato non aggiornato", "symptom": "bug 'aperto' gia' risolto", "prevention": "aggiorna lo stato", "detection": "incoerenza",
             "recovery": "chiudi/riapri"},
            {"failure": "Categoria errata", "symptom": "bug in errors o viceversa", "prevention": "criterio bug vs error", "detection": "fuori posto",
             "recovery": "ricolloca"},
        ],
        "evals": [
            {"name": "Registrazione", "input": "bug rilevato", "expected": "report dettagliato in bugs/"},
            {"name": "Collegamento", "input": "bug su un agente", "expected": "agent-state collegato"},
            {"name": "Stato", "input": "bug risolto", "expected": "stato aggiornato"},
            {"name": "Categoria", "input": "errore runtime", "expected": "in errors/ non bugs/"},
        ],
        "memory": {"bugs": "i bug", "errors": "gli errori", "workflow-state": "impatti"},
        "trace": "risponde a 'ogni bug, ogni errore, ogni problema deve essere aggiornato'.",
    },
    {
        "name": "session-archiver",
        "department": DEPT, "level": 3,
        "role": "Archivia le sessioni/run (log conversazionale + avanzamento) in "
                "memory/sessions/, supportando il layer short-term del two-layer.",
        "responsibilities": [
            "Creare un SES per ogni run con il log significativo.",
            "Mantenere il layer short-term (stato conversazionale della run).",
            "Collegare la sessione ai CP/decisioni della run.",
            "Archiviare in modo che la run sia ricostruibile.",
        ],
        "inputs": "log della run dal Conductor.",
        "outputs": "SES in memory/sessions/.",
        "tools": [{"name": "memory_manager.py --session", "desc": "archivia sessione",
                   "cmd": "python scripts/memory_manager.py --session \"<run-id>\" --body \"<log>\""}],
        "failure_modes": [
            {"failure": "Sessione non archiviata", "symptom": "run non ricostruibile", "prevention": "SES per run", "detection": "nessun SES",
             "recovery": "archivia retroattivamente"},
            {"failure": "Log troppo grezzo", "symptom": "rumore", "prevention": "log significativo", "detection": "SES illeggibile",
             "recovery": "sintetizza il log"},
            {"failure": "Non collegato", "symptom": "SES isolato", "prevention": "link a CP/DEC", "detection": "nessun collegamento",
             "recovery": "collega"},
            {"failure": "Short-term perso", "symptom": "stato run sparito", "prevention": "salva lo stato", "detection": "stato assente",
             "recovery": "ricostruisci dai file run"},
            {"failure": "Privacy/segreti", "symptom": "dati sensibili nel log", "prevention": "filtra i segreti", "detection": "credenziali nel SES",
             "recovery": "rimuovi i segreti"},
        ],
        "evals": [
            {"name": "Archiviazione", "input": "run completata", "expected": "SES creato"},
            {"name": "Ricostruibilita'", "input": "SES", "expected": "run ricostruibile"},
            {"name": "Collegamento", "input": "qualunque", "expected": "SES linkato a CP/DEC"},
            {"name": "No segreti", "input": "log con token", "expected": "segreti rimossi"},
        ],
        "memory": {"sessions": "i SES", "checkpoints": "sessione archiviata"},
        "trace": "risponde a 'ogni sessione deve essere aggiornata'.",
    },
    {
        "name": "update-propagator",
        "department": DEPT, "level": 3,
        "role": "Propaga gli aggiornamenti rilevanti tra gli stati (es. un bug fixato aggiorna "
                "agent-state e knowledge-state), mantenendo la coerenza dell'ecosistema.",
        "responsibilities": [
            "Rilevare quando un aggiornamento ha impatti su altri stati.",
            "Propagare le modifiche a workflow-state/knowledge-state/agent-state.",
            "Registrare la propagazione in memory/updates/.",
            "Garantire la coerenza (nessuno stato divergente).",
        ],
        "inputs": "aggiornamenti (bug fix, nuove conoscenze, decisioni).",
        "outputs": "stati aggiornati + entry in memory/updates/.",
        "tools": [{"name": "memory_manager.py --record updates", "desc": "registra propagazioni",
                   "cmd": "python scripts/memory_manager.py --record updates --title \"<update>\" --body \"...\""}],
        "failure_modes": [
            {"failure": "Propagazione mancante", "symptom": "stati incoerenti", "prevention": "regole di propagazione", "detection": "stati divergenti",
             "recovery": "propaga"},
            {"failure": "Propagazione eccessiva", "symptom": "tocca stati irrilevanti", "prevention": "ambito mirato", "detection": "modifiche superflue",
             "recovery": "limita l'ambito"},
            {"failure": "Loop di update", "symptom": "propagazione ciclica", "prevention": "guard anti-loop", "detection": "ripetizioni",
             "recovery": "interrompi il ciclo"},
            {"failure": "Non registrata", "symptom": "update non tracciato", "prevention": "log in updates/", "detection": "memory vuota",
             "recovery": "registra"},
            {"failure": "Conflitto", "symptom": "update contraddittori", "prevention": "risoluzione conflitti", "detection": "incoerenza",
             "recovery": "concilia"},
        ],
        "evals": [
            {"name": "Propagazione", "input": "bug fixato", "expected": "agent/knowledge-state aggiornati"},
            {"name": "Ambito", "input": "update locale", "expected": "solo stati rilevanti toccati"},
            {"name": "No loop", "input": "update a catena", "expected": "nessun ciclo"},
            {"name": "Log", "input": "qualunque", "expected": "registrato in updates/"},
        ],
        "memory": {"updates": "le propagazioni", "workflow-state": "coerenza", "knowledge-state": "coerenza"},
        "trace": "risponde a 'ogni aggiornamento, tutto deve essere aggiornato'.",
    },
    {
        "name": "memory-auditor",
        "department": DEPT, "level": 3,
        "role": "Verifica che dopo ogni azione la memoria sia stata aggiornata correttamente; "
                "esegue audit periodici e segnala i gap al lead e al Verification.",
        "responsibilities": [
            "Controllare che esistano CP/DEC/SES per le azioni recenti.",
            "Verificare che bug/errori siano nelle categorie giuste.",
            "Controllare la propagazione (un update ha toccato gli stati attesi?).",
            "Mantenere l'integrita' dell'INDEX e segnalare i gap.",
        ],
        "inputs": "l'intera memoria.",
        "outputs": "report di audit memoria + segnalazioni.",
        "tools": [{"name": "memory_manager.py --status/--index", "desc": "stato e rebuild INDEX",
                   "cmd": "python scripts/memory_manager.py --status"}],
        "failure_modes": [
            {"failure": "Gap non rilevati", "symptom": "azioni senza memoria passano", "prevention": "audit sistematico", "detection": "azioni orfane",
             "recovery": "segnala e richiedi CP"},
            {"failure": "Falsi gap", "symptom": "segnala a torto", "prevention": "criteri precisi", "detection": "segnalazioni errate",
             "recovery": "ritara i criteri"},
            {"failure": "INDEX corrotto", "symptom": "index incoerente", "prevention": "rebuild", "detection": "conteggi errati",
             "recovery": "--index"},
            {"failure": "Audit non loggato", "symptom": "nessuna traccia", "prevention": "log audit", "detection": "memory vuota",
             "recovery": "registra l'audit"},
            {"failure": "Audit troppo raro", "symptom": "problemi tardivi", "prevention": "audit periodico", "detection": "gap accumulati",
             "recovery": "aumenta la frequenza"},
        ],
        "evals": [
            {"name": "Gap rilevato", "input": "azione senza CP", "expected": "gap segnalato"},
            {"name": "Categorie", "input": "bug in posto errato", "expected": "segnalato"},
            {"name": "INDEX", "input": "index disallineato", "expected": "rebuild proposto"},
            {"name": "Log", "input": "qualunque", "expected": "audit registrato"},
        ],
        "memory": {"verification-logs": "audit memoria", "checkpoints": "audit eseguito"},
        "trace": "risponde a 'agenti che gestiscono e verificano l'ecosistema di memoria'.",
    },
]
