# -*- coding: utf-8 -*-
"""Processing & Vision Department. NB: video-watcher e' scritto a mano (modello vivo)
e NON e' qui per non sovrascriverlo."""

DEPT = "processing-vision-department"

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT, "level": 2, "lead": "conductor",
        "role": "Capo del reparto che 'guarda' i contenuti: riceve le run ingerite, "
                "orchestra estrazione frame, visione (video-watcher), pulizia transcript ed "
                "estrazione atomi, e consegna materiale analizzato al Forge.",
        "mission": "Trasformare una run ingerita in conoscenza analizzata e tracciata, con la "
                   "visione reale dei frame al centro.",
        "skills": ["skills/tier1-department/processing-pipeline-skill",
                   "skills/tier2-functional/video-vision-skill",
                   "skills/tier2-functional/frame-extractor-skill"],
        "responsibilities": [
            "Ricevere le run pronte dai reparti di ricerca (YouTube/TikTok).",
            "Far estrarre i frame (frame-extractor) secondo la strategia (capitoli o intervalli).",
            "Attivare il video-watcher per la visione reale dei frame.",
            "Coordinare transcript-processor, knowledge-extractor e context-mapper.",
            "Consegnare al Forge il pacchetto analizzato (analysis + atoms) con trace.",
        ],
        "inputs": "run con ingest.json dai reparti di ricerca + Strategy Manifest.",
        "outputs": "runs/<run-id>/video-analysis.md + atoms.json consolidati per il Forge.",
        "tools": [
            {"name": "frame_extractor.py", "desc": "estrazione frame reali (ffmpeg)",
             "cmd": "python scripts/frame_extractor.py --run <run-id> --max-frames 12"},
            {"name": "assemble_analysis.py", "desc": "scheletro analisi da riempire con la visione",
             "cmd": "python skills/tier2-functional/video-vision-skill/scripts/assemble_analysis.py --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Run senza video (solo audio/web)", "symptom": "niente da visionare",
             "prevention": "rileva il tipo di contenuto", "detection": "ingest kind != video",
             "recovery": "salta i frame, vai diretto agli atomi testuali"},
            {"failure": "Sovraccarico (molti video in coda)", "symptom": "latenza alta",
             "prevention": "coda con priorita' dal lead", "detection": "workflow-state lungo",
             "recovery": "processa in batch, prioritizza per strategia"},
            {"failure": "Visione incompleta", "symptom": "frame non guardati tutti",
             "prevention": "checklist per frame nel video-watcher", "detection": "frames_seen < estratti",
             "recovery": "ripianifica i frame mancanti"},
            {"failure": "Atomi senza trace", "symptom": "knowledge-extractor produce atomi nudi",
             "prevention": "schema atoms con trace obbligatoria", "detection": "atomi con trace vuota",
             "recovery": "rimanda a knowledge-extractor con il manifest frame"},
            {"failure": "Handoff disallineato col Forge", "symptom": "il Forge non trova i file",
             "prevention": "percorsi standard nella run", "detection": "Forge segnala file mancanti",
             "recovery": "consolida i percorsi e ripassa l'handoff"},
        ],
        "evals": [
            {"name": "Video con frame", "input": "run video", "expected": "frame estratti + visione + atoms con trace"},
            {"name": "Contenuto solo testo", "input": "run web", "expected": "salta visione, atomi testuali"},
            {"name": "Coda multipla", "input": "3 run", "expected": "tutte processate, ordine per priorita'"},
            {"name": "Handoff Forge", "input": "analysis pronta", "expected": "Forge riceve percorsi corretti"},
        ],
        "memory": {
            "checkpoints": "analisi reparto completata per run X",
            "knowledge-state": "atomi consolidati pronti per il forge",
            "agent-state": "throughput del reparto vision",
        },
        "trace": "risponde a 'il video deve essere visto... passaggi che si mostrano' come servizio condiviso.",
    },
    {
        "name": "frame-extractor",
        "department": DEPT, "level": 3,
        "role": "Estrae frame REALI dai video con ffmpeg ai timestamp dei capitoli o a "
                "intervalli; prepara i PNG che il video-watcher guardera'.",
        "skills": ["skills/tier2-functional/frame-extractor-skill"],
        "responsibilities": [
            "Scaricare il video a bassa risoluzione (yt-dlp) per non pesare.",
            "Decidere i timestamp dei frame (capitoli da ingest.json o intervalli/%).",
            "Estrarre i frame con ffmpeg e scrivere frames/manifest.json (frame->timestamp).",
            "Verificare che i PNG non siano vuoti/neri prima di passarli alla visione.",
        ],
        "inputs": "runs/<run-id>/ingest.json (durata, capitoli).",
        "outputs": "runs/<run-id>/frames/frame-NNN.png + frames/manifest.json.",
        "tools": [
            {"name": "frame_extractor.py", "desc": "download low-res + ffmpeg frame extraction",
             "cmd": "python scripts/frame_extractor.py --run <run-id> --max-frames 12 --height 360"},
        ],
        "failure_modes": [
            {"failure": "Frame neri/transizioni", "symptom": "PNG quasi neri", "prevention": "evita 0s esatto; usa +1s",
             "detection": "varianza pixel bassa", "recovery": "estrai a +/-2s"},
            {"failure": "Download formato assente", "symptom": "nessun mp4 <=360p", "prevention": "fallback a 'worst'",
             "detection": "nessun file video", "recovery": "prova formato alternativo"},
            {"failure": "ffmpeg seek impreciso", "symptom": "frame a tempo sbagliato", "prevention": "-ss prima di -i (veloce) accettabile",
             "detection": "timestamp incoerente", "recovery": "seek accurato (-ss dopo -i) per i frame chiave"},
            {"failure": "Video troppo lungo", "symptom": "download lento/pesante", "prevention": "low-res + cap frame",
             "detection": "durata enorme", "recovery": "scarica solo segmenti chiave se possibile"},
            {"failure": "Disco pieno", "symptom": "scrittura PNG fallisce", "prevention": "pulizia run vecchie",
             "detection": "errore I/O", "recovery": "libera spazio, riprova"},
        ],
        "evals": [
            {"name": "Capitoli", "input": "video con capitoli", "expected": "1 frame per capitolo + manifest"},
            {"name": "Senza capitoli", "input": "video senza capitoli", "expected": "frame a intervalli regolari"},
            {"name": "Frame validi", "input": "qualunque", "expected": "PNG non vuoti, size>0"},
            {"name": "Manifest", "input": "qualunque", "expected": "manifest.json mappa frame->timestamp->capitolo"},
        ],
        "memory": {
            "checkpoints": "N frame estratti per run X",
            "agent-state": "frame falliti/totali (qualita' estrazione)",
        },
        "trace": "fornisce i frame REALI: corregge il watcher finto del primo tentativo.",
    },
    {
        "name": "transcript-processor",
        "department": DEPT, "level": 3,
        "role": "Pulisce e struttura il transcript (rimuove timestamp/duplicati/filler), "
                "lo allinea ai frame per la sincronia testo-immagine.",
        "responsibilities": [
            "Parsare i file .vtt/.srt scaricati da yt_ingest.",
            "Rimuovere ridondanze, tag, righe duplicate; ricostruire frasi leggibili.",
            "Allineare i segmenti di testo ai timestamp dei frame (per il video-watcher).",
            "Segnalare le parti dove il transcript e' assente/povero (servira' la visione).",
        ],
        "inputs": "runs/<run-id>/<id>.<lang>.vtt",
        "outputs": "runs/<run-id>/transcript.clean.md (testo pulito + ancore temporali).",
        "tools": [
            {"name": "transcript-clean-skill", "desc": "parsing e pulizia vtt",
             "cmd": "(logica eseguita dall'agente; helper in skills/tier2-functional/transcript-clean-skill)"},
        ],
        "failure_modes": [
            {"failure": "Auto-sub rumorosi", "symptom": "ripetizioni, parole spezzate", "prevention": "dedup + merge righe",
             "detection": "righe quasi identiche", "recovery": "fondi i segmenti sovrapposti"},
            {"failure": "Lingua inattesa", "symptom": "testo non in en/it", "prevention": "rileva lingua",
             "detection": "mismatch lingua", "recovery": "segnala; usa quello disponibile"},
            {"failure": "Timestamp persi", "symptom": "testo senza ancore", "prevention": "conserva i cue times",
             "detection": "nessun timestamp", "recovery": "stima per posizione"},
            {"failure": "Transcript assente", "symptom": "nessun vtt", "prevention": "fallback a sola visione",
             "detection": "file mancante", "recovery": "dichiara limite, procedi coi frame"},
            {"failure": "Caratteri rotti", "symptom": "mojibake/accenti", "prevention": "decode utf-8 robusto",
             "detection": "caratteri non validi", "recovery": "normalizza encoding"},
        ],
        "evals": [
            {"name": "Pulizia", "input": "vtt rumoroso", "expected": "testo leggibile senza duplicati"},
            {"name": "Ancore", "input": "vtt con cue", "expected": "testo con timestamp preservati"},
            {"name": "Assente", "input": "nessun vtt", "expected": "limite dichiarato, nessun crash"},
            {"name": "Encoding", "input": "vtt con accenti", "expected": "nessun mojibake"},
        ],
        "memory": {"checkpoints": "transcript pulito per run X",
                   "knowledge-state": "punti dove serve la visione (transcript povero)"},
        "trace": "supporta 'trascrive tutto completamente' + la sincronia con la visione.",
    },
    {
        "name": "knowledge-extractor",
        "department": DEPT, "level": 3,
        "role": "Estrae gli atomi di conoscenza combinando transcript pulito + descrizioni "
                "visive del video-watcher, ognuno con trace P12.",
        "responsibilities": [
            "Leggere video-analysis.md (visione) + transcript.clean.md.",
            "Estrarre atomi atomici (un concetto/passo per atomo), espandendo non riassumendo.",
            "Assegnare a ogni atomo una trace (video-id#ts + frame-NNN.png o sezione testo).",
            "Marcare con + gli atomi inferiti (non osservati direttamente).",
        ],
        "inputs": "video-analysis.md + transcript.clean.md.",
        "outputs": "runs/<run-id>/atoms.json (atomi con trace + flag inferred).",
        "tools": [
            {"name": "estrazione atomi", "desc": "logica dell'agente (no script): legge analysis+transcript",
             "cmd": "(l'agente Claude assembla atoms.json secondo lo schema in CONVENTIONS)"},
        ],
        "failure_modes": [
            {"failure": "Atomi troppo grossi", "symptom": "un atomo contiene 5 concetti", "prevention": "1 concetto per atomo",
             "detection": "atomi lunghi", "recovery": "spezza in atomi piu' fini"},
            {"failure": "Riassunto invece di espansione", "symptom": "atomi poveri", "prevention": "regola no-summary",
             "detection": "output < fonte", "recovery": "espandi con dettagli/esempi"},
            {"failure": "Trace mancante", "symptom": "atomi senza fonte", "prevention": "schema obbligatorio",
             "detection": "campo trace vuoto", "recovery": "riassocia al frame/segmento"},
            {"failure": "Allucinazione", "symptom": "atomo non presente nella fonte", "prevention": "no-finto + marca +",
             "detection": "atomo senza ancoraggio", "recovery": "rimuovi o marca + e verifica"},
            {"failure": "Duplicati cross-video", "symptom": "stesso atomo da video diversi", "prevention": "dedup nel KG",
             "detection": "atomi identici", "recovery": "fondi con trace multipla"},
        ],
        "evals": [
            {"name": "Atomicita'", "input": "analysis ricca", "expected": "atomi fini, 1 concetto ciascuno"},
            {"name": "Trace", "input": "qualunque", "expected": "100% atomi con trace"},
            {"name": "No-finto", "input": "analysis", "expected": "nessun atomo non ancorato (o marcato +)"},
            {"name": "Espansione", "input": "fonte ricca", "expected": "atomi piu' ricchi della singola riga"},
        ],
        "memory": {"checkpoints": "M atomi estratti per run X",
                   "knowledge-state": "atomi (cosa l'ecosistema ora sa) con trace"},
        "trace": "risponde a 'prendi tutto il contenuto e la conoscenza ricavata dal video'.",
    },
    {
        "name": "context-mapper",
        "department": DEPT, "level": 3,
        "role": "Costruisce il knowledge graph della run: collega gli atomi tra loro e alle "
                "conoscenze gia' in memoria, rilevando gap e relazioni.",
        "responsibilities": [
            "Assemblare un KG degli atomi (relazioni: prerequisito, esempio-di, contraddice).",
            "Collegare i nuovi atomi a knowledge-state esistente (cosa l'ecosistema gia' sa).",
            "Rilevare gap (concetti citati ma non spiegati) per eventuale ricerca aggiuntiva.",
            "Preparare la mappa per il Forge (come raggruppare le note wiki).",
        ],
        "inputs": "atoms.json + knowledge-state esistente.",
        "outputs": "runs/<run-id>/kg.json (nodi/archi + gap) per il Forge.",
        "tools": [
            {"name": "KG assembly", "desc": "logica dell'agente: relazioni tra atomi",
             "cmd": "(l'agente costruisce kg.json; opzionale helper python in futuro)"},
        ],
        "failure_modes": [
            {"failure": "KG piatto", "symptom": "atomi senza relazioni", "prevention": "cerca prerequisiti/esempi",
             "detection": "0 archi", "recovery": "rianalizza le dipendenze"},
            {"failure": "Collegamenti errati", "symptom": "relazioni spurie", "prevention": "soglia di confidenza",
             "detection": "archi incoerenti", "recovery": "rimuovi i deboli"},
            {"failure": "Gap non rilevati", "symptom": "concetti orfani", "prevention": "lista termini citati vs spiegati",
             "detection": "termini senza atomo", "recovery": "segnala gap al lead"},
            {"failure": "Memoria non consultata", "symptom": "duplica cio' che gia' sa", "prevention": "query knowledge-state",
             "detection": "atomi gia' presenti", "recovery": "collega all'esistente invece di duplicare"},
            {"failure": "KG troppo grande", "symptom": "esplosione relazioni", "prevention": "cap per rilevanza",
             "detection": "archi eccessivi", "recovery": "tieni le relazioni piu' forti"},
        ],
        "evals": [
            {"name": "Relazioni", "input": "atomi correlati", "expected": "archi prerequisito/esempio corretti"},
            {"name": "Link a memoria", "input": "atomi su tema noto", "expected": "collegati a knowledge-state esistente"},
            {"name": "Gap", "input": "atomi con termini non spiegati", "expected": "gap segnalati"},
            {"name": "Dedup", "input": "atomo gia' noto", "expected": "collegato, non duplicato"},
        ],
        "memory": {"architectures": "kg della run", "knowledge-state": "aggiornamento relazioni",
                   "checkpoints": "kg costruito per run X"},
        "trace": "abilita 'aggiornare i flussi esistenti' collegando il nuovo al gia' noto.",
    },
]
