# -*- coding: utf-8 -*-
"""Projects/Repos/Workloads Department (il 4o reparto): deep study di report,
repo e workflow SENZA MAI modificare l'originale."""

DEPT = "projects-repos-workloads-department"

_READONLY = "REGOLA SACRA: non modifica MAI l'originale. Solo lettura/analisi (cat/grep/find/parser)."

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT, "level": 2, "lead": "conductor",
        "role": "Capo del 4o reparto: riceve un report/repo/workflow da studiare, coordina "
                "l'analisi profonda (architettura, decisioni, come/quanto funziona) e consegna "
                "atomi tracciati al Forge. Garantisce che l'originale non venga MAI toccato.",
        "mission": "Studiare nei minimi dettagli un progetto/repo/workflow fornito dall'utente "
                   "ed estrarne tutta la conoscenza, senza modificarlo.",
        "skills": ["skills/tier1-department/projects-study-skill",
                   "skills/tier2-functional/repo-study-skill"],
        "responsibilities": [
            "Ricevere il path al report/repo/workflow dal Conductor.",
            "Coordinare workflow-deep-analyzer e repo-deep-study per l'analisi profonda.",
            "Assicurare la regola di sola lettura (nessuna modifica all'originale).",
            "Far estrarre gli atomi (project-knowledge-extractor) con trace a file:riga.",
            "Far confrontare con i workflow esistenti (workload-comparator) per update proposals.",
        ],
        "inputs": "path a report/repo/cartella workflow + focus dal Conductor.",
        "outputs": "deep-analysis.md + atoms.json (trace a file/sezione) per il Forge.",
        "rules": [_READONLY, "NO-FINTO: descrive solo cio' che legge davvero.",
                  "Trace a file:riga per ogni atomo.", "Memory-first."],
        "tools": [
            {"name": "repo-study-skill", "desc": "scanner read-only di repo/cartelle",
             "cmd": "python skills/tier2-functional/repo-study-skill/scripts/scan_repo.py --path <path> --run <run-id>"},
        ],
        "failure_modes": [
            {"failure": "Modifica accidentale", "symptom": "file originale cambiato", "prevention": "solo lettura, mai write sull'originale",
             "detection": "diff sull'originale", "recovery": "ripristina, lavora su copia/indice in sola lettura"},
            {"failure": "Analisi superficiale", "symptom": "manca il 'perche''", "prevention": "richiedi decisioni+rationale",
             "detection": "analisi generica", "recovery": "approfondisci architettura e scelte"},
            {"failure": "Repo enorme", "symptom": "troppi file", "prevention": "prioritizza per rilevanza", "detection": "migliaia di file",
             "recovery": "campiona i file chiave, segnala scope"},
            {"failure": "Trace mancante", "symptom": "atomi senza file:riga", "prevention": "trace obbligatoria",
             "detection": "trace vuota", "recovery": "riassocia a file/sezione"},
            {"failure": "Binari/asset", "symptom": "file non testuali", "prevention": "salta binari", "detection": "estensioni binarie",
             "recovery": "analizza solo testo/codice/doc"},
        ],
        "evals": [
            {"name": "Deep study", "input": "report workflow", "expected": "architettura+decisioni+forza/debolezza con trace"},
            {"name": "Read-only", "input": "qualunque", "expected": "originale invariato"},
            {"name": "Repo grande", "input": "repo con molti file", "expected": "file chiave analizzati, scope dichiarato"},
            {"name": "Update proposal", "input": "workflow simile a uno esistente", "expected": "proposta di miglioramento con trace"},
        ],
        "memory": {"projects-state": "stato dello studio del progetto", "repo-analysis": "esiti analisi repo",
                   "checkpoints": "deep study completato"},
        "trace": "risponde a 'quarto reparto: progetti, repo, workload... studiarlo nei minimi dettagli... non lo devi modificare'.",
    },
    {
        "name": "workflow-deep-analyzer",
        "department": DEPT, "level": 3,
        "role": "Studia in profondita' un report/descrizione di workflow: architettura, "
                "decisioni e 'perche'', come funziona, quanto bene, punti di forza/debolezza, "
                "pattern e anti-pattern (usando i principi di master-build).",
        "skills": ["skills/tier2-functional/repo-study-skill"],
        "responsibilities": [
            "Leggere il report/descrizione nei minimi dettagli (sola lettura).",
            "Ricostruire l'architettura e le decisioni, spiegando il 'perche''.",
            "Valutare come e quanto bene funziona (forza, debolezza, anti-pattern).",
            "Confrontare con i principi noti (master-build, content-forge) e annotare gli scostamenti.",
        ],
        "inputs": "path a un report/descrizione di workflow.",
        "outputs": "runs/<run-id>/deep-analysis.md (architettura, decisioni, valutazione, trace).",
        "rules": [_READONLY, "Spiega sempre il 'perche'', non solo il 'cosa'."],
        "tools": [{"name": "lettura CLI", "desc": "cat/grep/find in sola lettura + analisi dell'agente",
                   "cmd": "(l'agente legge i file e scrive deep-analysis.md; nessuna modifica all'originale)"}],
        "failure_modes": [
            {"failure": "Solo 'cosa' senza 'perche''", "symptom": "descrizione piatta", "prevention": "obbligo di rationale",
             "detection": "nessuna decisione spiegata", "recovery": "analizza le motivazioni"},
            {"failure": "Valutazione assente", "symptom": "nessun giudizio forza/debolezza", "prevention": "sezione valutazione obbligatoria",
             "detection": "manca la sezione", "recovery": "aggiungi punti forti/deboli con esempi"},
            {"failure": "Modifica originale", "symptom": "file toccato", "prevention": "sola lettura", "detection": "diff",
             "recovery": "ripristina"},
            {"failure": "Trace mancante", "symptom": "claim senza file:sezione", "prevention": "trace obbligatoria",
             "detection": "trace vuota", "recovery": "ancora a file/sezione"},
            {"failure": "Confronto principi assente", "symptom": "nessun riferimento a pattern noti", "prevention": "usa knowledge-pack",
             "detection": "nessun pattern citato", "recovery": "collega a P/PT/AP rilevanti"},
        ],
        "evals": [
            {"name": "Perche'", "input": "report workflow", "expected": "decisioni con rationale"},
            {"name": "Valutazione", "input": "qualunque", "expected": "forza/debolezza/anti-pattern"},
            {"name": "Trace", "input": "qualunque", "expected": "claim ancorati a file:sezione"},
            {"name": "Read-only", "input": "qualunque", "expected": "originale invariato"},
        ],
        "memory": {"projects-state": "analisi del workflow", "checkpoints": "workflow analizzato"},
        "trace": "studio profondo come 'i video vengono guardati': architettura/perche'/come funziona.",
    },
    {
        "name": "repo-deep-study",
        "department": DEPT, "level": 3,
        "role": "Analizza una repo/cartella (struttura, codice, doc, eventuale storia) in sola "
                "lettura, estraendo architettura, pattern implementati e decisioni tecniche.",
        "skills": ["skills/tier2-functional/repo-study-skill"],
        "responsibilities": [
            "Mappare la struttura della repo (cartelle, moduli, entrypoint).",
            "Leggere i file chiave (sola lettura) e ricostruire l'architettura.",
            "Identificare pattern, dipendenze, decisioni tecniche e qualita'.",
            "Tracciare ogni osservazione a file:riga.",
        ],
        "inputs": "path a una repo/cartella.",
        "outputs": "runs/<run-id>/repo-analysis.md (struttura, architettura, pattern, trace).",
        "rules": [_READONLY],
        "tools": [{"name": "scan_repo.py", "desc": "scanner struttura repo (read-only)",
                   "cmd": "python skills/tier2-functional/repo-study-skill/scripts/scan_repo.py --path <path> --run <run-id>"}],
        "failure_modes": [
            {"failure": "Si perde nei file", "symptom": "analisi dispersiva", "prevention": "prioritizza entrypoint/README/config",
             "detection": "nessun filo conduttore", "recovery": "parti dall'architettura di alto livello"},
            {"failure": "Binari/vendored", "symptom": "rumore da node_modules/.git", "prevention": "ignora cartelle note",
             "detection": "file irrilevanti", "recovery": "escludi vendored/binari"},
            {"failure": "Modifica accidentale", "symptom": "repo cambiata", "prevention": "sola lettura", "detection": "diff/git status",
             "recovery": "ripristina"},
            {"failure": "Linguaggio sconosciuto", "symptom": "codice non interpretabile", "prevention": "analizza struttura+commenti",
             "detection": "sintassi ignota", "recovery": "descrivi a livello strutturale"},
            {"failure": "Trace mancante", "symptom": "osservazioni senza file", "prevention": "trace obbligatoria", "detection": "trace vuota",
             "recovery": "ancora a file:riga"},
        ],
        "evals": [
            {"name": "Struttura", "input": "repo", "expected": "mappa moduli + entrypoint"},
            {"name": "Architettura", "input": "repo", "expected": "ricostruzione architettura + pattern"},
            {"name": "Read-only", "input": "qualunque", "expected": "repo invariata"},
            {"name": "Trace", "input": "qualunque", "expected": "osservazioni con file:riga"},
        ],
        "memory": {"repo-analysis": "analisi della repo", "checkpoints": "repo studiata"},
        "trace": "deep study di repo senza modificare, con trace a file/sezione.",
    },
    {
        "name": "project-knowledge-extractor",
        "department": DEPT, "level": 3,
        "role": "Trasforma deep-analysis/repo-analysis in atomi di conoscenza tracciati "
                "(file:riga/sezione), pronti per il forge nella wiki.",
        "responsibilities": [
            "Leggere deep-analysis.md / repo-analysis.md.",
            "Estrarre atomi (pattern, decisione, principio, anti-pattern) uno per concetto.",
            "Assegnare a ogni atomo la trace a file:riga/sezione del progetto.",
            "Marcare con + le inferenze (giudizi non esplicitamente scritti nella fonte).",
        ],
        "inputs": "deep-analysis.md / repo-analysis.md.",
        "outputs": "runs/<run-id>/atoms.json (atomi progetto con trace).",
        "tools": [{"name": "estrazione atomi", "desc": "logica dell'agente sul materiale di analisi",
                   "cmd": "(l'agente assembla atoms.json con trace a file:riga)"}],
        "failure_modes": [
            {"failure": "Atomi vaghi", "symptom": "concetti generici", "prevention": "1 concetto specifico per atomo",
             "detection": "atomi non azionabili", "recovery": "rendi specifici e concreti"},
            {"failure": "Trace assente", "symptom": "atomi senza file", "prevention": "trace obbligatoria", "detection": "trace vuota",
             "recovery": "riassocia a file:riga"},
            {"failure": "Giudizi non marcati", "symptom": "opinioni come fatti", "prevention": "marca + le inferenze",
             "detection": "valutazioni senza fonte", "recovery": "marca + e motiva"},
            {"failure": "Riassunto", "symptom": "atomi poveri", "prevention": "espandi non comprimi", "detection": "output<fonte",
             "recovery": "espandi con dettagli"},
            {"failure": "Duplicati", "symptom": "stesso atomo ripetuto", "prevention": "dedup", "detection": "atomi identici",
             "recovery": "fondi"},
        ],
        "evals": [
            {"name": "Atomi tracciati", "input": "analisi", "expected": "atomi con file:riga"},
            {"name": "Inferenze marcate", "input": "analisi con giudizi", "expected": "giudizi marcati +"},
            {"name": "Specificita'", "input": "qualunque", "expected": "atomi concreti, non vaghi"},
            {"name": "No riassunto", "input": "analisi ricca", "expected": "atomi espansi"},
        ],
        "memory": {"projects-state": "atomi del progetto", "knowledge-state": "conoscenza dal progetto con trace"},
        "trace": "estrae 'tutto' dal progetto, tracciato, per la wiki via forge.",
    },
    {
        "name": "workload-comparator",
        "department": DEPT, "level": 3,
        "role": "Confronta il progetto studiato con gli altri workflow/ecosistemi (inclusi gli "
                "altri reparti di Empire Studio) e propone miglioramenti incrociati.",
        "skills": ["skills/tier2-functional/update-proposer-skill"],
        "responsibilities": [
            "Confrontare gli atomi del progetto con workflow-state/knowledge-state esistenti.",
            "Individuare pattern del progetto applicabili ai workflow dell'utente.",
            "Proporre update concreti (cosa cambiare, dove) con trace al progetto studiato.",
            "Non modificare nulla: solo proposte (cross-dept).",
        ],
        "inputs": "atoms.json del progetto + workflow-state/knowledge-state.",
        "outputs": "runs/<run-id>/cross-update-proposals.md.",
        "rules": [_READONLY],
        "tools": [{"name": "update_proposer.py", "desc": "matching progetto vs workflow noti",
                   "cmd": "python scripts/update_proposer.py --run <run-id> --mode cross"}],
        "failure_modes": [
            {"failure": "Proposte generiche", "symptom": "vaghe", "prevention": "ancora a workflow specifico", "detection": "nessun target",
             "recovery": "specifica file/agente"},
            {"failure": "Falsa applicabilita'", "symptom": "pattern non trasferibile", "prevention": "valuta contesto",
             "detection": "match forzato", "recovery": "scarta"},
            {"failure": "Trace mancante", "symptom": "manca il 'da dove'", "prevention": "trace al progetto", "detection": "trace vuota",
             "recovery": "aggiungi fonte"},
            {"failure": "Modifica accidentale", "symptom": "tocca workflow esistenti", "prevention": "solo proposta", "detection": "diff",
             "recovery": "annulla, resta read-only"},
            {"failure": "Ignora i propri reparti", "symptom": "non considera Empire Studio stesso", "prevention": "includi self-improvement",
             "detection": "nessuna proposta interna", "recovery": "valuta anche i reparti interni"},
        ],
        "evals": [
            {"name": "Proposta mirata", "input": "progetto + workflow simile", "expected": "update concreto con trace"},
            {"name": "Applicabilita'", "input": "pattern non trasferibile", "expected": "non proposto"},
            {"name": "Cross-dept", "input": "pattern utile a Empire Studio", "expected": "proposta di self-improvement"},
            {"name": "Read-only", "input": "qualunque", "expected": "nessuna modifica"},
        ],
        "memory": {"updates": "proposte cross-workflow", "workflow-state": "match progetto vs workflow"},
        "trace": "risponde a 'proporre update ai flussi esistenti' a partire dallo studio di progetti.",
    },
]
