# -*- coding: utf-8 -*-
"""Spec SKILL.md per le skill tier2-functional (gli script .py reali sono gia'
presenti nelle rispettive cartelle scripts/)."""

T = "tier2-functional"

SKILLS = [
    {
        "name": "yt-ingest-skill", "tier": T,
        "description": "Ingestione YouTube/TikTok via yt-dlp: video singolo o canale con screening per focus. Estrae metadata, sottotitoli, capitoli, thumbnail. CLI-only, no API.",
        "tagline": "Da link/canale a materiale grezzo strutturato pronto per la visione.",
        "does": ["Ingerisce un video singolo (info+subs+thumbnail, no download del video).",
                 "Fa screening di un canale/playlist filtrando per --focus.",
                 "Produce runs/<run-id>/ingest.json con id, durata, capitoli, subs."],
        "usage": ["python skills/tier2-functional/yt-ingest-skill/scripts/ingest.py <url> --focus design --run myrun"],
        "uses_scripts": ["scripts/ingest.py (wrapper) -> ../../scripts/yt_ingest.py (motore yt-dlp)"],
        "agents": ["youtube-department/yt-channel-ingester", "youtube-department/video-single-ingester",
                   "tiktok-department/tiktok-ingester"],
        "script_note": "`scripts/ingest.py` valida l'URL e delega al motore condiviso `scripts/yt_ingest.py`.",
        "trace": "risponde a 'parti da un link o da un canale e fai screening dei video'.",
    },
    {
        "name": "frame-extractor-skill", "tier": T,
        "description": "Estrazione di frame VERI da video con ffmpeg ai timestamp dei capitoli o a intervalli. Scarica il video a bassa risoluzione (yt-dlp) e produce PNG + manifest. I frame li guardera' Claude.",
        "tagline": "Frame reali (non screenshot ripetuti) che il video-watcher guardera' davvero.",
        "does": ["Scarica il video a bassa risoluzione (leggero, no audio).",
                 "Estrae frame con ffmpeg ai capitoli o a intervalli/%.",
                 "Scrive frames/frame-NNN.png + frames/manifest.json (frame->timestamp->capitolo)."],
        "usage": ["python skills/tier2-functional/frame-extractor-skill/scripts/extract.py --run myrun --kind youtube"],
        "uses_scripts": ["scripts/extract.py (wrapper) -> ../../scripts/frame_extractor.py (ffmpeg)"],
        "agents": ["processing-vision-department/frame-extractor", "processing-vision-department/video-watcher"],
        "script_note": "`scripts/extract.py` imposta la densita' di frame per tipo e delega a `scripts/frame_extractor.py`.",
        "trace": "fornisce i frame REALI: corregge il watcher finto del primo tentativo.",
    },
    {
        "name": "transcript-clean-skill", "tier": T,
        "description": "Pulisce un transcript .vtt/.srt (rimuove timestamp/tag/duplicati) e ricompone frasi leggibili con ancore temporali, per la sincronia testo-immagine.",
        "tagline": "Da auto-sub rumorosi a transcript leggibile e ancorato ai tempi.",
        "does": ["Parsa .vtt/.srt e rimuove header/tag/duplicati consecutivi.",
                 "Ricompone le frasi con ancore temporali ogni ~30s.",
                 "Produce runs/<run-id>/transcript.clean.md (o segnala l'assenza di transcript)."],
        "usage": ["python skills/tier2-functional/transcript-clean-skill/scripts/clean_transcript.py --run myrun"],
        "uses_scripts": ["scripts/clean_transcript.py"],
        "agents": ["processing-vision-department/transcript-processor"],
        "script_note": "`scripts/clean_transcript.py` e' standalone (stdlib only).",
        "trace": "supporta 'trascrive tutto completamente' + sincronia con la visione.",
    },
    {
        "name": "web-research-skill", "tier": T,
        "description": "Ricerca/crawl web con Playwright (render JS) + screenshot delle sezioni chiave, senza API. Degrada con grazia a urllib se Playwright non e' installato.",
        "tagline": "Ricerca avanzata e crawl di siti, con screenshot che Claude puo' guardare.",
        "does": ["Apre URL con Playwright, estrae il testo principale e cattura screenshot.",
                 "Se Playwright manca, scarica l'HTML grezzo con urllib (senza screenshot).",
                 "Registra le fonti in sources.json con trace a URL + screenshot."],
        "usage": ["python skills/tier2-functional/web-research-skill/scripts/web_research.py --crawl <url> --run myrun"],
        "uses_scripts": ["scripts/web_research.py"],
        "agents": ["web-department/web-researcher", "web-department/site-crawler"],
        "invariants": ["CLI-only, no API.", "Playwright opzionale (degrada a urllib).", "Trace a URL + screenshot."],
        "script_note": "`scripts/web_research.py` usa Playwright se presente, altrimenti urllib.",
        "trace": "risponde a 'siti web o ricerca estremamente avanzata'.",
    },
    {
        "name": "repo-study-skill", "tier": T,
        "description": "Scanner READ-ONLY di repo/cartelle: mappa struttura, tipi di file, entrypoint, README. Mai modifica l'originale. Base per il deep study del 4o reparto.",
        "tagline": "Mappa la repo in sola lettura per il deep study (architettura/decisioni).",
        "does": ["Scansiona una cartella ignorando .git/node_modules/binari.",
                 "Mappa conteggi, estensioni, entrypoint, README in repo-structure.json.",
                 "Garantisce la sola lettura: nessun file modificato."],
        "usage": ["python skills/tier2-functional/repo-study-skill/scripts/scan_repo.py --path <repo> --run myrun"],
        "uses_scripts": ["scripts/scan_repo.py"],
        "agents": ["projects-repos-workloads-department/repo-deep-study", "projects-repos-workloads-department/department-lead"],
        "invariants": ["SOLA LETTURA: mai modifica l'originale.", "Trace a file:riga.", "Ignora binari/vendored."],
        "script_note": "`scripts/scan_repo.py` e' read-only (stdlib only).",
        "trace": "risponde a '4o reparto: studiarlo nei minimi dettagli, non lo devi modificare'.",
    },
    {
        "name": "content-forge-bridge-skill", "tier": T,
        "description": "Ponte verso content-forge: assembla forge-input/ (analisi+atomi+transcript+trace) da una run e prepara il comando /forge --target=wiki. Garantisce MKD e tracciabilita'.",
        "tagline": "Prepara il materiale e lo passa a content-forge per le note wiki.",
        "does": ["Raccoglie in forge-input/ tutti i materiali della run (analisi, atomi, transcript).",
                 "Scrive un INDEX con le fonti e il comando /forge suggerito.",
                 "Lascia all'agente content-forge-invoker l'invocazione di /forge --target=wiki."],
        "usage": ["python skills/tier2-functional/content-forge-bridge-skill/scripts/prepare_forge_input.py --run myrun",
                  "/forge runs/myrun/forge-input/ --target=wiki --name myrun"],
        "uses_scripts": ["scripts/prepare_forge_input.py"],
        "controls": ["content-forge (skill esterna /forge)"],
        "agents": ["forge-wiki-department/content-forge-invoker"],
        "script_note": "`scripts/prepare_forge_input.py` assembla l'input; il forging vero lo fa la skill content-forge.",
        "trace": "risponde a 'tutto va portato in content-forge'.",
    },
    {
        "name": "wiki-writer-skill", "tier": T,
        "description": "Scrive le note forgiate nella wiki di Digital Empire (sottocartella per tipo) e aggiorna log.md. Auto-rileva second-brain-vault/wiki. Evita sovrascritture.",
        "tagline": "Deposita le note nella wiki di Digital Empire + aggiorna il log.",
        "does": ["Sceglie la sottocartella wiki per tipo (sources/concepts/tools/synthesis).",
                 "Scrive le note con front-matter (fonte/data/topic) e aggiorna wiki/log.md.",
                 "Auto-rileva il percorso della wiki risalendo le cartelle."],
        "usage": ["python skills/tier2-functional/wiki-writer-skill/scripts/write.py --note runs/myrun/wiki-notes/ --kind external --source <url>"],
        "uses_scripts": ["scripts/write.py (wrapper) -> ../../scripts/wiki_writer.py (motore)"],
        "agents": ["forge-wiki-department/wiki-writer"],
        "script_note": "`scripts/write.py` mappa il tipo a sottocartella e delega a `scripts/wiki_writer.py`.",
        "trace": "realizza 'aggiungere contenuto alla wiki connessa a Claude Code'.",
    },
    {
        "name": "update-proposer-skill", "tier": T,
        "description": "Confronta gli atomi di una run con i workflow esistenti e produce uno scheletro di update-proposals.md (match atomo->workflow). Solo proposte, mai modifica.",
        "tagline": "Dai nuovi atomi a proposte concrete per migliorare i workflow esistenti.",
        "does": ["Carica atoms.json della run e i workflow noti (workflow-state + lista).",
                 "Trova candidati match atomo->workflow per parole chiave.",
                 "Scrive update-proposals.md che l'agente raffina con proposte e trace."],
        "usage": ["python skills/tier2-functional/update-proposer-skill/scripts/update_proposer.py --run myrun"],
        "uses_scripts": ["scripts/update_proposer.py"],
        "agents": ["forge-wiki-department/update-proposer", "projects-repos-workloads-department/workload-comparator"],
        "invariants": ["Solo PROPOSTE: nessun workflow modificato.", "Trace alla fonte ispiratrice."],
        "script_note": "`scripts/update_proposer.py` produce lo scheletro dei candidati.",
        "trace": "risponde a 'la wiki interroga su come aggiornare i flussi esistenti'.",
    },
    {
        "name": "cli-doc-skill", "tier": T,
        "description": "Genera report leggibili (stile cli-printing-press) da una run: cosa e' stato ingerito, dove e' finito, con le trace principali. Per il deliverable finale all'utente.",
        "tagline": "Il report finale leggibile della run (cosa/dove/trace).",
        "does": ["Legge gli artefatti della run (ingest, frame, analisi, note wiki, proposte).",
                 "Assembla runs/<run-id>/REPORT.md strutturato e leggibile.",
                 "Elenca le trace principali fonte->frame->nota."],
        "usage": ["python skills/tier2-functional/cli-doc-skill/scripts/make_report.py --run myrun"],
        "uses_scripts": ["scripts/make_report.py"],
        "agents": ["forge-wiki-department/knowledge-packager"],
        "script_note": "`scripts/make_report.py` assembla il report dai file della run.",
        "trace": "usa cli-printing-press per output professionale, come da repo fornita.",
    },
]
