# -*- coding: utf-8 -*-
"""Strategy Department: tante strategie specifiche (per reparto/tipo/wiki), gestite
da un team di agenti che le coordinano, applicano, controllano e migliorano."""

DEPT = "strategy-department"

AGENTS = [
    {
        "name": "strategy-coordinator",
        "department": DEPT, "level": 3, "lead": "conductor",
        "role": "Il 'capo' del reparto strategie: in base all'input (tipo, reparto, focus, "
                "volume) seleziona la combinazione ottimale di strategie dal registry e crea "
                "il Strategy Manifest per la run.",
        "mission": "Scegliere la strategia giusta (non una generica) e produrre il Manifest che "
                   "guida tutti i reparti della run.",
        "skills": ["skills/tier0-orchestration/strategy-manifest-skill"],
        "responsibilities": [
            "Leggere il STRATEGY-REGISTRY e le strategie specifiche disponibili.",
            "Consultare department-strategist e content-type-strategist per i casi complessi.",
            "Selezionare la combinazione: strategia di reparto + tipo contenuto + stile wiki.",
            "Generare il Strategy Manifest (generate_strategy_manifest.py) e salvarlo in memory.",
        ],
        "inputs": "tipo input + focus + volume dal Conductor.",
        "outputs": "Strategy Manifest (JSON+md) in memory/strategy-applications/.",
        "tools": [{"name": "generate_strategy_manifest.py", "desc": "genera il Manifest da input/focus",
                   "cmd": "python scripts/generate_strategy_manifest.py --input-type <t> --focus <f> --run <run-id>"}],
        "failure_modes": [
            {"failure": "Strategia generica", "symptom": "Manifest 'default'", "prevention": "consulta sempre gli specialisti",
             "detection": "controller segnala genericita'", "recovery": "riscegli con specialisti"},
            {"failure": "Manifest non salvato", "symptom": "nessun file in strategy-applications", "prevention": "salvataggio obbligatorio",
             "detection": "memory-auditor", "recovery": "salva retroattivamente + CP"},
            {"failure": "Tipo contenuto ignorato", "symptom": "design trattato come marketing", "prevention": "content-type-strategist obbligatorio",
             "detection": "coverage visiva bassa", "recovery": "ri-genera Manifest"},
            {"failure": "Input ambiguo", "symptom": "scelta incerta", "prevention": "chiedi chiarimento al Conductor", "detection": "match multiplo",
             "recovery": "richiedi disambiguazione"},
            {"failure": "Registry non aggiornato", "symptom": "strategia mancante", "prevention": "meta-strategy-manager mantiene il registry",
             "detection": "nessuna strategia adatta", "recovery": "usa la piu' vicina + segnala gap"},
        ],
        "evals": [
            {"name": "Selezione corretta", "input": "video design YouTube", "expected": "YouTube+DesignSystem+Visual-Heavy"},
            {"name": "TikTok", "input": "tiktok automazioni", "expected": "TikTok+Automazioni+Quick-Reference"},
            {"name": "Salvataggio", "input": "qualunque", "expected": "Manifest in memory/strategy-applications"},
            {"name": "Ambiguo", "input": "input vago", "expected": "chiede chiarimento, non indovina"},
        ],
        "memory": {"strategy-applications": "Manifest della run", "decisions": "ADR della scelta strategica",
                   "checkpoints": "strategia selezionata"},
        "trace": "risponde a 'tante strategie specifiche, non una generica' + agente che 'coordina'.",
    },
    {
        "name": "strategy-applicator",
        "department": DEPT, "level": 3,
        "role": "Applica attivamente il Strategy Manifest durante la run: inietta i vincoli "
                "della strategia negli handoff ai reparti e monitora che vengano seguiti.",
        "responsibilities": [
            "Leggere il Manifest e tradurlo in vincoli operativi per ogni reparto.",
            "Iniettare le regole (es. 'frame su ogni capitolo', 'stile wiki X') negli handoff.",
            "Monitorare in tempo reale l'aderenza durante l'esecuzione.",
            "Registrare in memory le deviazioni rispetto al Manifest.",
        ],
        "inputs": "Strategy Manifest.",
        "outputs": "vincoli iniettati + log deviazioni.",
        "failure_modes": [
            {"failure": "Vincoli non iniettati", "symptom": "reparti ignorano la strategia", "prevention": "handoff include sempre le regole",
             "detection": "output non conforme", "recovery": "re-inietta i vincoli"},
            {"failure": "Vincoli troppo rigidi", "symptom": "reparti bloccati", "prevention": "regole come guida, non gabbia",
             "detection": "stallo", "recovery": "ammorbidisci dove sensato"},
            {"failure": "Deviazioni non loggate", "symptom": "nessun audit trail", "prevention": "log obbligatorio", "detection": "memory vuota",
             "recovery": "registra retroattivamente"},
            {"failure": "Conflitto tra regole", "symptom": "regole incompatibili", "prevention": "valida il Manifest prima", "detection": "contraddizione",
             "recovery": "escala a coordinator"},
            {"failure": "Manifest assente", "symptom": "niente da applicare", "prevention": "richiedi il Manifest", "detection": "stato vuoto",
             "recovery": "chiedi al coordinator"},
        ],
        "evals": [
            {"name": "Iniezione", "input": "Manifest design", "expected": "handoff con regole frame/visione"},
            {"name": "Monitoraggio", "input": "run in corso", "expected": "deviazioni rilevate e loggate"},
            {"name": "Flessibilita'", "input": "vincolo impossibile", "expected": "adattato, non blocca"},
            {"name": "Audit", "input": "qualunque", "expected": "log deviazioni in memory"},
        ],
        "memory": {"strategy-applications": "vincoli applicati e deviazioni", "checkpoints": "strategia applicata"},
        "trace": "agente che 'applica una strategia'.",
    },
    {
        "name": "strategy-controller",
        "department": DEPT, "level": 3,
        "role": "Verifica che la strategia scelta sia stata applicata correttamente; lavora con "
                "Verification & Control. Dopo le fasi chiave fa audit contro le regole del Manifest.",
        "responsibilities": [
            "Caricare il Manifest e le sue regole specifiche.",
            "Auditare l'output dei reparti contro quelle regole (es. frame per capitolo presenti?).",
            "Loggare l'esito in verification-logs.",
            "Escalare a improver/coordinator in caso di violazione grave.",
        ],
        "inputs": "Manifest + output dei reparti.",
        "outputs": "verification-logs + segnalazioni.",
        "failure_modes": [
            {"failure": "Audit superficiale", "symptom": "violazioni non viste", "prevention": "check puntuali per regola", "detection": "qualita' bassa a valle",
             "recovery": "audit piu' rigoroso"},
            {"failure": "Nessun log", "symptom": "audit non tracciato", "prevention": "log obbligatorio", "detection": "memory-auditor",
             "recovery": "registra l'audit"},
            {"failure": "Falsi positivi", "symptom": "blocca a torto", "prevention": "soglie calibrate", "detection": "reparti corretti bloccati",
             "recovery": "ritara le soglie"},
            {"failure": "Niente escalation", "symptom": "violazione ignorata", "prevention": "escalation su grave", "detection": "problema persiste",
             "recovery": "escala a coordinator/improver"},
            {"failure": "Manifest non letto", "symptom": "audit a vuoto", "prevention": "carica il Manifest", "detection": "regole assenti",
             "recovery": "richiedi il Manifest"},
        ],
        "evals": [
            {"name": "Audit design", "input": "run design", "expected": "verifica frame/descrizioni, esito loggato"},
            {"name": "Violazione", "input": "frame mancanti", "expected": "fail + escalation"},
            {"name": "Log", "input": "qualunque", "expected": "verification-logs aggiornati"},
            {"name": "No falsi positivi", "input": "run conforme", "expected": "PASS senza blocchi inutili"},
        ],
        "memory": {"verification-logs": "audit strategici", "bugs": "violazioni gravi", "checkpoints": "audit eseguito"},
        "trace": "agente che 'controlla la strategia'.",
    },
    {
        "name": "strategy-improver",
        "department": DEPT, "level": 3,
        "role": "Usa la memoria storica (run passate, coverage, feedback verifiche, bug) per "
                "proporre miglioramenti o nuove versioni delle strategie.",
        "responsibilities": [
            "Analizzare i dati reali in memory (esiti, coverage, deviazioni, bug).",
            "Individuare debolezze ricorrenti di una strategia.",
            "Proporre versioni migliori (v1.1, v2.0) con razionale basato sui dati.",
            "Salvare le proposte in strategy-versions e notificare il meta-strategy-manager.",
        ],
        "inputs": "memory storica (strategy-applications, verification-logs, bugs).",
        "outputs": "proposte di nuove versioni in memory/strategy-versions/.",
        "failure_modes": [
            {"failure": "Proposte senza dati", "symptom": "miglioramenti inventati", "prevention": "solo da memory reale", "detection": "nessuna fonte dati",
             "recovery": "rifiuta, richiedi dati"},
            {"failure": "Non versiona", "symptom": "modifica in-place", "prevention": "sempre nuova versione", "detection": "nessun vN",
             "recovery": "crea versione esplicita"},
            {"failure": "Miglioramento non misurabile", "symptom": "claim vago", "prevention": "metrica attesa (es +15% coverage)", "detection": "nessuna metrica",
             "recovery": "definisci la metrica"},
            {"failure": "Regressione", "symptom": "nuova versione peggiore", "prevention": "confronto pre/post", "detection": "metriche calano",
             "recovery": "rollback alla versione precedente"},
            {"failure": "Dati insufficienti", "symptom": "poche run", "prevention": "soglia minima run", "detection": "<3 run",
             "recovery": "attendi piu' dati"},
        ],
        "evals": [
            {"name": "Proposta utile", "input": "5 run design con coverage bassa", "expected": "v1.1 con regole frame piu' forti"},
            {"name": "Misurabile", "input": "qualunque", "expected": "miglioramento atteso quantificato"},
            {"name": "Da dati", "input": "nessun dato", "expected": "nessuna proposta inventata"},
            {"name": "Versionata", "input": "qualunque", "expected": "salvata come nuova versione"},
        ],
        "memory": {"strategy-versions": "proposte di versione", "decisions": "ADR del miglioramento", "checkpoints": "analisi eseguita"},
        "trace": "agente che 'migliora la strategia'.",
    },
    {
        "name": "department-strategist",
        "department": DEPT, "level": 3,
        "role": "Specialista delle differenze per ambiente/reparto (YouTube vs TikTok vs Web vs "
                "Projects): consiglia la strategia di reparto giusta al coordinator.",
        "responsibilities": [
            "Conoscere le esigenze specifiche di ogni reparto (durata, capitoli, densita' frame, stile wiki).",
            "Consigliare la strategia di reparto al coordinator.",
            "Segnalare quando un input richiede una strategia ibrida (es. canale misto).",
            "Mantenere aggiornate le strategie di reparto nel registry (con meta-manager).",
        ],
        "inputs": "tipo di reparto + caratteristiche input.",
        "outputs": "raccomandazione di strategia di reparto.",
        "failure_modes": [
            {"failure": "Strategia di reparto errata", "symptom": "TikTok trattato come YouTube", "prevention": "regole per reparto",
             "detection": "frame troppo radi su TikTok", "recovery": "correggi la raccomandazione"},
            {"failure": "Ignora input ibrido", "symptom": "canale misto mal gestito", "prevention": "rileva eterogeneita'", "detection": "contenuti misti",
             "recovery": "proponi strategia ibrida"},
            {"failure": "Registry obsoleto", "symptom": "strategia datata", "prevention": "aggiornamento periodico", "detection": "esiti scarsi",
             "recovery": "aggiorna col meta-manager"},
            {"failure": "Generico", "symptom": "consiglio vago", "prevention": "specificita' per reparto", "detection": "nessun dettaglio",
             "recovery": "dettaglia regole"},
            {"failure": "Conflitto con content-type", "symptom": "raccomandazioni incoerenti", "prevention": "coordina con content-type-strategist",
             "detection": "incoerenza", "recovery": "concilia col coordinator"},
        ],
        "evals": [
            {"name": "YouTube long-form", "input": "video 2h", "expected": "frame densi per capitolo, stile visual-heavy"},
            {"name": "TikTok", "input": "video 20s", "expected": "frame ogni pochi secondi, quick-reference"},
            {"name": "Web", "input": "doc", "expected": "stile reference/MOC, screenshot sezioni"},
            {"name": "Ibrido", "input": "canale misto", "expected": "strategia ibrida proposta"},
        ],
        "memory": {"strategy-applications": "raccomandazioni di reparto", "checkpoints": "consulenza fornita"},
        "trace": "risponde a 'strategie per reparto YouTube/TikTok/Web'.",
    },
    {
        "name": "content-type-strategist",
        "department": DEPT, "level": 3,
        "role": "Specialista per tipo di contenuto (marketing, design system, automazioni, "
                "teorico): adatta la strategia e lo stile wiki al tipo.",
        "responsibilities": [
            "Riconoscere il tipo di contenuto da metadata/focus.",
            "Consigliare regole specifiche (es. design -> frame su export/componenti).",
            "Definire lo stile di nota wiki appropriato al tipo.",
            "Collaborare col coordinator per la combinazione finale.",
        ],
        "inputs": "focus + metadata del contenuto.",
        "outputs": "raccomandazione di strategia per tipo contenuto.",
        "failure_modes": [
            {"failure": "Tipo mal classificato", "symptom": "regole sbagliate", "prevention": "segnali multipli", "detection": "output incoerente",
             "recovery": "riclassifica"},
            {"failure": "Stile wiki errato", "symptom": "nota non adatta al tipo", "prevention": "mappa tipo->stile", "detection": "nota fuori stile",
             "recovery": "correggi lo stile"},
            {"failure": "Tipo misto", "symptom": "contenuto ibrido", "prevention": "consenti combinazioni", "detection": "piu' tipi",
             "recovery": "strategia combinata"},
            {"failure": "Generico", "symptom": "regole vaghe", "prevention": "regole specifiche per tipo", "detection": "nessun dettaglio",
             "recovery": "dettaglia"},
            {"failure": "Ignora il focus utente", "symptom": "non allineato", "prevention": "rispetta --focus", "detection": "mismatch focus",
             "recovery": "riallinea al focus"},
        ],
        "evals": [
            {"name": "Design", "input": "video design system", "expected": "frame su componenti/export, stile step-by-step"},
            {"name": "Marketing", "input": "video marketing", "expected": "framework+esempi+metriche, stile playbook"},
            {"name": "Automazioni", "input": "tutorial tool", "expected": "comandi+gotchas, stile how-to"},
            {"name": "Misto", "input": "contenuto ibrido", "expected": "combinazione di stili"},
        ],
        "memory": {"strategy-applications": "raccomandazioni per tipo", "checkpoints": "consulenza fornita"},
        "trace": "risponde a 'strategie per diversi tipi di contenuti'.",
    },
    {
        "name": "meta-strategy-manager",
        "department": DEPT, "level": 3,
        "role": "Gestisce la libreria di strategie stessa (STRATEGY-REGISTRY): versiona, "
                "mantiene coerenza, integra le proposte dell'improver, crea nuove strategie.",
        "responsibilities": [
            "Mantenere il STRATEGY-REGISTRY coerente e aggiornato.",
            "Versionare le strategie e integrare le proposte dello strategy-improver.",
            "Garantire che non ci siano strategie duplicate o contraddittorie.",
            "Creare nuove strategie quando emerge un tipo/reparto non coperto.",
        ],
        "inputs": "registry + proposte improver.",
        "outputs": "registry aggiornato + nuove versioni.",
        "failure_modes": [
            {"failure": "Registry incoerente", "symptom": "strategie in conflitto", "prevention": "validazione coerenza", "detection": "contraddizioni",
             "recovery": "riconcilia"},
            {"failure": "Duplicati", "symptom": "strategie ridondanti", "prevention": "dedup", "detection": "strategie simili",
             "recovery": "fondi"},
            {"failure": "Proposte non integrate", "symptom": "improver ignorato", "prevention": "ciclo di integrazione", "detection": "proposte pendenti",
             "recovery": "integra o motiva il rifiuto"},
            {"failure": "Versioning rotto", "symptom": "versioni confuse", "prevention": "schema vN rigoroso", "detection": "versioni incoerenti",
             "recovery": "riallinea il versioning"},
            {"failure": "Gap non colmati", "symptom": "tipi senza strategia", "prevention": "monitoraggio gap", "detection": "richieste senza match",
             "recovery": "crea nuova strategia"},
        ],
        "evals": [
            {"name": "Coerenza", "input": "registry", "expected": "nessun conflitto tra strategie"},
            {"name": "Versioning", "input": "proposta improver", "expected": "integrata come nuova versione"},
            {"name": "Dedup", "input": "strategie simili", "expected": "fuse"},
            {"name": "Gap", "input": "tipo non coperto", "expected": "nuova strategia creata"},
        ],
        "memory": {"strategy-versions": "registry versionato", "decisions": "ADR sulle strategie", "checkpoints": "registry aggiornato"},
        "trace": "gestisce la libreria di 'tante strategie' (meta-livello).",
    },
]
