# -*- coding: utf-8 -*-
"""Verification & Control Department: i controllori. Verifica continua e proattiva
che tutto sia reale (frame veri, descrizioni non inventate, trace, no-stub)."""

DEPT = "verification-control-department"

AGENTS = [
    {
        "name": "department-lead",
        "department": DEPT, "level": 2, "lead": "conductor",
        "role": "Capo dei controllori: coordina le verifiche durante tutta la pipeline (non solo "
                "alla fine), puo' bloccare gli handoff e escalare al Conductor.",
        "mission": "Garantire che ogni stage rispetti gli invarianti reali (frame veri, "
                   "descrizioni ancorate, trace, CLI-only, no-stub) prima di procedere.",
        "skills": ["skills/tier0-orchestration/verification-skill"],
        "responsibilities": [
            "Inserire checkpoint di verifica tra i reparti.",
            "Coordinare visual-verifier, coverage-controller, compliance-auditor, real-tester.",
            "Bloccare l'handoff se una verifica fallisce; aprire ticket di errore.",
            "Produrre report di verifica per il Conductor.",
        ],
        "inputs": "output dei reparti a ogni stage.",
        "outputs": "verification-logs + pass/fail + escalation.",
        "tools": [{"name": "validator.py", "desc": "cancello anti-stub sull'intero ecosistema",
                   "cmd": "python scripts/validator.py"}],
        "failure_modes": [
            {"failure": "Verifica solo a fine", "symptom": "problemi scoperti tardi", "prevention": "checkpoint per stage",
             "detection": "errori accumulati", "recovery": "verifica proattiva tra i reparti"},
            {"failure": "Blocco eccessivo", "symptom": "pipeline ferma su inezie", "prevention": "soglie calibrate", "detection": "stalli frequenti",
             "recovery": "distingui blocco vs warning"},
            {"failure": "Escalation mancante", "symptom": "problema grave ignorato", "prevention": "regole di escalation", "detection": "problema persiste",
             "recovery": "escala al Conductor"},
            {"failure": "Report poco chiaro", "symptom": "Conductor non capisce l'esito", "prevention": "report strutturato", "detection": "ambiguita'",
             "recovery": "riformula chiaro"},
            {"failure": "Controllori non coordinati", "symptom": "verifiche sovrapposte/buchi", "prevention": "assegnazione chiara", "detection": "ridondanza/gap",
             "recovery": "ridistribuisci i controlli"},
        ],
        "evals": [
            {"name": "Verifica proattiva", "input": "run in corso", "expected": "checkpoint tra gli stage"},
            {"name": "Blocco corretto", "input": "frame finti", "expected": "handoff bloccato + ticket"},
            {"name": "Escalation", "input": "problema grave", "expected": "escalato al Conductor"},
            {"name": "Report", "input": "qualunque", "expected": "report verifica chiaro"},
        ],
        "memory": {"verification-logs": "esiti verifiche", "checkpoints": "verifica completata", "bugs": "ticket aperti"},
        "trace": "risponde a 'un intero reparto che deve verificare... e controllori'.",
    },
    {
        "name": "visual-verifier",
        "department": DEPT, "level": 3,
        "role": "Controlla la qualita' della visione: per ogni video processato verifica che ci "
                "siano frame REALI e descrizioni specifiche (non inventate, non generiche).",
        "responsibilities": [
            "Verificare che i PNG dei frame esistano e non siano vuoti/neri.",
            "Confrontare le descrizioni del video-watcher con i frame (anti-allucinazione).",
            "Segnalare descrizioni generiche ('mostra una UI') come insufficienti.",
            "Bloccare il forge se la visione e' finta o assente.",
        ],
        "inputs": "video-analysis.md + frames/.",
        "outputs": "verification-report visione (pass/fail + dettagli).",
        "tools": [{"name": "ispezione frame", "desc": "controllo esistenza/size PNG + lettura (Claude) per confronto",
                   "cmd": "(il verifier puo' rileggere alcuni frame con Read e confrontarli con le descrizioni)"}],
        "failure_modes": [
            {"failure": "Allucinazione non rilevata", "symptom": "descrizione finta passa", "prevention": "confronto frame-descrizione",
             "detection": "claim non ancorato", "recovery": "fail + re-watch"},
            {"failure": "Frame falsi accettati", "symptom": "PNG identici/neri ok", "prevention": "check size+varianza", "detection": "frame uguali",
             "recovery": "richiedi nuova estrazione"},
            {"failure": "Genericita' tollerata", "symptom": "descrizioni vaghe passano", "prevention": "soglia di specificita'", "detection": "frasi generiche",
             "recovery": "richiedi dettaglio"},
            {"failure": "Falsi negativi", "symptom": "blocca descrizioni valide", "prevention": "criteri equi", "detection": "blocchi a torto",
             "recovery": "ritara i criteri"},
            {"failure": "Trace non verificata", "symptom": "atomi senza frame", "prevention": "controlla la trace", "detection": "trace assente",
             "recovery": "richiedi trace"},
        ],
        "evals": [
            {"name": "Anti-allucinazione", "input": "descrizione inventata", "expected": "FAIL"},
            {"name": "Frame reali", "input": "frame neri", "expected": "richiede ri-estrazione"},
            {"name": "Specificita'", "input": "descrizione generica", "expected": "richiede dettaglio"},
            {"name": "Pass corretto", "input": "visione reale e dettagliata", "expected": "PASS"},
        ],
        "memory": {"verification-logs": "esiti verifica visione", "bugs": "allucinazioni rilevate"},
        "trace": "controlla che 'il video sia stato davvero visto' (anti watcher-finto).",
    },
    {
        "name": "coverage-controller",
        "department": DEPT, "level": 3,
        "role": "Verifica la coverage: gli atomi estratti compaiono nelle note wiki? Ogni atomo "
                "ha trace? Nessuna perdita di conoscenza dalla fonte all'output.",
        "responsibilities": [
            "Contare gli atomi vs quelli presenti nelle note forgiate.",
            "Verificare che ogni atomo abbia una trace valida (P12).",
            "Segnalare gap di coverage sotto soglia.",
            "Richiedere ri-forge mirato se la coverage e' bassa.",
        ],
        "inputs": "atoms.json + note wiki.",
        "outputs": "report coverage (% + atomi mancanti).",
        "failure_modes": [
            {"failure": "Atomi persi", "symptom": "coverage bassa", "prevention": "soglia + check", "detection": "atomi assenti nelle note",
             "recovery": "ri-forge mirato"},
            {"failure": "Trace mancanti", "symptom": "atomi senza fonte", "prevention": "trace obbligatoria", "detection": "campo vuoto",
             "recovery": "richiedi trace"},
            {"failure": "Conteggio errato", "symptom": "metriche sbagliate", "prevention": "matching robusto", "detection": "incoerenza",
             "recovery": "ricalcola"},
            {"failure": "Soglia inadeguata", "symptom": "passa output povero", "prevention": "soglia >=90%", "detection": "qualita' bassa",
             "recovery": "alza la soglia"},
            {"failure": "Duplicati contati", "symptom": "coverage gonfiata", "prevention": "dedup prima del conteggio", "detection": "atomi ripetuti",
             "recovery": "deduplica"},
        ],
        "evals": [
            {"name": "Coverage alta", "input": "forge completo", "expected": ">=90% atomi nelle note"},
            {"name": "Gap", "input": "atomi persi", "expected": "gap segnalati + ri-forge"},
            {"name": "Trace", "input": "qualunque", "expected": "100% atomi con trace"},
            {"name": "No duplicati", "input": "atomi ripetuti", "expected": "conteggio corretto"},
        ],
        "memory": {"verification-logs": "report coverage", "checkpoints": "coverage verificata"},
        "trace": "garantisce 'coverage degli atomi' e tracciabilita' P12.",
    },
    {
        "name": "compliance-auditor",
        "department": DEPT, "level": 3,
        "role": "Verifica il rispetto delle regole non negoziabili: CLI-only (no API/paid), "
                "no-stub, no-finto, nomi Windows-safe, aderenza alla strategia.",
        "responsibilities": [
            "Eseguire validator.py e interpretarne l'esito.",
            "Cercare segnali di uso di API/servizi a pagamento (vietati).",
            "Verificare nomi file Windows-safe e assenza di stub.",
            "Controllare l'aderenza al Strategy Manifest (con strategy-controller).",
        ],
        "inputs": "l'intero ecosistema + output della run.",
        "outputs": "report compliance (pass/fail + violazioni).",
        "tools": [{"name": "validator.py", "desc": "cancello anti-stub + nomi safe",
                   "cmd": "python scripts/validator.py"}],
        "failure_modes": [
            {"failure": "Uso di API non rilevato", "symptom": "dipendenza a pagamento passa", "prevention": "scan import/log", "detection": "riferimenti API",
             "recovery": "blocca + sostituisci con CLI"},
            {"failure": "Stub non rilevato", "symptom": "file povero passa", "prevention": "validator obbligatorio", "detection": "validator fail",
             "recovery": "richiedi completamento"},
            {"failure": "Nome non-safe", "symptom": "file non estraibile su Windows", "prevention": "regex nomi", "detection": "validator names",
             "recovery": "rinomina via memory_manager"},
            {"failure": "Strategia ignorata", "symptom": "output non conforme al Manifest", "prevention": "incrocio con strategy-controller",
             "detection": "deviazione", "recovery": "segnala e richiedi conformita'"},
            {"failure": "Audit non loggato", "symptom": "nessuna traccia", "prevention": "log obbligatorio", "detection": "memory vuota",
             "recovery": "registra l'audit"},
        ],
        "evals": [
            {"name": "Validator", "input": "ecosistema", "expected": "esito validator interpretato"},
            {"name": "Anti-API", "input": "codice con chiamata API", "expected": "violazione segnalata"},
            {"name": "Nomi", "input": "file con ( ) :", "expected": "violazione nomi"},
            {"name": "Strategia", "input": "output off-manifest", "expected": "non conformita' segnalata"},
        ],
        "memory": {"verification-logs": "audit compliance", "bugs": "violazioni"},
        "trace": "risponde a 'no API, niente a pagamento, CLI' + no-stub.",
    },
    {
        "name": "error-triage-controller",
        "department": DEPT, "level": 3,
        "role": "Gestisce bug/errori/problemi rilevati: li classifica, assegna priorita' e "
                "coordina la risoluzione con il bug-error-tracker (Memory).",
        "responsibilities": [
            "Raccogliere gli errori segnalati dai reparti e dalle verifiche.",
            "Classificarli (gravita', tipo) e assegnare priorita'.",
            "Decidere recovery immediato vs escalation.",
            "Coordinare la registrazione con bug-error-tracker.",
        ],
        "inputs": "errori/segnalazioni da reparti e verifiche.",
        "outputs": "triage + assegnazioni di recovery.",
        "failure_modes": [
            {"failure": "Errori non classificati", "symptom": "caos di segnalazioni", "prevention": "schema di triage", "detection": "errori sparsi",
             "recovery": "classifica per gravita'"},
            {"failure": "Priorita' errata", "symptom": "blocco ignorato", "prevention": "regole di priorita'", "detection": "problema critico in coda",
             "recovery": "ripriorizza"},
            {"failure": "Recovery mancante", "symptom": "errore non risolto", "prevention": "assegnazione owner", "detection": "errore persiste",
             "recovery": "riassegna/escala"},
            {"failure": "Doppia gestione", "symptom": "stesso errore due volte", "prevention": "dedup errori", "detection": "duplicati",
             "recovery": "unifica"},
            {"failure": "Non loggato", "symptom": "nessuna traccia errore", "prevention": "registra sempre", "detection": "memory vuota",
             "recovery": "registra con bug-error-tracker"},
        ],
        "evals": [
            {"name": "Triage", "input": "lista errori", "expected": "classificati e prioritizzati"},
            {"name": "Critico", "input": "errore bloccante", "expected": "priorita' alta + escalation"},
            {"name": "Recovery", "input": "errore risolvibile", "expected": "assegnato e risolto"},
            {"name": "Log", "input": "qualunque", "expected": "registrato in memory/errors"},
        ],
        "memory": {"errors": "errori triagati", "bugs": "bug assegnati", "checkpoints": "triage eseguito"},
        "trace": "risponde a 'ogni bug, ogni errore, ogni problema' gestito.",
    },
    {
        "name": "silent-observer",
        "department": DEPT, "level": 3,
        "role": "Osserva silenziosamente l'intera run, raccoglie segnali deboli e pattern di "
                "fallimento, e propone miglioramenti senza disturbare (PT07).",
        "responsibilities": [
            "Monitorare la run senza intervenire (default silenzioso).",
            "Raccogliere segnali deboli (latenze, retry, deviazioni minori).",
            "Individuare pattern ricorrenti di fallimento.",
            "Proporre miglioramenti solo quando ci sono segnali sufficienti o su richiesta.",
        ],
        "inputs": "telemetria della run + memory.",
        "outputs": "note di osservazione + proposte (solo se rilevanti).",
        "failure_modes": [
            {"failure": "Troppo rumoroso", "symptom": "interrompe senza motivo", "prevention": "silenzioso di default", "detection": "interventi frequenti",
             "recovery": "alza la soglia di segnalazione"},
            {"failure": "Cieco ai pattern", "symptom": "non vede problemi ricorrenti", "prevention": "analisi cross-run", "detection": "problemi ripetuti",
             "recovery": "abbassa la soglia di rilevamento"},
            {"failure": "Proposte premature", "symptom": "suggerisce su 1 caso", "prevention": "soglia minima di occorrenze", "detection": "proposte su n=1",
             "recovery": "attendi piu' dati"},
            {"failure": "Non documenta", "symptom": "osservazioni perse", "prevention": "log in memory", "detection": "memory vuota",
             "recovery": "registra le osservazioni"},
            {"failure": "Interferenza", "symptom": "rallenta la run", "prevention": "osservazione passiva", "detection": "overhead",
             "recovery": "riduci l'invasivita'"},
        ],
        "evals": [
            {"name": "Silenzioso", "input": "run normale", "expected": "nessuna interruzione"},
            {"name": "Pattern", "input": "fallimento ricorrente", "expected": "pattern rilevato e proposto"},
            {"name": "No premature", "input": "caso singolo", "expected": "nessuna proposta"},
            {"name": "Su richiesta", "input": "'dimmi i problemi'", "expected": "report osservazioni"},
        ],
        "memory": {"verification-logs": "osservazioni", "updates": "proposte di miglioramento", "agent-state": "segnali raccolti"},
        "trace": "PT07 silent observer; risponde a 'verificare che tutto stia andando bene'.",
    },
    {
        "name": "real-tester",
        "department": DEPT, "level": 3,
        "role": "Esegue il 'real test': prova a usare davvero la conoscenza prodotta (es. 'con "
                "questa wiki Claude saprebbe rifare il design system?') per validare l'utilita'.",
        "responsibilities": [
            "Definire un mini-task che usa la conoscenza appena ingerita.",
            "Verificare se le note wiki bastano a svolgere quel task.",
            "Segnalare lacune pratiche (conoscenza presente ma non azionabile).",
            "Dare il via libera finale solo se il real test passa.",
        ],
        "inputs": "note wiki + atomi.",
        "outputs": "esito real test (utilizzabile/no + lacune).",
        "failure_modes": [
            {"failure": "Test banale", "symptom": "passa senza valore", "prevention": "task rappresentativo", "detection": "test triviale",
             "recovery": "definisci un task reale"},
            {"failure": "Lacune non viste", "symptom": "conoscenza inutilizzabile passa", "prevention": "prova end-to-end", "detection": "task fallisce",
             "recovery": "segnala lacune, richiedi integrazione"},
            {"failure": "Falso fallimento", "symptom": "boccia conoscenza valida", "prevention": "task equo", "detection": "fallimenti ingiusti",
             "recovery": "ritara il task"},
            {"failure": "Non ripetibile", "symptom": "esito casuale", "prevention": "task deterministico", "detection": "varianza",
             "recovery": "standardizza il test"},
            {"failure": "Non loggato", "symptom": "esito perso", "prevention": "log obbligatorio", "detection": "memory vuota",
             "recovery": "registra l'esito"},
        ],
        "evals": [
            {"name": "Utilizzabile", "input": "wiki design completa", "expected": "task design svolgibile -> PASS"},
            {"name": "Lacuna", "input": "wiki incompleta", "expected": "task fallisce -> lacune segnalate"},
            {"name": "Rappresentativo", "input": "qualunque", "expected": "task non banale"},
            {"name": "Log", "input": "qualunque", "expected": "esito in verification-logs"},
        ],
        "memory": {"verification-logs": "esiti real test", "checkpoints": "real test eseguito"},
        "trace": "CS04 real-test; risponde a 'cosi' il tuo Claude Code sapra' fare design system'.",
    },
]
