"""Nucleo del dominio: modelli, stati, regole e persistenza."""

from .enums import (
    AgentLevel,
    ApprovalDecision,
    AssetKind,
    CopyReviewStatus,
    ProductionJobStatus,
    ReviewOutcome,
    WorkflowState,
)
from .exceptions import (
    ApprovalRequiredError,
    AuthorizationError,
    AutomationNotConfiguredError,
    BrowserAutomationError,
    FactoryError,
    FlikAdapterError,
    InvalidTransitionError,
    NicheLockError,
    OriginalityCheckError,
    RegulatoryBlockError,
)
from .models import (
    Approval,
    ChannelDiscovery,
    CompetitorReport,
    CopyAsset,
    NicheProposal,
    ProductionJob,
    ReviewRequest,
    ScriptAsset,
    ThumbnailAsset,
    TranscriptAsset,
    VideoCandidate,
    WorkflowEvent,
    WorkflowRun,
)
from .reporting import ReportingService
from .repositories import (
    InMemoryWorkflowRepository,
    JsonFileWorkflowRepository,
    WorkflowRepository,
)
from .workflow import ALLOWED_TRANSITIONS, YouTubeFactoryWorkflow

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AgentLevel",
    "Approval",
    "ApprovalDecision",
    "ApprovalRequiredError",
    "AssetKind",
    "AuthorizationError",
    "AutomationNotConfiguredError",
    "BrowserAutomationError",
    "ChannelDiscovery",
    "CompetitorReport",
    "CopyAsset",
    "CopyReviewStatus",
    "FactoryError",
    "FlikAdapterError",
    "InMemoryWorkflowRepository",
    "InvalidTransitionError",
    "JsonFileWorkflowRepository",
    "NicheLockError",
    "NicheProposal",
    "OriginalityCheckError",
    "ProductionJob",
    "ProductionJobStatus",
    "RegulatoryBlockError",
    "ReportingService",
    "ReviewOutcome",
    "ReviewRequest",
    "ScriptAsset",
    "ThumbnailAsset",
    "TranscriptAsset",
    "VideoCandidate",
    "WorkflowEvent",
    "WorkflowRepository",
    "WorkflowRun",
    "WorkflowState",
    "YouTubeFactoryWorkflow",
]
